Scripts/TrialOfTheChampion: Rescripting whole dungeon [WIP][WIP]
TrinityCore/TrinityCore pull request #14938
Opened 2015-06-22 21:25 UTC by Appled

WIP

Working on rescripting the whole dungeon. Flags and other data in SQL file are from sniffs. Although not everything is in the sniffs and I have gathered myself dozens videos of ToC instance from both alliance and horde back from actual Wotlk era.

TODO list
- Misc stuff
  - - [x] Announcer's gossip
  - - [x] Main Gate LoS disabled
- First boss fight: Grand Champions of Horde/Alliance
  - - [x] Player vehicles
  - - [x] Lesser Champions
  - - [x] Roleplaying event before jousting event
  - - [x] Jousting Event (including 'looking for new mount' phase)
  - - [ ] Actual boss fight against Grand Champions
  - - [ ] Loot chest
- Second boss fight: Argent Champions
  - - [ ] Trash packs
  - - [ ] Eadric the Pure
  - - [ ] Argent Confessor Paletress
  - - [ ] Loot chest
- Third boss fight: The Black Knight
  - - [ ] The summoning and actual boss fight

Please tell me if my coding is not correct or something in the code bothers you. We can discuss.

2015-06-22 21:34 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
> +            if (GrandChampionList[uiBoss-1] == 0)
switch? also you can make it really easier, I see many duplicate code

2015-06-22 21:36 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
> +                if (TeamInInstance == ALLIANCE)
what about to create method for it, with textid and npc entry as arguments? you can safe 300 lines

2015-06-22 21:42 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +void DoCastPennant(Creature* me)
you can create struct for AI for these bosses, this is really not good idea (I mean for all those methods)

https://github.com/Appled/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp#L89-L274

2015-06-22 21:49 UTC, MitchesD commented on sql/updates/world/2015_06_23_00_world_toc.sql
> +UPDATE `creature_template` SET `npcflag`='16777216',`speed_run`='1.57143',`spell1`='68505',`spell2`='62575',`spell3`='68282',`spell4`='62552',`VehicleId`='486' WHERE `entry`=@ARGENT_WARHORSE_H;
I am confused, why this line when I see this:
SET @ARGENT_WARHORSE_H := 35644; -- cosmetic vehicle (cannot be used)
npc flag 16777216 is for spellclick, so when it cannot be used why this? Please explain

Btw, these NPCs already  has vehicle ID 486

2015-06-22 21:55 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +                me->ExitVehicle(&me->GetPosition());
bad, use only me->ExitVehicle()

2015-06-22 21:56 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +                me->ExitVehicle(&me->GetPosition());
the same as above

2015-06-22 21:56 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +                me->ExitVehicle(&me->GetPosition());
once more

2015-06-22 21:57 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +                me->ExitVehicle(&me->GetPosition());
again use only ExitVehicle

2015-06-22 21:58 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +                me->ExitVehicle(&me->GetPosition());
how many times did you use that line without compile try?

2015-06-22 21:59 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp
> +        void OnPlayerEnter(Player* player)
better get player team in OnCreatureCreate

2015-06-22 22:00 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp
> +            switch (creature->GetEntry())
why another switch? there is already one above that

2015-06-22 22:01 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
> +                    int x;
maybe use uint8

2015-06-22 22:05 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
> +                switch (uiSummonTimes)
can be done easier

2015-06-23 07:53 UTC, jackpoz commented
does this PR relate in any way with https://github.com/TrinityCore/TrinityCore/pull/14893 or do we have 2 reworks of same instance ?

2015-06-23 07:59 UTC, jackpoz commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +        if (Creature* mount = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_GRAND_CHAMPION_VEHICLE_1)))
the NULL check is not needed here, if it's NULL then https://github.com/TrinityCore/TrinityCore/pull/14938/files#diff-2e14db63ffb42614aa604bc50e478a31R160 will return NULL anyway.

2015-06-23 08:00 UTC, jackpoz commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +    if (!instance)
the whole AI shouldn't even be created if me->GetInstanceScript() is NULL

2015-06-23 08:01 UTC, jackpoz commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +    Player *player;
by leaving player uninitialized you just caused a crash

2015-06-23 08:02 UTC, jackpoz commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +            if ((uiWaypointPath == 1 && waypointId == 3) || ((uiWaypointPath == 2 || uiWaypointPath == 3) && waypointId == 2))
please use enums or defines or anything else instead of magic number like 1,2,3 that don't really tell much about what these checks do

2015-06-24 08:27 UTC, Flameshot commented
If it helps I have my somehow old scripts that worked before Objectguid appeared I can share with you if you want :)

2015-06-24 09:40 UTC, Appled commented
I am not sure do I need your script but you could share it with me anyway. To see if I missed stuff or codestyle improvement. I'll be back on irc approxly in 6 hours so if we discuss more there?

To jackpoz and MitchesD, I have fixed all your comments, and improved and shorted the code. I will test it later today and if it looks good I push the changes. Then I'll continue from todo list.

2015-06-24 12:24 UTC, jackpoz commented
what about https://github.com/TrinityCore/TrinityCore/pull/14938#issuecomment-114395568 ?

2015-06-24 13:37 UTC, Appled commented
Well I started working on toc back in October 2014 and I encountered hardware issues around in last January. Harddrive literaly exploded. Just recently got retrieved most of the data, including toc script. I hadn't created git repo nor anything similiar. Now, recently before I got my hands on this again Aokromes started reworking on this as well. 

So TL;DR we have 2 reworks of the same instance

2015-06-24 16:48 UTC, tkrokli commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +                me->ExitVehicle(&me->GetPosition());
... in addition, `(&me->GetPosition())` on this exact line crashes the Travis build.

2015-06-25 13:19 UTC, Flameshot commented
.cpp / .h Files
http://pastebin.com/gFcu6XVq
http://pastebin.com/dVnM53fM
http://pastebin.com/wttQ189G
http://pastebin.com/mujVcFMu
http://pastebin.com/QFGY3JTV
http://pastebin.com/ragT9Nkp

SQl Code: (I updated it and It works with last TDB)
http://pastebin.com/Cv8Savav

2015-06-25 13:30 UTC, Aokromes commented
delete+insert creature template is evil.

2015-06-25 19:41 UTC, Appled commented
Thanks @Flameshot for providing your scripts. I will take a look at them and add missing changes into my PR.

@Killyana I updated the SQL file. Although it was not a necessary change as currently the gossip menu is handled in the source. Take a look https://github.com/Appled/TrinityCore/blob/3.3.5/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp#L868

2015-06-25 19:43 UTC, Appled commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +void DoCastPennant(Creature* me)
I needed to left 5 methods outside of toc_bossAI as they are also used by the lesser champions and Grand Champions' vehicles.

2015-06-26 16:05 UTC, Flameshot commented
@Appled  no problem. If I can help you somehow just ask.

2015-06-29 17:55 UTC, mik1893 commented
@Appled I also have scripted this, but never converted it properly to TC Standards. I'll gladly share code with you, let's talk on IRC

2015-06-29 21:31 UTC, joschiwald commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
> +        void DoSummonNextGrandChampion(bool skipEvent = false)
look what i've done in https://github.com/Aokromes/TrinityCore/commit/5696cef3f499dd3aceeecdeb5fc9741a06853676 it is a bit better

2015-06-30 11:56 UTC, Appled commented
@joschiwald Yeah that looks far more better and it's more cleaner. I'll change it. Btw, should I discontinue this as you guys are also working on this? Imo two reworks of same instance is pointless. Besides you guys are far more experienced in scripting that I am xd

@mik1893 Hey, I will get back on the weekend and I'll ping you in irc. Took this week off from work to build my summer cabin :-)

2015-07-03 12:14 UTC, PaulHellCore commented
UPDATE `gameobject_template` SET `flags`=0 WHERE `entry`IN(195323,195709,195374);

Loot for Confessor's Cache&Eadric's Cache

2015-07-03 12:25 UTC, Aokromes commented
Like i said on previous PR core must remove flags not db.

2015-07-09 00:46 UTC, Appled commented
@PaulHellCore The chests are not the problem here, but thanks anyway :-)

2015-07-10 16:49 UTC, Appled commented
Going to push seperate commits from now on, to see changes better. I will squash them together in the end. Also the initial commit should be reviewed as I have amended it dozen times atleast.

2015-07-12 19:57 UTC, Frytiks commented
Hard error xD

2015-07-12 21:40 UTC, Appled commented
I have it working on local but I'll push the fix when I have more content ready.

2015-07-26 07:00 UTC, Flameshot commented
Anything new?

2015-07-26 07:02 UTC, Appled commented
I haven't been able to made any recent progress aside from finishing champions encounter. My work schedule is very bad atm and I don't get much freetime. Hopefully I can continue this on upcoming week.

2015-08-19 12:33 UTC, Appled commented
Sorry for long delay between pushes. Been really busy irl.
But I managed to finish Grand Champions encounter, and from now on I think I can script the rest faster.

2015-08-23 22:51 UTC, Flameshot commented
"spell_toc5_trample_aura" defined in spell_generic and boss_grand_champions too.

2015-08-23 22:59 UTC, Appled commented
Thanks @Flameshot for noticing that, one of my previous commits got broken it reverted some file changes. Included them in the latest commit. Thanks again

2015-08-24 01:48 UTC, Flameshot commented
No problem :) @Appled

2015-08-29 12:04 UTC, digz6666 commented
When mounting on Argent Worg it immediately dismounts and dies after few seconds, so I cannot start the encounter. Anybody having same issue or am I doing something wrong?

2015-08-29 12:58 UTC, Flameshot commented
@digz6666 you must take a lance then you can mount an argent worg

2015-08-29 14:41 UTC, digz6666 commented
@Flameshot ah it works now, but for Allies the mount is not moving, for horde it's working.
![wowscrnshot_082915_233946](https://cloud.githubusercontent.com/assets/1736110/9562441/68f93cfc-4ea7-11e5-90fb-3c7c27f53a20.jpg)

2015-08-29 14:45 UTC, digz6666 commented
The problem with Alliance Argent Warhorse (template entry = 36557) has no script assigned to.
![wowscrnshot_082915_234502](https://cloud.githubusercontent.com/assets/1736110/9562480/1595b59e-4ea8-11e5-809a-aecfe278f7fd.jpg)

2015-08-29 15:30 UTC, Appled commented
Digz666 are you sure you applied the SQL too? I don't have any problems with that.

NOTE: As this script is still WIP you are at your own risk to apply the SQL. I can still edit SQL data for Grand Champions encounter for example if needed to and then if you have already applied the old SQL you can end up having bad data. I recommend to have clean TDB for this, and to remove your current database before final testing. In final testing all data you see 99,9% won't change anymore, so it is safe then to apply the SQL without the fear of deleting your database.

Also, I am currently scripting Eadric's combat AI. Paletress is fully done, thrash mobs in Argent Champion encounter are fully done and Eadric's other stuffs are fully done. You will see a commit most likely in a few next days.

2015-08-29 15:32 UTC, Appled commented
Also, if you don't have lance equiped and you try to mount a vehicle it just tosses you down. A good error message would work there but I didn't at that time find anything useful for it and which could be used from SmartAI/conditions. If you have a lance equipped you can control the mount then.

2015-08-29 15:46 UTC, Appled commented
And sorry for this spamming. But here I will show you something from current progression (just random screenshots xd).
First, we have a picture at the end of roleplaying event in Grand Champions encounter when battle is about to begin.
![wowscrnshot_111414_222711](https://cloud.githubusercontent.com/assets/346848/9562707/c2d8013e-4e7c-11e5-8424-0cfdf8c65661.jpg)

Next, I have a bad picture from fight on foot versus Grand Champions. Shaman is now "smart" and only 
occassionally heals party members (IF they aren't in full health) and uses combat abilities. And if anyone from the party goes on low health, he switches to "resto only" mod making him to spam healing spells on the most wounded party member. In this mode he does not use combat abilities anymore.
![wowscrnshot_081015_193224](https://cloud.githubusercontent.com/assets/346848/9562723/58db2a26-4e7d-11e5-86ab-8f3c87413149.jpg)

Next, I have a picture of beginning of Argent Champion encounter. 
![wowscrnshot_082915_184411](https://cloud.githubusercontent.com/assets/346848/9562742/05604966-4e7e-11e5-880b-e279e5f05100.jpg)

2015-08-29 15:54 UTC, digz6666 commented
@Appled can you run npc info command on Alliance Argent Warhorse and post screenshot?

2015-08-29 16:03 UTC, Appled commented
@digz6666 I checked npc flags and I have same data as you do. Did you apply the SQL which is in this PR?
https://github.com/TrinityCore/TrinityCore/pull/14938/files#diff-964b693544b8a194ee883f5a9008e63c

I don't have any problems with vehicles. I can't yet try with clean TDB but I may have inserted to database something what I don't have in the SQL.

2015-08-29 16:07 UTC, digz6666 commented
@Appled I tried on clean database, have you checked the script_name field?

2015-08-29 16:13 UTC, Appled commented
@digz6666 with completely clean database and without my SQL it will not work. As alliance vehicles were missing vehicle data which I fixed in https://github.com/TrinityCore/TrinityCore/pull/14938/files#diff-964b693544b8a194ee883f5a9008e63cR43

The player controlled vehicles will not have a scriptname at any point.
And also, like I said in previous comment there will be changes in SQL so I recommend to get a clean database when 'final phase' is here, and then import the SQL again there. After that there won't be any radical changes in SQL which would require you to get clean database when this goes live.

2015-08-29 16:15 UTC, digz6666 commented
@Appled I applied the SQL but it may not be the last version of yours, I will try again :)

2015-08-29 16:18 UTC, digz6666 commented
I checked it and I've applied the updated SQL before.

2015-08-29 16:40 UTC, digz6666 commented
I have a crash:
```
Revision: TrinityCore rev. d50c59d9ce5d+ 2015-08-29 14:41:29 +0900 (3.3.5 branch) (Win64, RelWithDebInfo)
Date 30:8:2015. Time 1:36 
//=====================================================
*** Hardware ***
Processor: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
Number Of Processors: 32
Physical Memory: 33507880 KB (Available: 17091356 KB)
Commit Charge Limit: 42913984 KB

*** Operation System ***
Windows Server 2012 Server 4.0 (Version 6.2, Build 9200)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  000007F743E59028 01:00000000001D8028 C:\running_cores\tc335_icarus\worldserver.exe

Registers:
RAX:0000005F0E548E80
RBX:0000005F0E548E80
RCX:0000005F0E548E80
RDX:0000000000000000
RSI:000000000000006E
RDI:0000005F0E560340
R8: 000007F745AE87A0
R9: 0000005E8962F101
R10:0000005EBC4EF618
R11:0000000000010AE1
R12:0000005EBC4EFC90
R13:0000005EA5691AD0
R14:0000000000000000
R15:0000000000000001
CS:RIP:0033:000007F743E59028
SS:RSP:002B:00000000BC4EF680  RBP:A5691A50
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010246

Call stack:
Address   Frame     Function      SourceFile
000007F743E59028  0000005EBC4EF6E0  WorldObject::IsInRange+18  c:\source\trinitycore_thorim\src\server\game\entities\object\object.cpp line 1310
000007F74489211B  0000005EBC4EF7C0  generic_vehicleAI_toc5::generic_vehicleAI_toc5AI::UpdateAI+10B  c:\source\trinitycore_thorim\src\server\scripts\northrend\crusaderscoliseum\trialofthechampion\boss_grand_champions.cpp line 1065
000007F744332086  0000005EBC4EF9C0  Creature::Update+9D6  c:\source\trinitycore_thorim\src\server\game\entities\creature\creature.cpp line 534
000007F7443A1EA9  0000005EBC4EFAD0  TempSummon::Update+39  c:\source\trinitycore_thorim\src\server\game\entities\creature\temporarysummon.cpp line 50
000007F7443A7E68  0000005EBC4EFB00  Trinity::ObjectUpdater::Visit<Creature>+38  c:\source\trinitycore_thorim\src\server\game\grids\notifiers\gridnotifiers.cpp line 345
000007F7442CD595  0000005EBC4EFB30  VisitorHelper<Trinity::ObjectUpdater,Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > >+15  c:\source\trinitycore_thorim\src\server\shared\dynamic\typecontainervisitor.h line 67
000007F7442CC9AD  0000005EBC4EFB80  Map::Visit<Trinity::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >+AD  c:\source\trinitycore_thorim\src\server\game\maps\map.h line 730
000007F7442E90C3  0000005EBC4EFC10  Map::VisitNearbyCellsOf+153  c:\source\trinitycore_thorim\src\server\game\maps\map.cpp line 639
000007F7442E88F9  0000005EBC4EFC80  Map::Update+159  c:\source\trinitycore_thorim\src\server\game\maps\map.cpp line 670
000007F7442E8774  0000005EBC4EFCB0  InstanceMap::Update+14  c:\source\trinitycore_thorim\src\server\game\maps\map.cpp line 3047
000007F7442F0DDB  0000005EBC4EFCE0  MapUpdater::WorkerThread+4B  c:\source\trinitycore_thorim\src\server\game\maps\mapupdater.cpp line 113
000007F7442F0E2D  0000005EBC4EFD10  std::_LaunchPad<std::_Bind<1,void,std::_Pmf_wrap<void (__cdecl MapUpdater::*)(void) __ptr64,void,MapUpdater>,MapUpdater * __ptr64> >::_Go+1D  c:\program files (x86)\microsoft visual studio 12.0\vc\include\thr\xthread line 188
000007FB0007D24C  0000005EBC4EFD50  ?_Release@_Pad@std@@QEAAXXZ+6C
000007FAFB174F7F  0000005EBC4EFD80  _beginthreadex+107
000007FAFB175126  0000005EBC4EFDB0  _endthreadex+192
000007FB09BE167E  0000005EBC4EFDE0  BaseThreadInitThunk+1A
000007FB0A25C3F1  0000005EBC4EFE30  RtlUserThreadStart+21
```

2015-08-29 17:02 UTC, Appled commented
Could you tell me what were you doing when it crashed? 
Are you sure also you have the latest version of this?
I have fixed one crash in local but I can't push it untill I have finished Eadric.

2015-08-30 04:45 UTC, digz6666 commented
@Appled I don't know, I just get it from crash logs few minutes later.
By the way I set ScriptName = generic_vehicleAI_toc5 for alliance mount and it moves.
```sql
UPDATE `creature_template` SET `ScriptName`='generic_vehicleAI_toc5' WHERE (`entry`='36557')
```

2015-08-30 05:55 UTC, digz6666 commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp
> +                case VEHICLE_ARGENT_WARHORSE_COSMETIC:
Shouldn't be case VEHICLE_ARGENT_WARHORSE_A:?

2015-08-30 05:56 UTC, digz6666 commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp
> +                        creature->UpdateEntry(VEHICLE_ARGENT_WARHORSE_A);
Shouldn't be creature->UpdateEntry(VEHICLE_ARGENT_WARHORSE_COSMETIC);?

2015-08-30 08:21 UTC, Appled commented
@digz6666 I think I have one crash solved in local. You mean the crash comes in combat or outside of combat? If it is in combat I had a bad check there which I corrected iirc.
But it's weird that I can move both alliance and horde vehicles without that scriptname.

2015-08-30 08:26 UTC, digz6666 commented
@Appled I added couple of comments to the code, maybe that's the issue? I haven't tested that, will update you when tested.

2015-08-30 08:37 UTC, Appled commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp
> +                case VEHICLE_ARGENT_WARHORSE_COSMETIC:
"The cosmetic" vehicles are what you see unfriendly vehicles. On alliance they are wolves and on horde they are horses. These are used by Grand Champions if they get fallen out of mount. After falling out they try to reach these mounts. Normally in the instance there are spawned only alliance vehicles (unfriendly wolf and friendly horse). So if you enter in horde, we change their templates to horde vehicles (unfriendly horse and friendly wolf). Therefore we don't have to loop through all vehicles, only alliance vehicles. In addition, no matter are you horde or alliance the vehicles are added into vehiclelist.

2015-08-30 08:37 UTC, Appled commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp
> +                        creature->UpdateEntry(VEHICLE_ARGENT_WARHORSE_A);
See above

2015-08-30 08:40 UTC, Appled commented
See, I don't have any scriptnames on alliance and I can mount the horse just fine.
![wowscrnshot_083015_113219](https://cloud.githubusercontent.com/assets/346848/9566351/cad6fa00-4f0a-11e5-81ce-5d2f750a617d.jpg)

I will push in next few days a next commit including whole Argent Champion encounter and some corrections in Grand Champions encounter. I really can't debug what's wrong with the horse untill I have Black Knight done. When it's done I can try things out with clean database.

Also, answered to your comments in code.

2015-09-01 02:08 UTC, digz6666 commented
@Appled I applied new commits and the alliance vehicle is still not moving, there's no skillbar. I copied updated cpp and header files to make sure nothing misses and re-applied the SQL.

2015-09-01 06:51 UTC, Appled commented
@digz6666 I may have forgot something from SQL file when I have created the SQL file. I am sorry but I cannot try yet with fresh TDB. I will first script Black Knight and then retry everything with clean database, and add most likely missing data. After that I leave further testing to you guys.

2015-09-06 13:05 UTC, Nevarian commented
Killing the Grand Champions makes their pets follow you for an eternity, causing me to be unable to complete the encounter: https://i.gyazo.com/f42a6c5422e619bf448da90fa8c8b80d.png

2015-09-06 15:57 UTC, Appled commented
Take note that if you are already testing this (which I don't recommend yet) don't use .die command at all. It will mess things up. Rather use .damage with a number being higher than mob's health. Using .die won't trigger certain events.

2015-09-06 16:31 UTC, Nevarian commented
Tested this a while ago, all in all looks okay for a WIP, but I had a crash with the waypoints and couldn't really get to the next boss.

2015-09-06 17:13 UTC, Appled commented
Do you remember at which stage you had a crash? Was it before encounter, during encounter or after encounter? And which encounter was it? A detailed answer, or even a crashlog, will help me to locate the problem and fix it.

2015-09-06 17:51 UTC, Krath commented
I think that he's talking about the crash that occurs when you kill one of these bosses : http://prntscr.com/8db6j4

It sometimes crash the server as soon as you kill one of those. Sadly, I don't have any crashlog to send you :(

2015-09-06 18:58 UTC, Appled commented
Do you have killed the bosses with .die command? If so, try with .damage.
Did the crash happen right after killing the boss? And it happens in mounted phase?
I don't get any crashes there, but I am running older TC (somewhere from June) on my computer. I will try later with the newest TC and clean TDB when I finish scripting The Black Knight.

2015-09-06 19:17 UTC, Krath commented
I have tried killing the boss with both damage command and normal way (fight using spells). I have also tried it with and without being mounted and it crashes . The crash occurs right after you kill one of those bosses.

2015-09-06 19:51 UTC, Appled commented
Alright, thanks for the report. I'll try to debug it as soon as I get Black Knight done.

2015-09-06 20:03 UTC, Krath commented
Alright, keep up the good work :). It's working well so far!

2015-09-10 09:23 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            if (id == 0)
switch and use enum for points

2015-09-10 09:23 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            if (bDone)
use
``cpp
if (!bDone)
Initialize();
``

2015-09-10 09:24 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            if (bDone)
the same here

2015-09-10 09:25 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            events.Reset();
again this line, not needed, use it only in Reset()

2015-09-10 09:30 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            if (!bMemory && !HealthAbovePct(25))
move it to DamageTaken

2015-09-10 09:31 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            events.Reset();
move this out

2015-09-10 09:32 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            {
remove brackets

2015-09-10 09:33 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            if (me->GetEntry() == NPC_ARGENT_LIGHWIELDER)
use switch instead

2015-09-10 09:34 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                return;
what

2015-09-10 09:34 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                events.Reset();
remove this

2015-09-10 09:35 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_black_knight.cpp
> +            events.Reset();
once more

2015-09-10 09:39 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
> +        if (action == GOSSIP_ACTION_INFO_DEF + 1)
you can use switch for these too

2015-09-10 09:40 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
> +            else if (uiPointId == 2)
switch

2015-09-10 09:42 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
> +#define GOSSIP_START_EVENT1     "I am ready."
can't be in database?

2015-09-15 09:01 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            faceRollerGUID.Clear();
do you really need to clear GUID in constructor?

2015-09-15 09:08 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                if (!bDone)
maybe you should use boss state instead of extra variable

2015-09-15 09:14 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            events.Reset();
useless

2015-09-15 09:15 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_black_knight.cpp
> +            events.Reset();
useless

2015-09-15 09:16 UTC, MitchesD commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_black_knight.cpp
> +            if (HealthBelowPct(31) && !doExplode)
use DamageTaken

2015-09-21 08:26 UTC, Flameshot commented
@Appled on alliance part when you mount the vehicle is not working.

2015-09-28 20:07 UTC, Appled commented
@Flameshot Yes, I am still aware of that. I have to wait for @joschiwald to take look at it.

2015-10-01 18:33 UTC, Laintime commented
@Appled no't work last rev.

2015-10-01 19:16 UTC, PaulHellCore commented
Can not start Event, does not meet announcer. Sorry my English.

2015-10-01 19:30 UTC, tkrokli commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
> +#define GOSSIP_START_EVENT1     "I am ready."
The text `'I am ready.'` exists in `broadcast_text`, but not in `npc_text` or `creature_text` yet.
```sql
SELECT * FROM `broadcast_text` WHERE `MaleText`= 'I am ready.' OR `FemaleText`= 'I am ready.';

2015-10-01 21:48 UTC, joschiwald commented
announcers does not work because of implementation of boss states

2015-10-03 18:53 UTC, PaulHellCore commented
Any news?

2015-10-17 23:04 UTC, PaulHellCore commented
There is a solution for running the event?

2015-10-18 18:31 UTC, joschiwald commented
pls check if the announcer works now

2015-10-19 18:25 UTC, PaulHellCore commented
announcer works, but now broken champions and not continue further.

2015-10-19 18:39 UTC, joschiwald commented
> but now broken champions and not continue further.

what do you mean?

2015-10-19 18:54 UTC, PaulHellCore commented
![GitHub Logo](http://s011.radikal.ru/i316/1510/2a/8be535ba9c67.jpg)
![GitHub Logo](http://s017.radikal.ru/i429/1510/7c/8725d2a59d89.jpg)
![GitHub Logo](http://s011.radikal.ru/i317/1510/38/58cf2abb18c1.jpg)

Wrong output winner, as loot appeared at the beginning of the battle , not after the victory. And just simply did not finish the fight.

2015-11-02 11:41 UTC, Keader commented
Need updates :)

2015-11-05 16:52 UTC, DevRival commented
Good work, but first the boss does not work.

2015-11-10 19:12 UTC, DevRival commented
Any news?

2015-11-10 19:25 UTC, Aokromes commented
No.

2015-12-12 11:37 UTC, bobkhan commented
Any news?

2016-01-05 17:33 UTC, jackpoz commented
What happened to this PR ?

2016-01-08 20:55 UTC, Appled commented
Afaik, https://github.com/Appled/TrinityCore/commit/86f7e46c2b825232a226b4732f7594a5dad02bf2 commit broke this PR, more precisely when I tried to update the instance script to new TC standards and change some ScriptedAIs to BossAIs. Before this commit the PR was working just fine excluding alliance vehicles and one spell casted by The Black Knight.
So options are either revert that commit partially and use "outdated" code, or rewrite whole PR. I don't have currently time for this as I am in military service for an year.

2016-01-08 21:11 UTC, joschiwald commented
problems are bossstate == not_started check, bossstates are initializied with to_b_decided

2016-01-08 21:13 UTC, joschiwald commented
@Appled which spell does not work in black knight encounter

2016-01-08 21:23 UTC, Appled commented
@joschiwald it was https://github.com/TrinityCore/TrinityCore/pull/14938/files#diff-0f46587bb19d921c285073f203ccb349R454 this spell. Some part in the spell didn't work. It should stun player target and then knock him/her back and inflict damage when the stun aura is removed. iirc it didn't knock player back, or it didn't deal damage when the stun aura was removed.

2016-01-08 22:23 UTC, jackpoz commented
@joschiwald since there are so many changes in this PR (and likely many improvements) could you check if that last commit could be reverted and what needs to be done to get it ready to merge ? I'd say it's ok to leave a couple of issues open, they can be fixed later (or after the military service ^^)

2016-01-08 22:36 UTC, joschiwald commented
pls try the encounter again

@jackpoz there is still some bad code that must be changed before merge

2016-01-26 12:07 UTC, saderka commented
change : instance_trial_of_the_champion.cpp

				case VEHICLE_ARGENT_WARHORSE_A:
					if (TeamInInstance == HORDE)
						creature->UpdateEntry(VEHICLE_ARGENT_WARHORSE_COSMETIC);
                    VehicleList.push_back(creature->GetGUID());
                    break;
                case VEHICLE_ARGENT_BATTLEWORG_H:
					if (TeamInInstance == ALLIANCE)
                        creature->UpdateEntry(VEHICLE_ARGENT_BATTLEWORG_COSMETIC);

Alliance mount update this.

UPDATE `world`.`creature` SET `id`=36557 WHERE  `id`=35644;

2016-02-05 11:55 UTC, DevRival commented
Any news?

2016-02-05 12:14 UTC, Aokromes commented
No.

2016-02-05 13:12 UTC, jackpoz commented
> Any news?

@DevRival did you merge locally this PR, test it and provide feedback ? Without these steps there cannot be any news

2016-02-05 14:33 UTC, DevRival commented
About of course, the problem consists in transition to a phase of champions. The first phase works incorrectly, when falling champions from horses they have to go to new horses, but thus they can be brought down, alas at us all of them equally continue to go. If you nevertheless managed to bring down all at the same time then there has to be a transition to a phase two. They simply remain with us on a place and on it everything, the second phase doesn't occur.

2016-02-05 14:52 UTC, Appled commented
Like I said before, Appled@86f7e46 commit broke this PR. Before that commit the issue you are talking about worked just fine.

2016-02-05 15:40 UTC, lashia commented
@Appled if i use with this commit 946a3b299ce36b4aeac1f9931842a1d4b076aecb it will work well?

2016-02-06 18:24 UTC, Appled commented
If you merge this pr and revert head to one commit before that commit it should work yes. Atleast iirc it did work then.

2016-02-07 03:14 UTC, lashia commented
okay i will test it today...

2016-02-16 07:15 UTC, lashia commented
![capture](https://cloud.githubusercontent.com/assets/8265622/13069503/ff79b932-d439-11e5-8471-e19bd929cf02.PNG)

2016-02-16 10:49 UTC, Laintime commented
@lashia remove override :DDDDDDD

2016-02-16 11:09 UTC, Shauren commented
dont suggest such things!, override is there to ensure the method has correct name, return type and parameters (and they dont here anymore - EnterEvadeMode now has additional arg)

2016-02-16 12:15 UTC, lashia commented
@Shauren what additional arg it is

2016-02-16 13:19 UTC, jackpoz commented
just for reference travis uses a compiler smart enough to find the virtual member function and tell the user about it https://travis-ci.org/TrinityCore/TrinityCore/builds/101176668#L1508

2016-02-16 13:33 UTC, Nyeriah commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                    ENSURE_AI(boss_eadric::boss_eadricAI, GetHitUnit()->ToCreature()->AI())->SetFacerollerPlayer(GetCaster()->GetGUID());
Why not SetGuid()?

2016-02-16 16:16 UTC, tkrokli commented
@lashia : I don't know exactly how to apply it, but the new form of `EnterEvadeMode` looks like this:
```cpp
void EnterEvadeMode(EvadeReason why) override { }
```
As an example of how it can be used, I found this sample piece of code:
```cpp
        void EnterEvadeMode(EvadeReason why) override
        {
            if (!_EnterEvadeMode(why))
                return;

            Reset();
        }
```
It can also be used in this form if needed:
```cpp
void EnterEvadeMode(EvadeReason /*why*/) override { }
```
Sorry that I don't know the exact way of applying it in this specific PR. Maybe a dev can suggest how.

2016-02-16 22:36 UTC, tkrokli commented on sql/updates/world/2015_10_01_14938_world.sql
> +DELETE FROM `achievement_criteria_data` WHERE `type` IN (11, 18) `criteria_id`=11789;
Missing `AND` in this line seems to be the only thing Travis complains about currently. Should be:
```sql
DELETE FROM `achievement_criteria_data` WHERE `type` IN (11, 18) AND `criteria_id`=11789;
```

2016-02-16 22:44 UTC, Treeston commented
The param to `EnterEvadeMode` tells you [the reason the creature is entering evade mode](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/CreatureAI.h#L85-L91).

The param can be safely disregarded if you don't actually need it for anything.

2016-02-16 22:48 UTC, Treeston commented on sql/updates/world/2015_10_01_14938_world.sql
> +-- creatures are spawned according to sniffs behind an invisible wall and they don't know how to go through it
Use `AddUnitState(UNIT_STATE_IGNORE_PATHFINDING)` in the unit AI when it's needed, then remove it when it's no longer needed. No need to disable mmaps for the entire dungeon.

2016-02-17 21:45 UTC, Treeston commented
Attempting to mount a warhorse while not having a lance equipped doesn't throw an error, but attempts to mount then lands the player butt first on the ground (this animation is hilarious, fwiw).

2016-02-17 22:06 UTC, Treeston commented
Horde side works well. I suspect that vehicle data is not properly adjusted when updating entry.

2016-02-17 22:15 UTC, Treeston commented
AI is not adjusted when updating entry either (it is determined when the instance initializes).

2016-02-19 01:29 UTC, Treeston commented
Ran the latest version of this PR with an alliance group today (hackfixed `creature` to spawn the correct mounts). Tons of issues. Updating this as we get further into this mess.

- Grand champions and their pets in mounted phase can (and do) immediately attack while being immune to counterattack themselves.
- During the second phase, the grand champions can be pulled independently, and don't all engage at once.
- Eressea Dawnsinger stays at about 40yd from the tank at all times and refuses to come to melee range at all.
- Eadric the Pure's trash isn't properly linked and multiple mobs in a pack can be engaged separately.
- Eadric the Pure trash home positions (the positions they reset to after a wipe) are incorrect.

2016-02-19 01:43 UTC, Treeston commented
As a side note, a lot of the above may have to do with setting react state in AI constructor. This is a bad thing. Use Reset().

2016-02-20 02:22 UTC, Treeston commented
Any of the above that can be attributed to creatures ignoring `REACT_PASSIVE` can probably be chalked up to the bug fixed in ab194d5 and d418406. I'll try to test this after those commits at the nearest opportunity and report back.

Any issues not relating to these bugs are still relevant, though.

2016-03-06 13:57 UTC, wowdarklym commented
make error .why?
/home/TrinityCore/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_black_knight.cpp:283:14: error：‘void boss_black_knight::boss_black_knightAI::EnterEvadeMode()’ marked override, but does not override
         void EnterEvadeMode() override

2016-03-06 14:32 UTC, lashia commented
@wowdarklym  check @tkrokli  comment about EvadeReason

2016-03-06 14:39 UTC, wowdarklym commented
I use git to pull
Merge branch '3.3.5' of https://github.com/Appled/TrinityCore into 3.3.5
And then the compiler went wrong.

2016-03-06 15:52 UTC, tkrokli commented
Yes, that is because https://github.com/Appled/TrinityCore/tree/3.3.5/ has not been updated since January 8, 2016. If you try to merge Appled's 3.3.5 branch into your own branch, you **will get merge issues** because your own 3.3.5 branch is almost up to date with TrinityCore/TrinityCore/tree/3.3.5. If you want to try Appled's source, you must clone his source to a separate folder on your computer.

2016-03-06 16:30 UTC, Treeston commented
[This patch](https://gist.github.com/Treeston/2f3c01072e9b337f3ac5) makes it compile with latest 3.3.5. Currently the PR will only work for either alliance or horde at any given time due to how it is set up. The patch linked makes it work for alliance but breaks it for horde.

To make it work for horde (and break it for alliance), change the last two lines of the sql update file to
```sql
UPDATE `creature` SET `id`=@ARGENT_WARHORSE_GC where `id`=@ARGENT_WARHORSE_A;
UPDATE `creature` SET `id`=@ARGENT_BATTLEWORG_H where `id`=@ARGENT_BATTLEWORG_GC;
```

2016-03-06 16:47 UTC, wowdarklym commented
Look forward to complete the repair

2016-03-12 23:45 UTC, Treeston commented
Alright, another run report from me, this time on heroic.
* Mounting a horse without lance doesn't throw any error, but just kicks you off right away. Unintuitive and broken.
* Horses don't recognize the "Alliance Lance" from outside the instance. Not sure if that is intended.
* You can't trample dismounted Faction Champions during phase one.
* Faction Champions desync when re-mounting, causing the client to show them at the wrong position (they are on their mount server-side, but dismounted client-side).

2016-03-13 00:29 UTC, Treeston commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                        for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
Hack. Use threat list.

2016-03-13 00:30 UTC, joschiwald commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                        for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
there are more hacks than this one ^^

2016-03-13 00:54 UTC, Treeston commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                        for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
Yeah, but it's the one I used.

2016-03-13 00:55 UTC, Treeston commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                            DoCastVictim(SPELL_SHADOW_WORD_PAIN_H);
[`spelldifficulty_dbc`](http://collab.kpsn.org/display/tc/spelldifficulty_dbc)

2016-03-13 00:56 UTC, Treeston commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +            if (!(me->GetEntry() == NPC_ARGENT_MONK && me->HasAura(SPELL_DIVINE_SHIELD)))
Check for `shielded` instead. Buff may not appear until next tick.

2016-03-13 00:57 UTC, Treeston commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                            DoCast(me, SPELL_FOUNTAIN_DUMMY_HEAL);
Why not `creature_template_addon` aura?

2016-03-23 00:21 UTC, Appled commented
I can take a look at this and try to revert, fix and clean this on this week. I have some freetime.

2016-03-23 00:33 UTC, Treeston commented
Check https://github.com/TrinityCore/TrinityCore/pull/14938#issuecomment-192927572 for a patch that makes it compile with latest `EnterEvadeMode` signature changes.

2016-03-23 01:19 UTC, tkrokli commented
Please also note the SQL typo in Line 446 (see https://github.com/TrinityCore/TrinityCore/pull/14938#discussion-diff-53091479).

2016-03-23 01:21 UTC, Treeston commented
It's part of the patch file ;)

@Appled thanks a lot for continuing work on this, keep it up :+1:

2016-03-23 01:24 UTC, tkrokli commented
@Treeston : Oh. I see. I did not notice the link, I thought it only referred to the visible SQL code block.

2016-03-23 13:45 UTC, danqu commented
@tkrokli      I test to find a problem, the horse can not be used properly

2016-03-23 15:29 UTC, danqu commented
![image](https://cloud.githubusercontent.com/assets/3050620/13990253/952cbc46-f14e-11e5-9347-fd2106dd075a.png)
1.Error message
2.Each repeated story, only to the second stage

2016-03-23 15:46 UTC, tkrokli commented
OK, it is good of you to test the PR content, but did you test Appled's branch alone, or this PR merged with your existing 3.3.5 branch? If I had time, I would have tested https://github.com/Appled/TrinityCore/tree/3.3.5/ on its own, just to be sure that only the PR causes that kind of issue.

2016-03-24 13:14 UTC, danqu commented
@joschiwald @tkrokli   When killing second BOSS, unable to continue, can solve this problem?

2016-03-24 16:42 UTC, tkrokli commented
If your previous problems are solved now, you just need to wait until more progess is done in this PR.

2016-04-15 02:35 UTC, ryoting commented
Any news?

2016-04-15 09:21 UTC, Aokromes commented
Yes, you can test it.

2016-04-16 00:20 UTC, ryoting commented
yes,i first test [WIP] Scripts/TrialOfTheChampion: Full rework #14893 ,then test #14938.
i dont know which method i will test? 14893 or 14938?
thanks

2016-04-16 00:40 UTC, tkrokli commented
@ryoting : if you read the last comment in 14893, https://github.com/TrinityCore/TrinityCore/pull/14893#issuecomment-140327425, you will see that it was closed with a link to this one (#14938). Test this current and open PR, because the other one is closed (don't use).

2016-04-16 00:58 UTC, ryoting commented
@tkrokli thank you very much.

2016-04-16 02:02 UTC, ryoting commented
`		for (std::set<uint32>::iterator itr = avalibleElixirs.begin(); itr != avalibleElixirs.end();)
		{
			SpellInfo const* spellInfo = sSpellMgr->EnsureSpellInfo(*itr);
			if (spellInfo->SpellLevel < m_spellInfo->SpellLevel || spellInfo->SpellLevel > unitTarget->getLevel())
				avalibleElixirs.erase(itr++);
			else if (sSpellMgr->IsSpellMemberOfSpellGroup(*itr, SPELL_GROUP_ELIXIR_SHATTRATH))
				avalibleElixirs.erase(itr++);`

what is "EnsureSpellInfo"?
error	1	error C2039: “EnsureSpellInfo”: no“SpellMgr” member
\TrinityCore\src\server\game\Spells\SpellEffects.cpp	1833	1	game

2016-04-20 07:35 UTC, ryoting commented
@joschiwald @tkrokli When killing second BOSS, unable to continue, can solve this problem?

this problem is exist still,when kill the man or woman,he or she do not Exit Site,and will fresh a new man or woman,killed again,then can`t continue next boss.

controllpanel tips:
![952cbc46-f14e-11e5-9347-fd2106dd075a](https://cloud.githubusercontent.com/assets/12771834/14666639/610ae49a-070d-11e6-8e7f-ac87c60ba65b.png)

2016-04-20 13:14 UTC, tkrokli commented
@ryoting : Sorry, I don't have any personal experience from the way the code looks in this PR at the moment, so I don't know the answer to your question. But thanks for your feedback and problem info.

2016-04-22 18:15 UTC, Keader commented
>Bradley@BRADLEY /e/TrinityCore (toc5man)
$ git apply toc5man.txt
toc5man.txt:229: trailing whitespace.
-- for achievement IDs 3778, 4018, 4019, 4048, 4049, 4050, 4051, 4052, 4053, 4054, 4055, 4296, 4297, 4298,
toc5man.txt:409: trailing whitespace.
INSERT INTO `spell_proc_event` (`entry`,`procFlags`,`procEx`,`CustomChance`,`Cooldown`) VALUES
toc5man.txt:458: trailing whitespace.
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
toc5man.txt:1022: trailing whitespace.

toc5man.txt:1209: trailing whitespace.
                        break;
warning: squelched 11 whitespace errors
warning: 16 lines add whitespace errors.

2016-04-22 18:20 UTC, Keader commented on sql/updates/world/2015_10_01_14938_world.sql
> +-- for achievement IDs 3778, 4018, 4019, 4048, 4049, 4050, 4051, 4052, 4053, 4054, 4055, 4296, 4297, 4298,
white space

2016-04-22 18:21 UTC, Keader commented on sql/updates/world/2015_10_01_14938_world.sql
> +INSERT INTO `spell_proc_event` (`entry`,`procFlags`,`procEx`,`CustomChance`,`Cooldown`) VALUES
white space

2016-04-22 18:21 UTC, Keader commented on sql/updates/world/2015_10_01_14938_world.sql
> +INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `Condi
white space

2016-04-22 18:22 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +
white space

2016-04-22 18:23 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                        break;
white space

2016-04-22 19:19 UTC, Keader commented
Testing with rev 02d7df6aa4352d7112073898826ef195bedb6cff
In normal and heroic, if i try mount on Argent Battleworg, he kick me out.

2016-04-23 03:19 UTC, ryoting commented
@Keader yes,the  2º Boss bug,you know how to solve it?

2016-04-23 09:21 UTC, Appled commented
Like I have said, this PR worked just fine before I updated InstanceScript to this "modern version". That broke whole PR. Almost whole PR needs to be rewritten. My plan was to revert that specific commit partly, idea was to remove all changes from InstanceScript and use the old version. But ofc thats not cool.

2016-04-23 10:46 UTC, Keader commented
ok, i'll waiting your changes before test again ^^

2016-04-29 17:35 UTC, ConradBunton commented
Columns doesn't match, today. That patch is useless, today.

2016-04-29 18:03 UTC, Aokromes commented
189 queries executed, 189 success, 0 errors, 0 warnings

2016-04-29 20:06 UTC, ConradBunton commented
???
There's only one link SQL : http://pastebin.com/Cv8Savav and the columns `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6` doesn't exist on the latest DB.

2016-04-29 20:41 UTC, Aokromes commented
IDK what sql are you trying to use, but on latest version we don't use delete+insert creature_template.

2016-04-29 21:25 UTC, ConradBunton commented
Latest version ? Where ?

2016-04-29 21:34 UTC, Aokromes commented
The one on the pull request, no some random sql found who knows where.

2016-05-02 07:02 UTC, ConradBunton commented
So if we don't touch the sql, i've one the latest basic core (March 2016).
Where's the diff files to merge that ?

2016-05-02 08:20 UTC, Nawuko commented
![facepalm](http://memesvault.com/wp-content/uploads/Facepalm-Meme-Picard-14.jpg)

Click on "File changes" to see the file changes (duh)
https://github.com/TrinityCore/TrinityCore/pull/14938/files

You can clone this PR or use the genrated diff file from github:
https://patch-diff.githubusercontent.com/raw/TrinityCore/TrinityCore/pull/14938.diff

2016-05-02 11:13 UTC, ConradBunton commented
Et si je me mets à te parler comme ça ? Ca te paraitrait plus clair ?
Donc si je commence à taper dans les abrév., on va voir si tu t'en sors.
Conclusion, ce qui te parait être une évidence ne l'est pas forcément pour tous, surtout dans une autre langue. Penses-y, la prochaine fois.

2016-05-02 11:16 UTC, Nawuko commented
Way to go champ. Be rude to ppl that want to help. Real hero :+1:

2016-05-02 11:29 UTC, ConradBunton commented
So, as I said, it can't be applied on the last core.

$ git apply 14938.diff

And...

14938.diff:229 trailing whitespace.
== for achievement IDs 3778, 4018, 4019, 4048, 4049, 4050, 4051, 4052, 4053, 4054, 4055, 4296, 4297, 4298,
14938.diff:409: trailing whitespace.
INSERT INTO 'spell_proc_event' ('entry','procFlags','procEx','CustomChance','Cooldown') VALUES
14938.diff:458: trailing whitespace.
INSERT INTO 'conditions' ('SourceTypeOrReferenceID', 'SourceGroup', 'SourceEntry', 'SourceId', 'ElseGrou', 'ConditionTypeOrReference', 'ConditionTarget', 'ConditionValue1', 'ConditionValue2', 'ConditionValue3', 'NegativeCondition', 'ErrorType', 'ErrorTextId', 'ScriptName', 'Comment') VALUES
14938.diff:1022: trailing whitespace.

14938.diff:1209: trailing whitespace.
                                   break;
warning: squelched 11 whitespace errors
warning: 16 lines add whitespace errors.

2016-05-02 12:30 UTC, Keader commented
Warning != Error...
If only has warning, patch is appled :)

2016-05-02 12:34 UTC, ConradBunton commented
Ok, scripts work better, but mount are unusable, probably an error in DB.

2016-05-02 14:43 UTC, dobrMAN commented
[look at this comment to fix db](https://github.com/TrinityCore/TrinityCore/pull/14938#issuecomment-213559759)

2016-05-02 16:50 UTC, ConradBunton commented
Ok in the hord side, but mount bug in alliance

2016-05-03 03:25 UTC, ryoting commented
the biggest issue of this script was killed the No.2 boss,it can`t leave site,and refresh another No.2 boss,killed it again,then can`t continue.

2016-05-05 08:33 UTC, ConradBunton commented
Fix DB doesn't change anything. Only hord mount work.
Alliance mount is takable, but no spell appear and cant move.

2016-05-05 08:35 UTC, Treeston commented
Run this on your DB to make it work for alliance (note: breaks it for horde though)

```sql
+UPDATE `creature` SET `id`=@ARGENT_WARHORSE_A where `id`=@ARGENT_WARHORSE_GC;
+UPDATE `creature` SET `id`=@ARGENT_BATTLEWORG_GC where `id`=@ARGENT_BATTLEWORG_H;
```

2016-05-05 08:49 UTC, ConradBunton commented
Better if its work in the both side.

2016-05-05 09:53 UTC, Treeston commented
Obviously. This is purely hotfixing the issue so you can test the rest of the dungeon using alliance toons.

2016-05-05 10:05 UTC, ConradBunton commented
All the dungeon work fine, exept alliance mount and sometimes the 2nd boss.

2016-05-08 17:21 UTC, joschiwald commented
check mounts again

2016-05-09 10:04 UTC, ConradBunton commented
Testing... 100% ok, thanks

2016-05-10 00:22 UTC, ryoting commented
@ConradBunton 100%?The No.2 Boss no problem?

2016-05-10 05:42 UTC, ConradBunton commented
Completely tested 5 times and no problem for me. May be one of the modifications that I made myself.

2016-05-10 07:40 UTC, Appled commented
Good job @joschiwald

2016-05-10 08:35 UTC, Appled commented
Incase the second boss isnt working for some people, @ConradBunton you mind sharing your tweaks with us so this can be completed?

2016-05-11 13:55 UTC, lellonicole commented
sorry, instance don't pass second boss, he spawn a loop :/ any ideas to fix it?

2016-05-11 14:38 UTC, dobrMAN commented
I test PR in normal mode on Horde side. Dont have any issues with 2nd boss... All work good. (Clear TC last rev. and diff from this PR)

2016-05-11 15:23 UTC, lellonicole commented
the second boss we bug if killed too fast (10 sec).
In heroic mode is always bug!
tested with a horde pg gm.. it's only bug on 2nd boss..
sorry for my bad english

2016-05-11 16:03 UTC, Appled commented
@lellonicole Are you talking about Argent Confessor Paletress or Eadric the Pure?

2016-05-11 16:38 UTC, lellonicole commented
yes @Appled

2016-05-11 22:19 UTC, Appled commented
Do you use GM commands such as .die or casting spell id 5?
They will break the encounter.

2016-05-12 05:31 UTC, ryoting commented
@Appled not GM,it`s test it with player account.the No.2 boss break sometimes.not always.

2016-06-04 09:08 UTC, ConradBunton commented
Sorry too much tweak, i cant find it.

However, since May 28th, all compil show 3 errors messages
error C2065: 'UNIT_FLAG_DISABLE_MOVE' 
boss_argent_challenge.ccp : line 973
boss_black_knight.ccp : line 324
boss_black_knight.ccp : line 689

And the achivments doesnt work, now

2016-06-04 09:36 UTC, Treeston commented
Replace all occurremces of `UNIT_FLAG_DISABLE_MOVE` with `UNIT_FLAG_REMOVE_CLIENT_CONTROL`. It's just a rename.

2016-06-09 01:29 UTC, Keader commented
@Appled new about it?

2016-06-09 18:35 UTC, Keader commented
I found one problem with Eadric the Pure.
Instance state is != Special when he is defeated.
After "kill" him, using .i get 1, result is : Boss id 1 state is 0 (NOT_STARTED).
They need be in special state to call EVENT_EADRIC_DONE...

2016-06-09 19:18 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                        me->DeleteThreatList();
@Appled @joschiwald this line is the cause of secound boss dont work.
When event EVENT_EADRIC_DONE is called, DeleteThreatList make creature enter in evade, and all script stuck in secound boss.
Just removind this line, instance works well (dont tested achievs)
And need update ```UNIT_FLAG_REMOVE_CLIENT_CONTROL``` flags

2016-06-09 19:49 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                        me->DeleteThreatList();
https://github.com/TrinityCore/TrinityCore/pull/14938#discussion_r66504510

2016-06-10 12:38 UTC, Keader commented
@cshaaa look: https://github.com/TrinityCore/TrinityCore/pull/14938#issuecomment-223745459 and https://github.com/TrinityCore/TrinityCore/pull/14938#issuecomment-223746534 and https://github.com/TrinityCore/TrinityCore/pull/14938#issuecomment-224778815 and https://github.com/TrinityCore/TrinityCore/pull/14938#discussion_r66504510 xD

2016-06-10 12:52 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                            DoCast(me, SPELL_VENGEANCE);
You can change to "DoCastSelf"

2016-06-10 12:55 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                me->RemoveAura(SPELL_SHIELD);
RemoveAuraDueToSpell

2016-06-10 12:56 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                DoCastAOE(SPELL_HOLY_NOVA, false);
false is default value, you dont need put him

2016-06-10 13:19 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_black_knight.cpp
> +        bool doExplode;
All variables rly need be "public"?
normally is used private for this cases

2016-06-10 13:30 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +        for (int i = 0; i < 3; i++)
uint8 please.

2016-06-10 13:30 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +        for (int i = 0; i < 3; i++)
uint8 please.

2016-06-10 13:30 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +                for (int i = 0; i < 3; i++)
uint8 please.

2016-06-10 13:30 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +        for (int i = 0; i < 3; ++i)
uint8

2016-06-10 13:37 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp
> +                me->RemoveAura(SPELL_BLADESTORM);
RemoveAuraDueToSpell

2016-06-10 13:49 UTC, cshaaa commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                DoCastAOE(SPELL_HOLY_NOVA, false);
mean i should delete this line "DoCastAOE(SPELL_HOLY_NOVA, false);"
@Keader thanks for your guid

2016-06-10 13:49 UTC, cshaaa commented
thanks very much！you'r so kind for so much detail guides!

2016-06-10 13:51 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp
> +                DoCastAOE(SPELL_HOLY_NOVA, false);
No, you can replace with: ```oCastAOE(SPELL_HOLY_NOVA);```, same result

2016-06-10 14:17 UTC, cshaaa commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_black_knight.cpp
> +        bool doExplode;
then how to change about this,  please?aha

2016-06-10 14:23 UTC, Keader commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_black_knight.cpp
> +        bool doExplode;
e.g.:
```cpp
private: 
    bool doExplode;
```

2016-06-10 14:56 UTC, cshaaa commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_black_knight.cpp
> +        bool doExplode;
thank you @Keader

2016-06-14 14:00 UTC, Keader commented
Achiev Faceroller should be a Group Achiev, not Player Achiev
http://www.wowhead.com/achievement=3803/the-faceroller#comments:id=803927

2016-06-14 22:37 UTC, Keader commented
Looking For Group system dont finish when Black Knight is killed
maybe need be hardcoded like: https://github.com/TrinityCore/TrinityCore/blob/d1aa171a7ad89db6283ddd93c29c346dc8373eae/src/server/scripts/Outland/CoilfangReservoir/TheSlavePens/boss_ahune.cpp#L205-L211

2016-06-15 01:22 UTC, ccrs commented
thats a hack, check dbcs to know the required spells for LFG

2016-06-15 04:41 UTC, Aokromes commented
@Appled 
This branch has conflicts that must be resolved
 Use the command line to resolve conflicts before continuing.

2016-06-15 06:51 UTC, Appled commented
Hey,
Like I said before I am serving in military still the next 7 months. I dont have access to a computer for while so I gotta call @joschiwald here.

2016-06-15 06:59 UTC, Aokromes commented
1st notice i see about that :P

2016-06-15 07:03 UTC, Appled commented
It's hard to spot but there it is ;-)
https://github.com/TrinityCore/TrinityCore/pull/14938#issuecomment-170121551

2016-06-15 09:15 UTC, atheosTG commented
Is there any need for more manpower here?
I'm horrible at using github so I don't really get what's left to fix.

2016-06-15 12:13 UTC, Keader commented
@ccrs how?

2016-06-16 00:29 UTC, ccrs commented
check dbcs with a viewer -> find the criterias for lfg -> cast spells on encounter done

2016-06-16 08:06 UTC, atheosTG commented
@ccrs Which DBC am I supposed to look through? LFGDungeons.dbc does not seem to contain LFG criteria so i'm at a dead end

2016-06-25 13:07 UTC, BungiSk commented
Hello, not working first bosses spells. Only attacked me weapons :( :D
Here is video, please help me.
https://vid.me/ZR6w

2016-07-15 15:08 UTC, sirikfoll commented
If a player log out while mounted, then log back, he will appear unmounted, but the vehicle aura 67830 [Ride Vehicle] will remain on him, result: player is invulnerable to all attacks(everywhere, not just inside the instance)

2016-08-15 18:27 UTC, Treeston commented
QC run on this just now - alliance side. Bugs below:

- No error message when trying to mount a warhorse without a lance equipped. The mount just fails.
- During the mounted combat phase, enemy grand champions cannot be trampled. This makes the fight extremely difficult to finish, as they keep re-mounting.
- During Palatress trash, the herald (Arelas Brightstar) faces the wall.
- The "Fountain of Light" is capable of moving during Palatress trash.
- "Argent Monk" doesn't die on its own after "Final Meditation" finishes channeling. Anecdotally, I think it should die on its own.
- Palatress remains in her attack stance animation even after combat ends and she moves to the center.
- Palatress never leaves the arena when starting the black knight event
- Pets keep attacking the Black Knight during Feign Death and prevent the event from proceeding.

2016-08-15 19:02 UTC, Treeston commented
Additional bugs we found during our run of heroic difficulty:

- During the second part of faction champions, you can pull the three bosses separately from each other.
- Palatress' summoned memories will never despawn even if the group wipes.
- Palatress doesn't properly remove Reflective Shield when the summoned memory dies.

2016-08-25 07:42 UTC, Aokromes commented
This branch has conflicts that must be resolved
 Use the command line to resolve conflicts before continuing.

2016-10-05 14:52 UTC, sucklifex commented
this one was great :(

2016-10-23 17:08 UTC, Keader commented
Sometimes this happens:

![4ade14891c4114bf0386769558c262d4d9b0df463c1b16bbbc pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/7120913/19627976/79860420-9932-11e6-9a26-fcf0ab8a6067.png)

This need a secound re-write haha

2016-11-09 14:38 UTC, Keader commented
I did boundary for trial of champions...
https://github.com/Keader/TrinityCore/commit/9d9c600dd069592f6906bcfa87e8398445d8f23c
when someone takeover or re-write this pr, can be used.
Has a issue that ```instance_trial_of_the_crusader.cpp``` should be the cause...
if i try use: .debug boundary in some boss, shows: VisualizeBoundary error: Creature movement is unbounded
and .instance get/setbossstate 1/2/3 dont work :)
Useful data:
> Keader wtf?
> Keader someone know why .instance get/setbossstate dont work in trial of the champions?
> Keader .i get 0, work
> Keader .i get 1 = Incorrect values.
> Keader 1 should be BOSS_ARGENT_CHALLENGE_E
> <Krudor> Keader: trial of the champion does not override GetBossState/SetBossState
> Krudor So you shouldn't get any useful data from the default implementation
> Keader hmm
> ariel- that's not true
> Krudor It uses SetData instead for some reason
> ariel- that a instance decides to override GetBossState/SetBossState with command giving info
> ariel- override is only used to some extra functions (like on Ulduar for example for spawning cache with loot)
> ariel- to have meaningful results with the command, the instance must perform a SetBossNumber call on construct
> ariel- and bosses inside instance should use BossAI
> Krudor I think you missunderstand me, they use SetData instead of Get/SetBossState, so there's no wonder he doesn't get useful data
> Krudor The script most likely call Get/SetData instead of use Get/SetBossState

2016-11-15 13:31 UTC, Bodeguero commented
**Any News?**

2016-11-15 22:35 UTC, Mrgrasser commented
now player in Boss_Crand_Champions if out  or logout  was enemy and after can go or other instaces tank and just give aggro and othre characters kill any bosses in the patch, this problem is very fun . just true test can see ;D

2016-11-16 13:42 UTC, ceresia commented
> now player in Boss_Grand_Champions if out or logout ( or where work for wipe ) was enemy and after can go or other instaces tank and just give aggro and othre characters kill any bosses in the patch, this problem is very fun . just true test can see ;D

What...?

2016-11-25 22:45 UTC, Mrgrasser requested changes

2016-11-25 22:45 UTC, Mrgrasser commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.h
> +enum WaypointData
after commit 28050f338dfc66e0c40b6a3915bf96e38e0613e5 break WaypointData  !!!

2016-12-13 06:51 UTC, ConradBunton commented
Conflict with new WP manager

2016-12-14 22:51 UTC, ConradBunton commented
Since ariel's commit "Core/Spell: improved immunity logic for dispels", 3 days ago, I have that error :
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(369): error C2660: 'Creature::IsImmunedToSpell': function does not take 1 arguments

In the script :

    void SpellHit(Unit* /*caster*/, SpellInfo const* spell) override
    {
        if (spell->Id == SPELL_TRAMPLE_AURA && LookingForMount && uiPhase == 0 && !me->IsImmunedToSpell(spell))

spell seems dont wanna stay alone...

2016-12-15 19:10 UTC, ConradBunton commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.h
> +enum WaypointData
That commit make errors for me :

\src\server\scripts\northrend\crusaderscoliseum\trialofthechampion\trial_of_the_champion.h(224): error C2011: 'WaypointData': 'struct' type redefinition (compiling source file \src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_argent_challenge.cpp)
\src\server\game\Movement\Waypoints\WaypointManager.h(35): note: see declaration of 'WaypointData' (compiling source file \src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_argent_challenge.cpp)
\src\server\scripts\northrend\crusaderscoliseum\trialofthechampion\trial_of_the_champion.h(224): error C2011: 'WaypointData': 'struct' type redefinition (compiling source file \src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_black_knight.cpp)
\src\server\game\Movement\Waypoints\WaypointManager.h(35): note: see declaration of 'WaypointData' (compiling source file \src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_black_knight.cpp)
\src\server\scripts\northrend\crusaderscoliseum\trialofthechampion\trial_of_the_champion.h(224): error C2011: 'WaypointData': 'struct' type redefinition (compiling source file src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\instance_trial_of_the_champion.cpp)
\src\server\game\Movement\Waypoints\WaypointManager.h(35): note: see declaration of 'WaypointData' (compiling source file \src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\instance_trial_of_the_champion.cpp)
\src\server\scripts\northrend\crusaderscoliseum\trialofthechampion\trial_of_the_champion.h(224): error C2011: 'WaypointData': 'struct' type redefinition (compiling source file \src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp)
\src\server\game\Movement\Waypoints\WaypointManager.h(35): note: see declaration of 'WaypointData' (compiling source file \src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp)
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(760): error C2065: 'DATA_GENERATE_WAYPOINTS_FOR_BOSS_1': undeclared identifier
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(760): error C2131: expression did not evaluate to a constant
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(760): note: failure was caused by non-constant arguments or reference to a non-constant symbol
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(760): note: see usage of 'DATA_GENERATE_WAYPOINTS_FOR_BOSS_1'
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(777): error C2065: 'DATA_GENERATE_WAYPOINTS_FOR_BOSS_2': undeclared identifier
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(777): error C2131: expression did not evaluate to a constant
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(777): note: failure was caused by non-constant arguments or reference to a non-constant symbol
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(777): note: see usage of 'DATA_GENERATE_WAYPOINTS_FOR_BOSS_2'
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(792): error C2065: 'DATA_GENERATE_WAYPOINTS_FOR_BOSS_3': undeclared identifier
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(792): error C2131: expression did not evaluate to a constant
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(792): note: failure was caused by non-constant arguments or reference to a non-constant symbol
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(792): note: see usage of 'DATA_GENERATE_WAYPOINTS_FOR_BOSS_3'
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(807): error C2065: 'DATA_GENERATE_WAYPOINTS_FOR_ADDS': undeclared identifier
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(807): error C2131: expression did not evaluate to a constant
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(807): note: failure was caused by non-constant arguments or reference to a non-constant symbol
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(807): note: see usage of 'DATA_GENERATE_WAYPOINTS_FOR_ADDS'
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(814): error C2065: 'DATA_GENERATE_WAYPOINTS_FOR_BOSS_3': undeclared identifier
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(760): error C2051: case expression not constant
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(777): error C2051: case expression not constant
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(792): error C2051: case expression not constant
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(807): error C2051: case expression not constant
\src\server\scripts\Northrend\CrusadersColiseum\TrialOfTheChampion\boss_grand_champions.cpp(812): warning C4060: switch statement contains no 'case' or 'default' label

2016-12-18 22:58 UTC, ConradBunton commented on src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.h
> +enum WaypointData
Finally, I revert the commit and it work.

2016-12-18 23:26 UTC, Keader commented
@ConradBunton this PR need a big fucking update...
still has alot of hacks, codestyle, bugs...

2016-12-23 23:33 UTC, bumbummen99 commented
Could this PR possibly profit from https://github.com/Kittnz/Sunwell/tree/master/src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion ? As i have read they have fixed this and many other dungeons/raids.

2017-01-23 22:24 UTC, Viste commented
Hello, i use that script with some restruct all works fine but last boss DK is non attackeble i think it problem here
`        boss_black_knightAI(Creature* creature) : BossAI(creature, DATA_THE_BLACK_KNIGHT)
        {
            Initialize();
            me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
            me->SetReactState(REACT_PASSIVE);
        }
`
and here
`        void EnterEvadeMode(EvadeReason why = EVADE_REASON_OTHER) override
        {
            BossAI::EnterEvadeMode(why);
            me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_IMMUNE_TO_PC);
        }
`
can some one help plz. boss_black_knight.cpp http://paste2.org/dKVF5jkh instance_trial_of_the_champion.cpp http://paste2.org/KIVEAazM

2017-01-24 02:59 UTC, Appled commented
@Aokromes @ariel- @joschiwald @ConradBunton I have allowed edits from maintainers, if that was the setting you were looking for? (I couldn't find that setting earlier when Aok asked me xd)
I know the PR is a true mess and it would be better to rewrite it from scratch but if you think you can fix this mess then do it 👍 I have been off from WoW development for quite some time and I've been working and practising another software developments lately.

2017-01-24 03:10 UTC, Treeston commented
Yup, that's the setting, @Appled - thanks.

This means that this PR is now up for grabs - if any hotshot devs want to try their hand at it, let us know so we can assign.

2017-01-24 06:10 UTC, ariel- commented
I merely fixed merge conflicts with the spell changes.

2017-04-08 06:35 UTC, HannibalRoG commented
Any news with this?

2017-05-08 20:15 UTC, Whizer07 commented
Achievement don't work
(Argent Confessor Paletress and Eadric the Pure)
Fix it pls :З

2017-05-21 16:55 UTC, bumbummen99 commented
Seems like the PR is still up for grab.

2017-08-14 20:52 UTC, D4R4 commented
Currently there is an issue with the script, In the Grand Champion fight in the last phase (ground phase) the champions do not use their abilities. It looks like the ExecuteEvent() in the genericAI's Update prevents the events to be updated in each of the champion's AI (boss_warrior_toc5,boss_mage_toc5,..)

2017-08-15 00:06 UTC, Keader commented
Looks like no one will take over this PR, so closing...
If someone want continue this work, fork appled branch and continue.

2017-08-15 00:06 UTC, closed without merging

2017-08-15 00:08 UTC, Aokromes commented
And to get faster review / merge better do multiple PRs

2017-09-11 09:25 UTC, ConradBunton commented
Worked fine but cant merge it with actual trinitycore.

2017-10-15 18:13 UTC, ConradBunton commented
I try to adapt Appled's scripts with the actual syntax. For the moment, I only added spells part.
What do you think about that ?

diff --git a/src/server/game/Spells/SpellEffects.cpp b/src/server/game/Spells/SpellEffects.cpp
index 15af775..d32e018 100644
--- a/src/server/game/Spells/SpellEffects.cpp
+++ b/src/server/game/Spells/SpellEffects.cpp
@@ -4704,7 +4704,10 @@ void Spell::EffectLeapBack(SpellEffIndex effIndex)
     float speedz = damage/ 10.f;
     //1891: Disengage
     unitTarget->JumpTo(speedxy, speedz, m_spellInfo->SpellIconID != 1891);
-
+    //4022: Rolling Throw
+    m_caster->JumpTo(speedxy, speedz, (m_spellInfo->SpellIconID != 1891 && m_spellInfo->SpellIconID != 4022));
+    if (m_spellInfo->SpellIconID == 4022)
+        unitTarget->JumpTo(speedxy, speedz);
     // changes fall time
     if (m_caster->GetTypeId() == TYPEID_PLAYER)
         m_caster->ToPlayer()->SetFallInformation(0, m_caster->GetPositionZ());

diff --git a/src/server/game/Spells/SpellInfo.cpp b/src/server/game/Spells/SpellInfo.cpp
index 477e3ba..41c5e34 100644
--- a/src/server/game/Spells/SpellInfo.cpp
+++ b/src/server/game/Spells/SpellInfo.cpp
@@ -2267,8 +2267,17 @@ void SpellInfo::_LoadSpellDiminishInfo()
                     return DIMINISHING_NONE;
                 // Screams of the Dead (King Ymiron)
                 else if (Id == 51750)
+                    return DIMINISHING_NONE; 
+                // Triggered trample aura (ToC 5)
+                else if (Id == 67868)
                     return DIMINISHING_NONE;
-                break;
+                // The Black Knight's Death's Respite (ToC 5)
+                else if (Id == 67745)
+                    return DIMINISHING_NONE;
+                // The Black Knight's Death's Respite (Heroic ToC 5)
+                else if (Id == 68306)
+                    return DIMINISHING_NONE;
+                 break;
             }
             // Event spells
             case SPELLFAMILY_UNK1:

diff --git a/src/server/game/Spells/SpellMgr.cpp b/src/server/game/Spells/SpellMgr.cpp
index 22b16a2..abace29 100644
--- a/src/server/game/Spells/SpellMgr.cpp
+++ b/src/server/game/Spells/SpellMgr.cpp
@@ -3613,6 +3613,44 @@ void SpellMgr::LoadSpellInfoCorrections()
         spellInfo->AttributesEx7 |= SPELL_ATTR7_INTERRUPT_ONLY_NONPLAYER;
     });
 
+            // TRIAL OF THE CHAMPION SPELLS
+            //
+	ApplySpellFix({
+		67546,	// Warrior Grand Champion - Rolling Throw
+				// Should hit both caster and target
+    }, [](SpellInfo* spellInfo)
+    {
+        spellInfo->AttributesEx |= SPELL_ATTR1_NO_THREAT;
+    });
+	ApplySpellFix({
+		66797,	// The Black Knight - Death's Push (casted on announcer)
+				// The duration is correct otherwise but announcer dies currently in mid-air
+				// this happens because blizzard has 100-200ms delay before applying an aura
+				// so in retail announcer makes it on the ground before dying
+    }, [](SpellInfo* spellInfo)
+    {
+        spellInfo->DurationEntry = sSpellDurationStore.LookupEntry(39); // 2 seconds instead of 1.7 seconds
+    });
+	ApplySpellFix({
+        67779,	// The Black Knight - Desecration
+				// According to several videos the desecration players lose the desecration debuff in 12 seconds of cast
+				// There is an invisible stalker triggering every 2 seconds a desecration debuff
+				// so setting 10 second duration is correct
+				// besides the visual desecration on the ground disappears in 10 seconds of cast
+    }, [](SpellInfo* spellInfo)
+    {
+        spellInfo->DurationEntry = sSpellDurationStore.LookupEntry(1); // 10 seconds instead of 15 seconds
+    });
+	ApplySpellFix({
+        67802,	// The Black Knight - Desecration Arm
+				// in 3.3.5 there is only one radius in dbc which is 0 yards in this case
+				// use max radius from 4.3.4
+    }, [](SpellInfo* spellInfo)
+    {
+        spellInfo->Effects[EFFECT_0].RadiusEntry = sSpellRadiusStore.LookupEntry(EFFECT_RADIUS_7_YARDS);
+    });
+            // ENDOF TRIAL OF THE CHAMPION SPELLS
+
     ApplySpellFix({
         42490, // Energized!
         42492, // Cast Energized

2017-11-04 07:24 UTC, ConradBunton commented
I think that everyone gave up

2017-11-04 13:41 UTC, tkrokli commented
Well, the overwhelming challenge is to deal with a lot of changes needed in a single PR, although it can also be difficult to break the changes into smaller PRs because of how much the individual parts affect each other. If there had been an easy way to split this PR into individual parts, I suspect someone would have posted those PRs already.

But by all means, feel free to suggest a list of parts or NPC names you think will be appropriate for separate PRs.

2017-11-04 17:08 UTC, Jildor commented
I suggest create a new branch with this Pull Request and then, all can create a little Pull Request for clean and fix the code better

I think it's better than nothing 😉

2017-11-04 17:12 UTC, ConradBunton commented
Appled scripts worked good but now, the syntax changed. So, the compil has too many conflict.

2017-11-04 17:20 UTC, tkrokli commented
Sure, but I kind of like Jildor's suggestion about making a branch for the existing code, even if it does not work with current code, and then ask contributors to improve on the code via minor PRs.

2017-11-05 02:13 UTC, Appled commented
The content worked as intended to but I agree the way I implemented the vehicle combat was/is very hacky. That was mostly due to poor vehicle system at time and/or lack of my knowledge towards the vehicle system. Timers, combat and roleplaying events for each encounter however were well researched, and if someone is working on this, I hope he or she uses them. Good luck.

2017-11-05 04:33 UTC, tkrokli commented
I have only managed to fix the SQL file contents, but there are 5 travis-ci compile errors in the scripts (probably missing some `#include` somewhere).

I will push my `3.3.5-trial_of_the_champion` branch to TrinityCore to make it available for new PRs so it can be fixed.

2018-02-15 15:42 UTC, Treeston commented
Succeeded by #21427.