Core/Entity : Conversation
TrinityCore/TrinityCore pull request #18001
Opened 2016-09-25 15:29 UTC by Traesh

**Changes proposed:**

-  Implement Conversation Entity, used to display ingame dialog
-  Command .debug conversation # convId
-  Command .Reload conversation_template
- Add 5 tables for templates, actors & lines

**Target branch(es):** 6.x

**Issues addressed:** Closes #17992

**Tests performed:** (Does it build, tested in-game, etc)
Built
Tested ingame with conversation id 708    (.debug conv 705)
Tested ingame with conversation id 1025  (.debug conv 1025)

**Known issues and TODO list:**

- None ATM

2016-09-25 15:38 UTC, Shauren commented on src/server/game/Entities/Conversation/Conversation.cpp
> +        AddDynamicValue(CONVERSATION_DYNAMIC_FIELD_ACTORS, actor.Id);
If each actor requires several entries in the updatefield then use "structured dynamic values" - look at how item gems and artifact powers are implemented

2016-09-25 15:40 UTC, Shauren commented on src/server/game/Entities/Object/Object.cpp
> +                if (updateType != UPDATETYPE_VALUES || _dynamicChangesArrayMask[index][v])
I don't like this change - messing with code here affects every object type, generally only non zero values are sent on create

2016-09-25 15:44 UTC, akrom23 commented
How about sceneobjects? :)

2016-09-25 15:44 UTC, Shauren commented on src/server/game/Globals/ObjectMgr.cpp
> +void ObjectMgr::LoadConversationTemplates()
All queries here are used only in this method and only during startup, there is no need to make them prepared statements (reloading is seen as development purpose, should not affect deciding whether to use a prepared statement or not)

2016-09-25 15:44 UTC, Shauren commented on src/server/game/Globals/ObjectMgr.h
> -
this empty line should be here

2016-09-25 15:45 UTC, Shauren commented on sql/updates/world/6.x/9999_99_99_00_world.sql
> +CREATE TABLE IF NOT EXISTS `conversation_template` (
Write these as DROP TABLE IF EXISTS + CREATE TABLE

2016-09-25 15:46 UTC, Shauren commented on sql/updates/world/6.x/9999_99_99_00_world.sql
> +DELETE FROM conversation_actor_template WHERE Id IN (49825, 50124);
since the purpose of this sql is to create tables, you can omit deletes

2016-09-25 15:47 UTC, Shauren commented on sql/updates/world/6.x/9999_99_99_00_world.sql
> +(1025, 3458, 22624);
You are adding new commands, this sql should also insert data to `command` table with help text

2016-09-25 15:47 UTC, Shauren requested changes

2016-09-25 16:37 UTC, Traesh commented on src/server/game/Entities/Object/Object.cpp
> +                if (updateType != UPDATETYPE_VALUES || _dynamicChangesArrayMask[index][v])
I understand, but in my sniffs there is a lot of DYNAMIC_FIELD send even if value is 0 at creation.

Conversation does not work if 0 value is not sent, so this is mandatory, but of course there is perhaps a better way to do it

2016-09-26 13:15 UTC, Shauren commented on src/server/game/Entities/Conversation/Conversation.cpp
> +    ///- Register the AreaTrigger for guid lookup and for caster
that comment copypaste

2016-09-26 14:19 UTC, Traesh commented on src/server/game/Entities/Conversation/Conversation.cpp
> +    ///- Register the AreaTrigger for guid lookup and for caster
Don't know what you're talking about, i'm innocent

2016-09-27 07:33 UTC, closed without merging

2016-09-27 07:33 UTC, Traesh commented
Now at #18010 due to a fail on previous repo