Core/Player Quest&Phase update improve.
TrinityCore/TrinityCore pull request #18146
Opened 2016-10-26 19:55 UTC by Palabola

[//]: # (*********************************)
[//]: # (** DO NOT DELETE THIS TEMPLATE **)
[//]: # (*********************************)

**Changes proposed:**

-  Better handling for Quest based Phase changes. (Complete,Taken,Rewarded,(Objective Completed)...)
-  
-  

**Target branch(es):** 3.3.5/master

**Issues addressed:** Closes #

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** None!

**DEPRECATION NOTICE** When creating new PRs to the (old) 6.x branch, make sure the target branch is **master** instead of 6.x.
**NOTE** Enable the setting "Allow edits from maintainers." when creating your pull request.  
**NOTE** If this PR __only__ contains SQL files, create an issue instead.  
**NOTE** Squashing commits is not required.  
**SUGGESTION** When adding new SQL files, name them 9999_99_99_99_db_name.sql to reduce the chance of possible merge conflicts.

Better functionality for Phase changing and updating.

2016-10-26 21:23 UTC, Keader requested changes
remove white space

2016-10-26 21:23 UTC, Keader commented on src/server/game/Entities/Player/Player.cpp
> +	UpdateAreaAndZonePhase();
identation :)

2016-10-26 22:04 UTC, Aokromes commented on src/server/game/Entities/Player/Player.cpp
> +	UpdateAreaAndZonePhase();
in fact, tab to spaces :P

2016-10-27 09:24 UTC, jackpoz commented
> Tests performed: (Does it build, tested in-game, etc.)

no tests performed ?

2016-10-27 09:37 UTC, zamalaev commented
jackpoz, I checked on the Pandaren and works well

2016-10-27 10:18 UTC, DDuarte commented
This is equal to #16973 which got open and closed by Lopfest.
@Lopfest could you give some info on this?

2016-10-27 11:15 UTC, funjoker commented
U think blizz is doing those Updates via spell.
Saw many spells in sniffs which Force a Phase update

2016-10-27 11:37 UTC, jackpoz commented
> jackpoz, I checked on the Pandaren and works well

you should write in the PR description which tests you did in the most detailed way. You should describe the previous behavior, the current behavior (and for this particular PR the quest ID you tested).

2016-10-27 13:57 UTC, Palabola commented
@jackpoz  Easy,

**Current version:**
1. Create Phase in (phase_area) table and any Quest Condition(Reward,Complete,Taken...) for it into the (conditions) table.
2. Complete,Take or Reward the Quest and nothing will happen with your Phase. (It will update only  with your next relog/area change!)
**Updated version:**
1. Create Phase in (phase_area) table and any Quest Condition(Reward,Complete,Taken...) for it into the (conditions) table.
2. Complete,Take or Reward the Quest your Phase will be updated based on Phase_area and Condition.

**Proof of concept:**
- Long time ago same functionality were in spell_area table with quest_start_status / quest_end_status field. 
- 

**Posible conflicts:**
- None, since relog or re-enter the Area use the same effect.

2016-10-27 13:59 UTC, Lopfest commented
@DDuarte Well, like I have written in that closed PR of mine, first I thought the same as this PR description sais. I dont remember exactly what changed my mind, but it looks like I found a quest that was not matching this behavior. I shoud have written the quest ID in the comment :(

2016-10-29 17:32 UTC, zamalaev commented
I do not quite understand, but I think this hack

2016-11-02 20:00 UTC, Lopfest commented
One great example of exception is this quest [The Missing Driver](http://www.wowhead.com/quest=29419/the-missing-driver) in pandaren starting zone. Phases should definitely not be updated automatically when the quest becomes complete. It should be updated manually via AI few moments after quest is complete, or MAYBE when player do a relog before the manual update.

2016-11-02 20:49 UTC, Palabola commented
It's only update the phase if you allow in the condition to be updated, but okay If reloging after every quest more blizzlike up to you.

2016-11-02 21:03 UTC, Lopfest commented
no forget relogging :D in that quest, you have condition that phase should update only if the quest is complete or rewarded. but the phase shouldnt be updated immediatelly after quest becomes complete, thats the point.

2016-11-08 00:28 UTC, funjoker commented
@Lopfest 

> you have condition that phase should update only if the quest is complete or rewarded. but the phase shouldnt be updated immediatelly after quest becomes complete, thats the point.

example?

2016-11-08 07:15 UTC, Lopfest commented
@funjoker 

> One great example of exception is this quest The Missing Driver in pandaren starting zone. Phases should definitely not be updated automatically when the quest becomes complete. It should be updated manually via AI few moments after quest is complete...

few posts above...

2016-11-19 10:41 UTC, Palabola commented
@Lopfest Simlply not enought some quest ender become only seeable only after you completed the Quest just like some Phase which activeted after an Objective become completed. 
This PR work in practice, that's my last word about it.

2017-02-19 13:34 UTC, Lopfest commented
can anyone make some statement about this PR and whether there can be added quest exception list in the code? For example something like this:
```
void Player::CompleteQuest(uint32 quest_id)
{
    if (quest_id)
    {
        switch (quest_id)
        {
            case 29419:
                SetQuestStatus(quest_id, QUEST_STATUS_COMPLETE, false);
                break;
            default:
                SetQuestStatus(quest_id, QUEST_STATUS_COMPLETE);
                break;
        }
...
```

2017-02-23 21:31 UTC, tkrokli commented
@Lopfest : I am fairly sure it's a bad idea to hardcode the status of specific quests when you can use the DB table `disables` instead. Quest status should not be handled like spell exceptions.

2017-02-23 21:33 UTC, Lopfest commented
I totaly forgot about disables table. That will suffice too.

2017-06-03 06:20 UTC, Aokromes commented
Sooo, this pr is valid or invalid? it's ridiculous to have one 1 row PR opened for more than half year.

2017-06-04 14:55 UTC, funjoker commented
for me it's invalid. Due to some quests do not force a phase update.
Phase updates are also often done by spells which are casted on quest accept.

2017-06-04 15:13 UTC, Shauren commented
@funjoker going to trust you on this one, you have more experience with quest phasing

2017-06-04 15:13 UTC, closed without merging

2017-06-05 01:14 UTC, funjoker commented
The one and only thing i can imagine where the phase update could accure by quest update is, when a quest gets abonded.

2017-06-05 09:18 UTC, Golrag commented
There is a quest flag in WPP UpdatePhaseShift (0x00400000). It's not in the core tho