Add CONDITION_QUEST_OBJECTIVE_COMPLETE
TrinityCore/TrinityCore pull request #18235
Opened 2016-11-10 21:53 UTC by funjoker

[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Added new Condition to ConditionMgr (thank you @Traesh)
-  Added IsObjectiveComplete bool (thank you @Traesh)

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:** Closes #17863

2016-11-10 22:02 UTC, joschiwald commented on src/server/game/Entities/Player/Player.h
> +        bool IsQuestObjectiveComplete(Quest const* quest, QuestObjective objective) const;
QuestObjective const&

2016-11-11 08:17 UTC, Aokromes commented
/home/travis/build/TrinityCore/TrinityCore/src/server/game/Conditions/ConditionMgr.cpp:468:42: fatal error: 
      comparison of integers of different signs: 'const int8'
      (aka 'const signed char') and 'const uint32' (aka 'const unsigned int')
      [-Wsign-compare]
                    if (obj.StorageIndex == ConditionValue2)
                        ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~

2016-11-11 08:23 UTC, jackpoz commented on src/server/game/Entities/Player/Player.cpp
> +    case QUEST_OBJECTIVE_MONSTER:
please keep the original indentation

2016-11-11 16:16 UTC, funjoker commented on src/server/game/Entities/Player/Player.cpp
> +    case QUEST_OBJECTIVE_MONSTER:
oh auto formation

2016-11-11 16:16 UTC, funjoker commented
@Aokromes 

To Do:

storageIndex can be -1 (Conditions only support uint at the moment)

2016-11-24 06:05 UTC, Aokromes requested changes

2017-01-08 10:31 UTC, Aokromes approved these changes

2017-03-19 11:07 UTC, Aokromes commented
Conflicting files
src/server/game/Conditions/ConditionMgr.cpp
src/server/game/Conditions/ConditionMgr.h

2017-03-19 13:29 UTC, tkrokli commented
AppVeyor failed because I posted commit https://github.com/TrinityCore/TrinityCore/pull/18235/commits/93d2026a1c0850371ac0cab695e649475d9f3128 before the build fix (https://github.com/TrinityCore/TrinityCore/commit/27bf4010b8d12c27d3d8f6df40bff3d9b1a425b1).

2017-03-19 16:25 UTC, Shauren commented
`sObjectMgr->GetQuestObjective(questObjectiveId)` is now a thing

2017-03-19 16:43 UTC, funjoker commented
@Shauren thanks

2017-03-19 20:53 UTC, Shauren commented on src/server/game/Globals/ObjectMgr.h
> +        std::pair<QuestObjective const*, uint32> const* GetQuestObjectivePairData(uint32 questObjectiveId) const
thats not QuestID inside QuestObjective

2017-03-19 21:00 UTC, funjoker commented on src/server/game/Globals/ObjectMgr.h
> +        std::pair<QuestObjective const*, uint32> const* GetQuestObjectivePairData(uint32 questObjectiveId) const
_questObjectives[obj.ID] = std::make_pair(&obj, qinfo->GetQuestId());

2017-03-19 22:39 UTC, funjoker commented
Removed the pair, because it's unecessary if the questid is already in struct.
Would only cause duplicate of data.

2017-03-20 07:54 UTC, merged