Update Spell_monk.cpp
TrinityCore/TrinityCore pull request #18536
Opened 2016-12-20 13:35 UTC by Teleslet

fixed spell roll

[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

-  Fixed spell roll for monk
-  
-  

**Target branch(es):** 3.3.5/master

- [ ] master

**Issues addressed:** Closes #  (insert issue tracker number)

	8990375
**Tests performed:** (Does it build, tested in-game, etc.)

Tested in game
**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ] 

[//]: # (**DEPRECATION NOTICE** Instead of creating new PRs to the (old) 6.x branch, make sure the target branch is **master** instead of 6.x.)
[//]: # (**NOTE** Enable the setting "[√] Allow edits from maintainers." when creating your pull request (if not enabled already).)
[//]: # (**NOTE** If this PR __only__ contains SQL files, open a new issue instead and post or link the SQL there.)
[//]: # (**SUGGESTION** When adding new SQL files, name them 9999_99_99_99_db_name.sql to reduce the chance of possible merge conflicts.)

2016-12-20 14:00 UTC, Keader requested changes
Change Tabs to spaces in all file please

2016-12-20 14:01 UTC, Keader commented on src/server/scripts/Spells/spell_monk.cpp
> +			if (!sSpellMgr->GetSpellInfo(SPELL_MONK_ROLL))
you should validate here ```SPELL_MONK_ROLL_TRIGGER```

2016-12-20 14:02 UTC, Keader commented on src/server/scripts/Spells/spell_monk.cpp
> +			if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
Caster cant be null in SpellScript, and this check ```caster->GetTypeId() != TYPEID_PLAYER``` should be in Load function :)

2016-12-20 14:03 UTC, Keader commented on src/server/scripts/Spells/spell_monk.cpp
> +		void Register()
missing override

2016-12-20 14:03 UTC, Keader commented on src/server/scripts/Spells/spell_monk.cpp
> +	SpellScript* GetSpellScript() const
missing override

2016-12-20 14:30 UTC, Keader commented on src/server/scripts/Spells/spell_monk.cpp
>  			if (!sSpellMgr->GetSpellInfo(SPELL_MONK_ROLL))
you just need check spells used inside of your spellscript.
in this case, only ```SPELL_MONK_ROLL_TRIGGER```

2016-12-20 14:32 UTC, Keader commented on src/server/scripts/Spells/spell_monk.cpp
> -			if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
add it:

```cpp
            bool Load() override
            {
                return GetCaster()->GetTypeId() == TYPEID_PLAYER;
            }
```
below or above Validate function.

2016-12-20 14:35 UTC, Keader commented
Missing a sql file
something like:
```sql

DELETE FROM `spell_script_names` WHERE `ScriptName`='spell_monk_roll';
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES
(109132,'spell_monk_roll');

```

2016-12-26 21:00 UTC, Keader commented
Any news on this @Teleslet?
Still missing sql file and still missing change tabs to 4 spaces

2017-01-25 20:10 UTC, Keldo commented
Still doesnt work, Click, Sound Effects Work, No Action, Timer is present --- No Roll.

2017-01-26 13:48 UTC, Shauren commented
PR doesn't work at all? K.

2017-01-26 13:48 UTC, closed without merging