Core/Player: UpdateCraftSkill
TrinityCore/TrinityCore pull request #19023
Opened 2017-02-01 22:14 UTC by DoctorKraft

[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

- Add new system for profession skill where a craft give more than 1 skill points
For example : http://www.wowhead.com/spell=167950/research-warbinders-ink (Rewards 3 skill points)
-  Rewrite for better understanding

**Target branch(es):** 3.3.5/master

- [ ] master

**Issues addressed:** Closes #  Unk

**Tests performed:** Build & Tested in-game

2017-02-01 22:31 UTC, joschiwald commented on src/server/game/Entities/Player/Player.cpp
> +                craft_skill_gain = _spell_idx->second->NumSkillUps;
could it be also `_spell_idx->second->NumSkillUps * sWorld->getIntConfig(CONFIG_SKILL_GAIN_CRAFTING)`?

2017-02-01 22:38 UTC, DoctorKraft commented on src/server/game/Entities/Player/Player.cpp
> +                craft_skill_gain = _spell_idx->second->NumSkillUps;
Sure ! CONFIG_SKILL_CHANCE_ORANGE better no ? Because all skill with NumSkillUps > 1 is orange

2017-02-01 22:44 UTC, Shauren requested changes

2017-02-01 22:44 UTC, Shauren commented on src/server/game/Entities/Player/Player.cpp
> +                        return UpdateSkillPro(parentSkillId, skill_gain_chance, craft_skill_gain);
This is for child skills like MoP cooking so this is no good. You need to give guaranteed skill value equal to highest child skilline, not grant a separate roll (also you need to make sure.
I suggest only doing the multiple skillups in this PR as the title says.

2017-02-01 23:05 UTC, DoctorKraft commented on src/server/game/Entities/Player/Player.cpp
> +                        return UpdateSkillPro(parentSkillId, skill_gain_chance, craft_skill_gain);
Ok thanks, i have missed this. It's a very old code ! Fixed :)

2017-02-02 11:30 UTC, DoctorKraft commented
I have updated, say me if you prefer with old codestyle

2017-02-03 19:53 UTC, Shauren approved these changes

2017-02-03 20:05 UTC, merged