Use system supported threads instead of hardcoded amount for mmaps
TrinityCore/TrinityCore pull request #19255
Opened 2017-03-06 16:41 UTC by Rochet2

[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

- Use unsigned int for thread count
- Use std::thread::hardware_concurrency() to try estimate available threads instead of hardcoded 3 threads by default for mmap generation
- Print thread count always regardless of using --threads switch or not

Motivation:
Not everyone uses the extractor.bat in contrib, its not available for linux, not everyone uses the switches and people with 8 cores end up with 3 threads. Multiple people have been using the extractor directly and not have been aware of the thread switch and have had multiple cores.

With the changes we use c++11 functions to get the system supported thread count and use that to utilize all system cores.
According to http://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency it gives only a hint though and it is possible the count cannot be found. In these cases 0 is used, which means only single threaded processing instead of the hardcoded 3.
If wanted, there could be used std::max to define either 3 or the std::thread::hardware_concurrency() amount of threads if the switch is not used to make sure that when the amount cannot be deduced then at least 3 are used.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)
Builds and tested extracting to see the print.
With default settings used 4 threads on 4 core system. Tested using --threads switch to change threads from -5  to 0 to 5 and results are 0, 0 and 5.

**Known issues and TODO list:** (add/remove lines as needed)

2017-03-06 20:02 UTC, zamalaev commented
hm, type int == unsigned int = 0 before 65535 (2^16)-1) ?

зачем?
possible negative value?

2017-03-06 20:21 UTC, ariel- commented
int is 32bit long, not 16. And think about what the variable stores. Does it make sense to have a negative amount of threads/cpu cores?

2017-03-06 20:23 UTC, Rochet2 commented
std::thread::hardware_concurrency() returns unsigned int, which is why I changed the int to unsigned int.
And the code ignored negative values and handled them like 0 is handled, which is why now negative values passed to the switch are converted to 0.

2017-03-06 20:35 UTC, zamalaev commented
need pro code, Shauren)))

2017-03-06 20:40 UTC, Naios commented on src/tools/mmaps_generator/PathGenerator.cpp
> +               unsigned int& threads)
Is there any reason to pass this by reference? The amount of threads doesn't change during program execution neither is adjusting of the threadpool supported.

2017-03-06 20:41 UTC, Naios requested changes

2017-03-06 20:41 UTC, Naios commented on src/tools/mmaps_generator/PathGenerator.cpp
> +               unsigned int& threads)
Is there any reason to pass this by reference? The amount of threads doesn't change during program execution neither is adjusting of the threadpool supported.

2017-03-06 20:46 UTC, Shauren commented on src/tools/mmaps_generator/PathGenerator.cpp
> +               unsigned int& threads)
yes, thats handleArgs reading command line arguments (--threads)

2017-03-06 20:47 UTC, Naios approved these changes

2017-03-09 08:24 UTC, jackpoz commented
looks ok (altho it will kill your cpu while extracting mmaps)

2017-03-09 08:43 UTC, Shauren commented
--threads option is still supported (and if people use the .bat from /contrib then this PR sets the same value, at least in theory)

2017-03-09 14:45 UTC, Warpten commented on src/tools/mmaps_generator/PathGenerator.cpp
> +    unsigned int threads = std::thread::hardware_concurrency();
`std::thread::hardware_concurrency()` can return 0. `std::max(std::thread::hardware_concurrency(), 1u);` would do better.

2017-03-09 14:45 UTC, Warpten commented on src/tools/mmaps_generator/PathGenerator.cpp
> +            threads = static_cast<unsigned int>(std::max(0, atoi(param)));
Probably here too.

2017-03-09 17:52 UTC, Rochet2 commented on src/tools/mmaps_generator/PathGenerator.cpp
> +    unsigned int threads = std::thread::hardware_concurrency();
Hmm, not sure it makes it better. And 0 is a valid thread count to the program. The thread number is actually the number of threads additional to the program main thread.

Preventing 0 as thread count will disable one "feature" of the program as it is.
See this:
https://github.com/Rochet2/TrinityCore/blob/f41c26761df4272fe8343fc61439f7cc06af04c9/src/tools/mmaps_generator/MapBuilder.cpp#L212

2017-03-09 17:53 UTC, Rochet2 commented on src/tools/mmaps_generator/PathGenerator.cpp
> +            threads = static_cast<unsigned int>(std::max(0, atoi(param)));
Preventing 0 as thread count will disable one "feature" of the program as it is.
See this:
https://github.com/Rochet2/TrinityCore/blob/f41c26761df4272fe8343fc61439f7cc06af04c9/src/tools/mmaps_generator/MapBuilder.cpp#L212

2017-03-09 18:15 UTC, jackpoz commented
Just merge it :)

2017-03-09 22:21 UTC, Warpten commented on src/tools/mmaps_generator/PathGenerator.cpp
> +    unsigned int threads = std::thread::hardware_concurrency();
There is, if you have threads = 0 even after parameters parsing goes through, nothing happens. It sounds dumb.

2017-03-09 22:21 UTC, Warpten commented on src/tools/mmaps_generator/PathGenerator.cpp
> +            threads = static_cast<unsigned int>(std::max(0, atoi(param)));
nvmd then, didnt see that

2017-03-17 18:09 UTC, merged