Implement quest_request_items_locale
TrinityCore/TrinityCore pull request #19331
Opened 2017-03-19 13:28 UTC by AlcDenat

**Changes proposed:** Add a new table quest_request_items_locale and code

**Target branch(es):** master

**Issues addressed:** Missing locale table

**Tests performed:** no errors, code works ingame

**Known issues and TODO list:** none

2017-03-19 14:23 UTC, Shauren requested changes

2017-03-19 14:23 UTC, Shauren commented on src/server/game/Globals/ObjectMgr.cpp
> +        AddLocaleString(CompletionText, locale, data.RequestItemsText);
copypaste is strong here, `CompletionText`

2017-03-19 14:32 UTC, AlcDenat commented on src/server/game/Globals/ObjectMgr.cpp
> +        AddLocaleString(CompletionText, locale, data.RequestItemsText);
While 98% of this stuff is copy & paste, CompletionText is the field name in the original table and thus in the _locale table I created. I'd say it's ok to just let it be - It's never reused anyway.

2017-03-19 14:45 UTC, joschiwald commented on src/server/game/Globals/ObjectMgr.cpp
> +        AddLocaleString(CompletionText, locale, data.RequestItemsText);
`CompletionText` should be fine, rename `RequestItemsText` -> `CompletionText`

2017-03-19 14:46 UTC, Shauren commented on src/server/game/Globals/ObjectMgr.cpp
> +        AddLocaleString(CompletionText, locale, data.RequestItemsText);
just rename it to RequestItemsText to remove inconsistencies

2017-03-19 16:02 UTC, Shauren commented on src/server/game/Globals/ObjectMgr.cpp
> +        AddLocaleString(CompletionText, locale, data.RequestItemsText);
The reason I recommend keeping the `RequestItems` name is because that is the field name used in packet

2017-03-19 16:38 UTC, AlcDenat commented on src/server/game/Globals/ObjectMgr.cpp
> +        AddLocaleString(CompletionText, locale, data.RequestItemsText);
Changed it to RequestItems, should be fine now.

2017-03-19 22:32 UTC, joschiwald commented
@Shauren i don't get your point, in packet it is named `CompletionText`

or something changed since 6.x?
```c#
public class ClientQuestGiverRequestItems
{
    public string QuestTitle                { get; set; }
    public QuestGiverRequestItems QuestData { get; set; }
    public string CompletionText            { get; set; }
}
```

2017-03-20 08:26 UTC, Shauren commented
fine then

2017-03-21 16:45 UTC, closed without merging