Script/Spell : Warlock Rain of Fire
TrinityCore/TrinityCore pull request #19345
Opened 2017-03-22 00:06 UTC by Traesh

**Changes proposed:**

-  Fix Warlock spell "Rain of Fire" (http://www.wowhead.com/spell=5740). The Warlock can have multiple "Rain of Fire" areatrigger spawned, but a single target will always receive damage only once per tick
-  Minor cleanup (delete 1 old spell, removed from game)

**Target branch(es):**

- [ ] master

**Issues addressed:** None

**Tests performed:** (Does it build, tested in-game, etc.)
Compiled, tested ingame

**Known issues and TODO list:** (add/remove lines as needed)
- None

2017-03-22 01:12 UTC, Exodius requested changes

2017-03-22 01:12 UTC, Exodius commented on src/server/scripts/Spells/spell_warlock.cpp
> +// 5740 - Demonic Circle: Summon
Shouldn't this line say
// 5740 - Rain of Fire
?

2017-03-22 06:44 UTC, Traesh commented on src/server/scripts/Spells/spell_warlock.cpp
> +// 5740 - Demonic Circle: Summon
Yup, bad copy paste x)

2017-03-22 09:22 UTC, Shauren requested changes

2017-03-22 09:22 UTC, Shauren commented on src/server/scripts/Spells/spell_warlock.cpp
> +                GuidUnorderedSet insideTargets = rainOfFireAreaTrigger->GetInsideUnits();
const& - dont copy

2017-03-22 10:16 UTC, Shauren approved these changes

2017-03-22 14:48 UTC, joschiwald commented on sql/updates/world/master/9999_99_99_19344_world.sql
> +(10133, 0, 0, 8, 8, 0, 0, 0, 0, "", 23420);
we already have this areatrigger_template in db

2017-03-25 08:42 UTC, tkrokli commented on sql/updates/world/master/9999_99_99_19344_world.sql
> +DELETE FROM `spell_script_names` WHERE `spell_id`=5740;
Please delete by `ScriptName` instead of `spell_id` to remove any existing spell script names using a different spell ID.

2017-03-25 12:37 UTC, ghost approved these changes

2017-03-25 13:22 UTC, Keader commented on sql/updates/world/master/9999_99_99_19345_world.sql
> +DELETE FROM `spell_script_names` WHERE `spell_id`=5740 OR `ScriptName`="spell_warl_rain_of_fire";
We always use ```ScriptName``` because 1 id can have multiple scripts linked to him

2017-03-25 13:25 UTC, tkrokli commented on sql/updates/world/master/9999_99_99_19345_world.sql
> +DELETE FROM `spell_script_names` WHERE `spell_id`=5740 OR `ScriptName`="spell_warl_rain_of_fire";
Yes, that is taken care of already in commit https://github.com/TrinityCore/TrinityCore/pull/19345/commits/42591e59c87f441f3c9d91fa86dd00437bc9aeac. Notice the use of `OR` as a divider.
Deleting any spell scripts using `spell_id` 5740 is just an extra precaution. :-)

2017-03-25 16:20 UTC, Exodius approved these changes

2017-03-25 17:09 UTC, ariel- commented on sql/updates/world/master/9999_99_99_19345_world.sql
> +DELETE FROM `spell_script_names` WHERE `spell_id`=5740 OR `ScriptName`="spell_warl_rain_of_fire";
OR is not AND, it should delete only by ScriptName, not by spell_id

2017-03-25 17:29 UTC, tkrokli commented on sql/updates/world/master/9999_99_99_19345_world.sql
> +DELETE FROM `spell_script_names` WHERE `spell_id`=5740 OR `ScriptName`="spell_warl_rain_of_fire";
Well, if you think about the use of `AND`, it is very selective whereas `OR` is not.
This variant opens for deleting both for all cases of `ScriptName`='spell_warl_rain_of_fire'
as well as deleting that special case of `spell_id`= 5740.

2017-03-27 12:19 UTC, Keital commented on sql/updates/world/master/9999_99_99_19345_world.sql
> +DELETE FROM `spell_script_names` WHERE `spell_id`=5740 OR `ScriptName`="spell_warl_rain_of_fire";
@tkrokli you still don't get it..... delete just by scriptname.... what about spell 5740 maybe has another script linked..... for example for a talent???? then you just unlink it too????

2017-03-27 12:21 UTC, Keader commented on sql/updates/world/master/9999_99_99_19345_world.sql
> +DELETE FROM `spell_script_names` WHERE `spell_id`=5740 OR `ScriptName`="spell_warl_rain_of_fire";
Delete only by ScriptName please.

2017-03-27 22:18 UTC, Exodius commented on sql/updates/world/master/9999_99_99_19345_world.sql
> +DELETE FROM `spell_script_names` WHERE `spell_id`=5740 OR `ScriptName`="spell_warl_rain_of_fire";
Long story short:
```diff
-DELETE FROM `spell_script_names` WHERE `spell_id`=5740 OR `ScriptName`="spell_warl_rain_of_fire";
+DELETE FROM `spell_script_names` WHERE `ScriptName`="spell_warl_rain_of_fire";

2017-04-01 19:44 UTC, merged