Core/ScriptReloadMgr: Fixed scripts hot swapping on OS X
TrinityCore/TrinityCore pull request #19365
Opened 2017-03-25 22:59 UTC by svranesevic

**Changes proposed:**
-  Added appropriate dynamic linking include, and shared library extension for OS X
-  Canonicalized world server executable path in ScriptReloadMgr::GetDirectoryOfExecutable()

**Target branch(es):** 3.3.5/master
- [x] 3.3.5
- [ ] master

**Issues addressed:**

**Tests performed:**
- [x] Builds
- [x] Tested in-game

**Known issues and TODO list:**

2017-03-25 23:27 UTC, Naios commented
Nice that finally someone fixed hotswap for OSX :-)

2017-03-25 23:36 UTC, Naios requested changes
Well done :-)
The commit is only missing the support for uninstalling `.dylib` as mentioned in the review.

2017-03-25 23:36 UTC, Naios commented on src/server/game/Scripting/ScriptReloadMgr.cpp
> +    #define HOTSWAP_PLATFORM_REQUIRES_CACHING
Is caching of binaries actually required on OSX?
The BSD kernel should behave similar to Linux not locking the loaded shared libraries on usage.

2017-03-25 23:36 UTC, Naios commented on src/server/game/Scripting/ScriptReloadMgr.cpp
> +        return fs::canonical(fs::absolute(path)).parent_path();
👍

2017-03-25 23:36 UTC, Naios commented on src/server/game/Scripting/ScriptReloadMgr.cpp
> +    return "dylib";
You are also required to add an entry in the CMake function [here](https://github.com/TrinityCore/TrinityCore/blob/86b98686a95e23247ecb774fb23ecd5b8d94b97b/cmake/macros/ConfigureScripts.cmake#L89) so the shared library gets removed properly on uninstall.

2017-03-25 23:38 UTC, svranesevic commented on src/server/game/Scripting/ScriptReloadMgr.cpp
> +    return "dylib";
Roger.

2017-03-25 23:38 UTC, svranesevic commented on src/server/game/Scripting/ScriptReloadMgr.cpp
> +    #define HOTSWAP_PLATFORM_REQUIRES_CACHING
It is, I will check again tho.

2017-03-26 01:14 UTC, svranesevic commented on src/server/game/Scripting/ScriptReloadMgr.cpp
> +    #define HOTSWAP_PLATFORM_REQUIRES_CACHING
It is needed indeed,
Without caching compilation and reload procedures are triggered, however after reload old scripts are still used by the core.

For the sake of my curiosity, is there anything else that could be causing this behaviour ?

2017-03-26 01:17 UTC, Naios approved these changes

2017-03-26 01:34 UTC, Naios commented on src/server/game/Scripting/ScriptReloadMgr.cpp
> +    #define HOTSWAP_PLATFORM_REQUIRES_CACHING
How did you see that the scripts are still usable by the core?
Maybe you could explain your impressions in detail.

Caching is required only if you can't delete shared libraries out of the `scripts` directory through your file explorer (when caching is disabled).

2017-03-26 02:16 UTC, svranesevic commented on src/server/game/Scripting/ScriptReloadMgr.cpp
> +    #define HOTSWAP_PLATFORM_REQUIRES_CACHING
I was playing around with '.gm' command from GM script, and making changes in notification system (eg. GM mode on/off) so I could have visual feedback on functionality of loaded script.
And without caching script used by the core is not reloaded at all, even though whole compile/reload procedure successfully completes after script file change.

Also , OS X definitely does not lock loaded shared libraries.

2017-03-26 11:42 UTC, Naios commented on src/server/game/Scripting/ScriptReloadMgr.cpp
> +    #define HOTSWAP_PLATFORM_REQUIRES_CACHING
Ah ok, don't know why that is the case, but then just let the system cache the binaries for the OSX platform.

2017-03-31 21:09 UTC, Shauren approved these changes

2017-03-31 21:10 UTC, Shauren commented
Looks good enough to me

2017-03-31 21:10 UTC, merged