Core/Scripts: Implemented ScriptLoader Extensions
TrinityCore/TrinityCore pull request #19526
Opened 2017-04-29 13:36 UTC by Seyden

[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

The purpose of this PR is, to shorten the scripts.. we can outsource the header and the footer of scripts..
actually we're writing the header and footer in each script.

As example: https://gist.github.com/Seyden/8b4d849b2ad0b3bb481fe80637496398

- AuraScriptLoader extension
- SpellScriptLoader extension
- SpellAuraScriptLoader extension
- AreaTriggerEntityScriptLoader extension

**Target branch(es):** master

- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

- [x] tested ingame with a lot of scripts

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] No known issue

2017-04-30 08:45 UTC, joschiwald commented on src/server/game/Scripting/ScriptMgr.h
> +    SpellScript* GetSpellScript() const
missing override

2017-04-30 08:47 UTC, joschiwald commented on src/server/game/Scripting/ScriptMgr.h
> +    SpellScriptLoaderEx(const char* name) : SpellScriptLoader(name) {}
codestyle: const after type and one space between {}
`SpellScriptLoaderEx(char const* name) : SpellScriptLoader(name) { }`

2017-04-30 09:53 UTC, Shauren requested changes

2017-04-30 09:53 UTC, Shauren commented on src/server/game/Scripting/ScriptMgr.h
> +struct SpellScriptLoaderEx : public SpellScriptLoader
SpellScriptLoader is a class so why are all of these struct?

2017-04-30 10:27 UTC, Shauren commented on src/server/game/Scripting/ScriptMgr.h
> +    SpellScriptLoaderEx(char const* name) : SpellScriptLoader(name) { }
`public:`

2017-06-14 14:19 UTC, Seyden commented
What is missing?

2017-06-14 21:26 UTC, tkrokli commented
Approval from Shauren, I suppose.

2017-07-16 09:45 UTC, Vincent-Michael commented
remove pls whitespaces

2017-07-18 07:32 UTC, Aokromes commented
anything left here?

2017-07-18 09:56 UTC, tkrokli commented
Approval from Shauren, maybe?

2017-07-18 12:12 UTC, Shauren approved these changes

2017-07-18 12:13 UTC, Shauren commented
Code is ok, I don't like the `Ex` in name but at the same time I have no better idea

2017-07-18 21:48 UTC, Seyden commented
@Shauren maybe there is a way to drop this redundant code completly? Isn't there a way to prevent using always SpellScript* GetSpellScript and this things?

2017-07-19 00:05 UTC, Seyden commented
Don't merge it.. i will push a improvement tommorow

2017-07-19 02:43 UTC, Treeston commented
@Shauren here's our new version after extensive IRC discussion earlier - I feel it's a lot cleaner than what was originally proposed.

PS: Advise on macro naming please, `REGISTER_SPELL_SCRIPT` (to keep with general style of allcaps for macros) vs `RegisterSpellScript` (matches with `PrepareSpellScript`)?

2017-07-19 02:47 UTC, Treeston commented
Rebased for de-conflicting. Also includes example usage (the `spell_item` change).

2017-07-19 22:15 UTC, merged