Core/Misc: Update locales_achievement_reward to simple system
TrinityCore/TrinityCore pull request #19528
Opened 2017-04-30 12:13 UTC by ChazyTheBest

[//]: # (***************************)
[//]: # (** FILL IN THIS TEMPLATE **)
[//]: # (***************************)

**Changes proposed:**

- Update locales_achievement_reward to simple system
- Update achievement_reward to keep consistency

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** None

**Tests performed:** (Does it build, tested in-game, etc.)

- [x] Builds
- [ ] Tested in-game

2017-04-30 12:34 UTC, Shauren requested changes

2017-04-30 12:34 UTC, Shauren commented on src/server/game/Achievements/AchievementMgr.cpp
> -                if (uint32 titleId = reward->titleId[Player::TeamForRace(GetPlayer()->getRace()) == ALLIANCE ? 0 : 1])
stooooooooop right here, `uint32 titleId` is a local variable scoped to this if only, it should not start with uppercase (this comment applies to ALL local variables changed in this PR)

2017-04-30 12:35 UTC, Shauren commented
And keep the inserts, even if the table is empty

2017-04-30 12:35 UTC, Shauren commented on sql/updates/world/3.3.5/2017_xx_xx_xx_world.sql
> +) ENGINE=MYISAM DEFAULT CHARSET=utf8mb4;
I am confused about this change, why?

2017-04-30 13:06 UTC, ChazyTheBest commented on src/server/game/Achievements/AchievementMgr.cpp
> -                if (uint32 titleId = reward->titleId[Player::TeamForRace(GetPlayer()->getRace()) == ALLIANCE ? 0 : 1])
right away

2017-04-30 15:04 UTC, Shauren requested changes

2017-04-30 15:04 UTC, Shauren commented on src/server/game/Achievements/AchievementMgr.cpp
> +            std::string Subject = reward->Subject;
I said everywhere, this means also here

2017-04-30 15:04 UTC, Shauren commented on src/server/game/Achievements/AchievementMgr.cpp
> +            std::string Text = reward->Text;
and here

2017-04-30 15:04 UTC, Shauren commented on src/server/game/Achievements/AchievementMgr.cpp
> +        std::string Subject     = fields[2].GetString();
and here

2017-04-30 15:04 UTC, Shauren commented on src/server/game/Achievements/AchievementMgr.cpp
> +        std::string Text        = fields[3].GetString();
and here

2017-05-02 21:42 UTC, Shauren approved these changes

2017-05-02 21:55 UTC, closed without merging