Get zone/area IDs from vmap data in the liquid update
TrinityCore/TrinityCore pull request #19840
Opened 2017-06-02 17:35 UTC by Treeston

Right now, every call to `GetZoneId`/`GetAreaId` (which seem innocuous enough) actually invokes a full vmaps lookup to find the zone/area id of the object. This is kind of bad.

However, as discussed in #19056, we already do liquid state updates on every server tick for everything, and that's a vmap lookup. And that vmap lookup gives us the zone/area data, we just don't use it.

Now we use it, and save it on the WorldObject, and then use that info to turn `GetZoneId` and `GetAreaId` into simple member accesses.

2017-06-02 17:40 UTC, Treeston commented on src/server/game/Entities/Unit/Unit.cpp
> +    /*if (GetTypeId() == TYPEID_PLAYER)
Heads-up, enable this block if you're reproing to get me some useful info (also, give me a `.gps`).

2017-06-02 17:44 UTC, ccrs commented on src/server/game/Entities/Unit/Unit.cpp
> +    /*if (GetTypeId() == TYPEID_PLAYER)
how about a timer to be able to know how much it takes?

2017-06-02 18:19 UTC, Shauren requested changes

2017-06-02 18:19 UTC, Shauren commented on src/server/game/Entities/Object/Object.cpp
> +    GetMap()->GetZoneAndAreaId(m_zoneId, m_areaId, GetPositionX(), GetPositionY(), GetPositionZ());
Why not `GetBaseMap()`?

2017-06-02 18:19 UTC, Shauren commented on src/server/game/Entities/Object/Object.h
> +        // zone/area ID updated in Unit::Update (only Units can move)
False. GameObjects and DynamicObjects can move when on transport.

2017-06-02 18:19 UTC, Shauren commented on src/server/game/Entities/Unit/Unit.cpp
> +    PositionFullVMapData data;
FullTerrainStatus (naming - matters here because you are returning GridMap data if on flat/nowmo terrain)

2017-06-02 19:09 UTC, nawuko commented
It's somewhat unrealated to this PR, but since you are currently working on it this could an intressting issue to solve: https://github.com/TrinityCore/TrinityCore/issues/19761. I did not look into this issue at all, so i'm not sure if zone/area id is even the root cause here.

2017-06-02 19:49 UTC, Treeston commented
That'd be an issue with base gridmap/vmap data, @nawuko. Not something this PR will (or aims to) address.

2017-06-02 19:55 UTC, Treeston commented on src/server/game/Entities/Object/Object.h
> +        // zone/area ID updated in Unit::Update (only Units can move)
Hm, should we do the call in their `::Update` too? Or are transports always their own area?

2017-06-02 20:02 UTC, nawuko commented
okay, just wanted to be sure its not a problem in the lookup logic. Thanks for looking into that 👍

2017-06-02 20:04 UTC, Treeston commented
I honestly can't say whether it is, @nawuko - though it seems unlikely.

2017-06-02 23:09 UTC, Shauren commented on src/common/Collision/Management/VMapManager2.cpp
> +                        data.hasLiquid = true;
Looks like a good candidate to use Optional

2017-06-02 23:53 UTC, Treeston commented on src/common/Collision/Management/VMapManager2.cpp
> +                        data.hasLiquid = true;
Would make it inconsistent with other vmap methods though.

2017-06-03 00:45 UTC, Treeston commented
@Shauren it is my understanding that any movement of a worldobject while it's added to a map should go through one of the methods calling `->Relocate` in `Map` - is this correct?

2017-06-06 19:56 UTC, Raydor commented
So are these changes good to go? Imo this should get more attention from shauren if you can, please. Dynamic spawn is almost done and its been in proccess for so long, dont delay it more by not getting enough attention to this pr please :(

2017-06-06 20:46 UTC, Shauren requested changes

2017-06-06 20:46 UTC, Shauren commented on src/common/Collision/Management/VMapManager2.cpp
> +                        data.hasLiquid = true;
use it.

2017-06-06 20:46 UTC, Shauren commented on src/common/Collision/Management/VMapManager2.h
> +            virtual void getAreaAndLiquidData(unsigned int mapId, float x, float y, float z, uint8 reqLiquidType, AreaAndLiquidData& data) const override;
virtual keyword not needed

2017-06-06 20:46 UTC, Shauren commented on src/common/Collision/Management/IVMapManager.h
> +    struct TC_COMMON_API AreaAndLiquidData
*_API macro is only needed when your struct/class has methods implemented in .cpp file

2017-06-06 20:46 UTC, Shauren commented on src/server/game/Entities/Object/Object.h
> +        virtual void _ProcessPositionDataChanged(PositionFullTerrainStatus const& data);
don't prefix method names with _

2017-06-06 20:46 UTC, Shauren commented on src/server/game/Entities/Unit/Unit.cpp
> +    /*if (GetTypeId() == TYPEID_PLAYER)
remove debug commented out code

2017-06-06 20:46 UTC, Shauren commented on src/server/game/Maps/Map.cpp
> +        else if (delta > 0.1f)
`Map::getLiquidStatus` checks against -0.1f here

2017-06-06 20:46 UTC, Shauren commented on src/server/game/Maps/Map.cpp
> +    if (gmap)
broken. you are overwriting vmap result. `Map::getLiquidStatus` returns early if vmap result is found

2017-06-06 20:46 UTC, Shauren commented on src/server/game/Maps/Map.h
> +    bool hasFullAreaInfo;
pls, Optional (no has*** members)

2017-06-06 20:46 UTC, Shauren commented on src/server/game/Maps/Map.cpp
> +    if (vmapData.hasAreaInfo && !(z + 2.0f > mapHeight && mapHeight > vmapData.floorZ))
dont bring out the negation before (), especially when you have conditions you can easily change (> to <=)

2017-06-06 20:46 UTC, Shauren commented on src/server/game/Maps/Map.cpp
> +
2 newlines

2017-06-06 20:46 UTC, Shauren commented on src/server/game/Maps/Map.cpp
> +void Map::getFullTerrainStatusForPosition(float x, float y, float z, PositionFullTerrainStatus& data, uint8 reqLiquidType) const
method name? make it start with uppercase (you can leave the one in vmapmanager as-is)

2017-06-06 20:46 UTC, Shauren commented on src/server/game/Entities/Unit/Unit.h
> +        void _ProcessPositionDataChanged(PositionFullTerrainStatus const& data) override;
don't prefix method names with _

2017-06-06 22:52 UTC, Treeston commented
Made most of the refactors you requested. Use of `Optional` needs some significant refactors.

2017-06-06 23:41 UTC, tkrokli commented on src/server/game/Entities/Unit/Unit.h
> +        void ProcessPositionDataChanged(PositionFullTerrainStatus const& data) override;
```
src/server/game/Entities/Unit/Unit.h:2311:80: fatal error: 
      only virtual member functions can be marked 'override'
  ...const& data) override;
                  ^~~~~~~~
```

2017-06-07 01:33 UTC, Treeston commented
Travis build fail is due to outdated boost (it has 1.55, we require [1.59](https://trinitycore.atlassian.net/wiki/display/tc/Windows+Requirements)).

Dropping in place construction (`.emplace`, the Boost 1.56 feature we need) is a pretty significant performance impact, which I'm not overly willing to accept at this point in a core vmap call.

2017-06-07 04:28 UTC, ariel- commented
Ref boost::optional move semantics, not the first time this happens:
https://github.com/TrinityCore/TrinityCore/commit/4c27203c8f36dd2a5df0a4ae69fbdc4c9140b29d#diff-1bfb148491dedaab3a6311bec32f7e7eR172.

Is the performance hit that bad? IIRC POD types were just copied instead moved, you can still use boost::in_place to perform an in-place initialization

2017-06-07 07:52 UTC, Shauren commented
We use boost::in_place everywhere in packets on master branch

2017-06-07 08:05 UTC, Shauren requested changes

2017-06-07 08:05 UTC, Shauren commented on src/server/game/Maps/Map.h
> +    typedef VMAP::AreaAndLiquidData::AreaInfo AreaInfo;
I know this is convenient but don't do this. Don't make all users of Map class also include VMapManager

2017-06-07 11:47 UTC, Shauren commented
https://github.com/TrinityCore/TrinityCore/blob/c5d3dd90bea3889ef5fcd33c9ef0d59d7c544f8a/src/server/game/Handlers/AuthHandler.cpp#L36

This is the zero-overhead pattern that is being used in master branch for building packets - assigning boost::in_place() no-arg version is the same as calling .emplace() with no args
after that you just assign each field

2017-06-07 22:23 UTC, Shauren approved these changes

2017-06-07 22:25 UTC, merged