Scripts/OrderHall: Spawn some Warrior Order Hall NPC's and script some of them
TrinityCore/TrinityCore pull request #19902
Opened 2017-06-17 12:28 UTC by Golrag

**Changes proposed:**

- Add some spawns for warrior order hall & waypoints (those who are spawned before you turn in the quest 'Odyn and the Valarjar')
- Some scripts for npc's
- Script for introduction scene with Odyn
- Script for Danica
- Also enabled SMSG_CANCEL_SCENE

**Target branch(es):** master
-  master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:**
- Tested in game
- Builds

**Known issues and TODO list:** (add/remove lines as needed)
- Waypoints aren't smooth
- Val'kyrs are to slow.
- Timers may be not 100% blizzlike.
- Danica the reclaimer should despawn and a personal one should be escorting you.
- Infinite Scene due to quest objective order bug (no areatrigger spotted so I made the trigger in MoveInLoS).
- Val'kyrs jump is weird.
- Missing emotes for npc's using waypoints.
- Phase condition not working (see SQL file) <-- One I would like to fix if the issue is sql related

Any feedback & help is welcome. I feel like some scripts could have been easier.

2017-06-17 12:30 UTC, Golrag commented on sql/updates/world/master/2017_mm_dd_xx_world.sql
> +DELETE FROM `creature_addon` WHERE `guid`=@CGUID+16;
should be +0

2017-06-17 13:36 UTC, Shauren commented on src/server/scripts/BrokenIsles/zone_orderhall_warrior.cpp
> +                        me->GetMotionMaster()->MoveSmoothPath(1, DanicaPath02, DanicaPath02Size, false, true);
Are you sure about all of your uses of MoveSmoothPath? Is Catmullrom spline flag present in sniff? If not then don't use this function

2017-06-17 14:37 UTC, Golrag commented on src/server/scripts/BrokenIsles/zone_orderhall_warrior.cpp
> +                        me->GetMotionMaster()->MoveSmoothPath(1, DanicaPath02, DanicaPath02Size, false, true);
No it's not, shouldn't the function only set catmullroll for flying creatures only and smoothgroundpath for non-flying units ?
Which function should I use if I want an NPC to move by path ?
Small exception for danica, she is not using catmullroll while flying, but I can't find a function for it except ```me->GetMotionMaster()->MovePath()``` which requires the path to be in the database.

2017-07-10 21:23 UTC, Golrag commented
>Infinite Scene due to quest objective order bug (no areatrigger spotted so I made the trigger in MoveInLoS).

Fixed the order but I still have the infinite scene, will look at it tomorrow or sometime later.

2017-07-31 18:59 UTC, Golrag commented
Noticed a bug, when the val'kyrs reached their last point and DisappearAndDie() is used that's the spot where they will respawn (they shouldn't respawn there).

2018-01-02 16:19 UTC, Golrag commented
Added some more issues to the known issues section of this PR. Some of them I can not fix (in this PR), some I'm not sure about (looking at the move jump of the val'kyrs). And I don't want to go to my sniffs again to find which emotes I need to add to the npc's using db waypoints in the mead hall.

Anything left I need to do for this PR ? :p

2018-01-06 19:21 UTC, Golrag commented
I could use some help to understanding what's wrong with the val'kyrs.. I tried checking their position on Reset, it was good but they did not respawn at that position tho, and with the latest changes they "move down" above the hole and despawn instantly :/
Small note to this: I'm using max visibilty distance for continents (533) to have a better view of the whole order hall (it looks nicer)

2018-01-08 12:46 UTC, Golrag commented
>Sometimes a valkyr spawns in the ground.

https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Entities/Creature/Creature.cpp#L1433-L1442
Don't know why it's there so i'm not touching it, but pretty sure it's the cause :p

2018-03-03 21:09 UTC, Golrag commented
@Shauren anything I will have to change here for your phasing PR ?
Also a bit more off-topic but is there a better way of finding out in which phase a creature/gameobject is in when your smsg_phase_shift lists a lot of phases? As it was really a mess to find these

2018-03-03 21:57 UTC, Shauren commented
Phasing rewrite should not break any existing uses, only introduce new functionality (and fix areatriggers)
As for finding phase id... there really isnt a better way

2018-04-04 01:38 UTC, Aokromes commented
@Golrag https://app.codacy.com/app/TrinityCore/TrinityCore/pullRequest?prid=1497762

2018-04-06 20:16 UTC, Golrag commented
@Aokromes fixed

2018-04-08 20:25 UTC, Shauren requested changes

2018-04-08 20:25 UTC, Shauren commented on src/server/scripts/BrokenIsles/zone_orderhall_warrior.cpp
> +    static uint8 const DanicaPath01Size = 6;
Do the std::extent thing

2018-04-09 16:38 UTC, Golrag commented
@Shauren done
Also I noticed that the first text of the personal spawn could be seen by an other character

2018-05-28 03:56 UTC, Stanwarr commented
Any idea why this isn't on the master branch anymore?

2018-05-28 18:59 UTC, illfated commented
What do you mean? This PR has not been merged yet, so I guess you are referring to something else. 😕 ❔

2018-09-25 17:10 UTC, Golrag commented
Updated to https://github.com/TrinityCore/TrinityCore/commit/2704e3c6f8aba47ed3d753ef06aa3c5b9c196a57

Anything left for me to do with this PR?

2019-06-15 07:45 UTC, Golrag commented
Updated to 6b29c4da76fbdcb55b4a89f485a5cff58c4296b9

Haven't done any tests as I get an error when I try to connect (BLZ51901017). Once that's fixed I will test

2019-06-19 18:46 UTC, Golrag commented
Seems like everything still works like I last tested it

2019-06-19 19:54 UTC, illfated commented
Maybe we could have a comment from Shauren whether he thinks this is OK.

2019-08-25 10:59 UTC, merged