Proper client timeout detection
TrinityCore/TrinityCore pull request #19906
Opened 2017-06-18 00:32 UTC by Treeston

Properly detect client timeout when logged into a character after a configurable time (default 10s) has passed without the client sending any packets.

Fixes issues with crashed clients leaving characters in the world for a very long time (default 15 minutes), as well as edge case exploits involving intentionally pausing client execution for some amount of time.

2017-06-20 11:03 UTC, jackpoz commented
10s might be quite low, like in cases of Windows Updates randomly starting and using the whole bandwidth. Maybe 1 minute is high enough anyway ?

2017-06-20 11:04 UTC, Treeston commented
You'd need to not send _any_ packets for 10s to kill the connection - that's not really something that's gonna happen just because some other program is using bandwidth.

2017-06-20 11:47 UTC, jackpoz commented
It just has to happen once to trigger the disconnect, where now any client can have any kind of network lag spike without causing the disconnect (wifi signal degradation, mobile data connection with low performance, network saturation).
How often is the client sending a packet for sure anyway ? is there any operation on the computer that might trigger the disconnect (map loading on slow computer + other background unrelated processes, etc) ?

2017-06-20 12:03 UTC, Treeston commented
Yes, but a client _shouldn't_ be able to stay connected for prolonged periods of time without data - the WoW client/server model simply isn't designed to handle it gracefully.

Keeping a player connected in these scenarios will make them visually teleport for others (impossible to fight against in PvP), as well as allowing them to clip through locked doors (as they aren't being sent in time), ignore NPC aggro (by moving from one side of the aggro range to the other before the next movement packet is sent) and many many more. It's simply not sustainable while maintaining a consistent gameplay environment (which is why the retail servers would act like this PR does).

2017-06-20 13:33 UTC, Shauren commented
And 10s is too short (thats both CMSG_PING and CMSG_KEEPALIVE are on 30s timers)

2017-06-20 13:34 UTC, Treeston commented
40s then?

2017-06-20 13:36 UTC, Shauren commented
1 minute suggested earlier by jackpoz seems like a good idea to me

2017-06-20 13:41 UTC, Shauren requested changes

2017-06-20 13:41 UTC, Shauren commented on src/server/game/Server/WorldSocket.cpp
> +            if (_worldSession)
This is very bad - you are accessing _worldSession while sessionGuard is not locked

2017-06-20 13:41 UTC, Treeston commented on src/server/game/Server/WorldSocket.cpp
> +            if (_worldSession)
The only modification being made is to a `std::atomic` though. Still an issue?

2017-06-20 14:03 UTC, Shauren commented on src/server/game/Server/WorldSocket.cpp
> +            if (_worldSession)
its the session pointer in WorldSocket that needs to be protected, not any member of WorldSession

2017-06-20 14:03 UTC, jackpoz commented on src/server/game/Server/WorldSocket.cpp
> +            if (_worldSession)
if a race condition can happen here on _worldSession then its value could become NULL after the NULL-check, causing a NULL dereference crash.
if that's the case then it's just a matter of calling sessionGuard.lock() and then sessionGuard.unlock() (or whatever is the syntax of this lock) in the CMSG_KEEP_ALIVE case ?

2017-06-20 14:04 UTC, Treeston commented on src/server/game/Server/WorldSocket.cpp
> +            if (_worldSession)
Makes sense, thanks @Shauren - I'll adjust this to lock/unlock.

2017-06-20 14:20 UTC, Shauren commented on src/server/game/Server/WorldSocket.cpp
> +            if (_worldSession)
@jackpoz the type of sessionGuard is unique_lock (constructed with deferred lock flag), there is no need to unlock it

2017-06-20 21:50 UTC, Treeston commented
@Shauren any other feedback or can this be merged?

2017-06-26 22:21 UTC, Shauren approved these changes

2017-06-26 22:22 UTC, merged