Scripts/Desolace: Implement Gizeltons Caravan
TrinityCore/TrinityCore pull request #20116
Opened 2017-08-06 20:35 UTC by Gerhood

**Changes proposed:**
Implementation for Gizelton's Caravan in Desolace based on work of Cala, Rushor and myself.
There still are some cosmetic flaws e.g. a Kodo not properly following or ambushers not immediatly attacking and maybe some parts of the scripts are not actually needed (I'm leaving this to you guys, don't know much about escort scripting myself). The ambush points + creature texts have been well researched.

**Target branch(es):**

- [x] 3.3.5
- [ ] master

**Issues addressed:**
Closes #1657
Closes #3260

2017-08-07 08:26 UTC, ccrs commented on src/server/scripts/Kalimdor/zone_desolace.cpp
> +        ObjectGuid summons[MAX_CARAVAN_SUMMONS];
try std::vector, tc standard and somewhat cleaner :)

2017-08-07 08:29 UTC, ccrs commented on src/server/scripts/Kalimdor/zone_desolace.cpp
> +                summons[0] = ObjectGuid();
better use objectguid null, check the class; or even nullptr directly

2017-08-23 18:03 UTC, kvipka commented
script should be updated, related with new EscortAI. 
Caravan stoped, when seeing npc-enemy and can't continue movement

2017-09-22 00:13 UTC, tkrokli commented
@Gerhood : could you look into what kvipka said about EscortAI and possible issues with current code?

2017-09-22 14:52 UTC, Gerhood commented
I don't have the time right now. Would be nice if someone that knows about escort AI could look into it, I did not code that part

2017-12-10 17:17 UTC, jackpoz commented
@ccrs could you apply the suggestions you wrote above to the PR itself so then we can merge it ?
anyone up to update it to the new EscortAI system (whatever it is) ?

2018-03-11 20:15 UTC, jackpoz requested changes

2018-03-11 20:15 UTC, jackpoz commented on src/server/scripts/Kalimdor/zone_desolace.cpp
> +            memset(&summons, 0, sizeof(summons));
never memset, just don't

2018-03-11 20:15 UTC, jackpoz commented on src/server/scripts/Kalimdor/zone_desolace.cpp
> +            headNorth = true;
this field must be initialized in the constructor too to avoid static analysis issues

2018-03-11 20:15 UTC, jackpoz commented on src/server/scripts/Kalimdor/zone_desolace.cpp
> +            _playerGUID = ObjectGuid();
there should be other ways to reset the value of _playerGUID to an empty guid

2018-03-11 20:15 UTC, jackpoz commented on src/server/scripts/Kalimdor/zone_desolace.cpp
> +            if (field == 1 && data == 1)
please don't use magic numbers but use enums or defines

2019-04-08 16:59 UTC, closed without merging

2019-04-08 16:59 UTC, jackpoz commented
Closing this PR as it seems abandoned. Feel free to ask here to reopen it if anyone would like to work on it.