[3.3.5] Core/Movement: Pets go for the back unless being the victim
TrinityCore/TrinityCore pull request #20128
Opened 2017-08-09 14:17 UTC by necropola

This restores the pet's original behavior to not **always** attack from the front and get cleaved down.
* Target branch: 3.3.5
* Issues addressed: Closes #19925 
* Tests performed:
  * build success
  * tested/verified in game

I was neither able to pinpoint the commit that broke it nor do I think I found the best place/way to fix it, but it's very effective and should make warlocks and hunters happy again.

2017-08-10 17:13 UTC, Shauren submitted a review, later dismissed
Seems legit?

2017-08-10 17:58 UTC, necropola commented
I mean it's clearly not the right/best place to adjust the`` _angle`` value. But seeing that the code already adjusts ``offset`` and ``size`` for the *pet runs to owner* case, I thought "what the heck, why not fix it here!?"

2017-08-10 18:58 UTC, ccrs approved these changes
If you've tested it... 👍

2017-08-10 19:30 UTC, necropola commented
I'm running around with a warlock and a hunter for some time now and it's clearly an improvement. I haven't seen any *pet dance* regression (pet tries to reach the target's back while target tries to attack from the front) and the pet does no longer actively go for the front when it's not the target.

It's still not 100% what it used to be. In older versions of TC-3.3.5 the pet would just approach the target in a straight line and attack from there. Like it still does when using _Charge_ (which uses a different ``MovementGenerator``).

2017-08-16 20:51 UTC, necropola commented
Anything I can do to increase the likelihood that this gets merged into TC-3.3.5?

2017-08-16 21:16 UTC, tkrokli commented
Not really, it will be approved and merged when enough developers have had the chance to review it.

2017-08-20 16:24 UTC, Shauren commented
Alright, looks like I found a possible problem with it
By manipulating `_angle` you prevent this code from triggering when reaching target https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp#L92

2017-08-21 15:06 UTC, necropola commented
I understand that ``_angle`` is used to calculate a point at ``offset`` distance from the target relative to where the target is currently facing, i. e. if ``_angle == 0``  this point is in front of the target and if ``_angle == M_PI`` it's in its back.
Currently the ``TargetedMovementGenerator`` seems to be used with ``_angle == M_PI/2`` for the case that the pet returns to it's owner, and with ``_angle == 0`` to approach a hostile target which has the undesired effect of going for the front, even when the target is after someone else (the tank).
My patch simply catches the latter case and prevents the pet from going suicidal.

2017-08-21 15:13 UTC, ccrs commented
Thing is the pet must face the creature when reaches the target (thats what the section shauren linked does). The pet will face its target visually (clientside) because it is targeting it (unit::SetTarget) and client makes the unit always face its target.

But serverside the orientation will remaing incorrect, maybe being autocorrected for a second if it casts, but returning to old (incorrect) after the cast. This can break many things like autoattacks or spells that require facing.

2017-08-21 15:38 UTC, necropola commented
Could we change it so that the pet (server-side) faces a hostile target even when in its back?
In older versions of TC the pet would simply approach in a straight line like it still does when using it's _Charge_ ability  and then attack from the point where it reached the target (ignoring the target's orientation by obviously using a different MovementGenerator, maybe Point?).
At some point along the line (when?) it has probably been changed to use the ``TargetedMovementGenerator`` and thereby introduced pet suicide mode ...

2017-11-24 18:43 UTC, Jildor commented
any news?

2017-11-24 18:54 UTC, tkrokli commented
If I have understood the conversation correctly, we are still waiting for a solution to the issue Shauren pointed out in https://github.com/TrinityCore/TrinityCore/pull/20128#issuecomment-323595682 .

2018-01-04 18:56 UTC, Keader commented
Any news on this @necropola ?

2018-01-12 00:25 UTC, chaodhib commented
Please don't solve this through the MoveGen. Like you said, it's not the best place to put that code. And the reason pet logic is already in the MoveGen is because of the laziness of past contributors. Let's not do the same.

PS: I'm in the process of cleaning up that MoveGen.

2018-01-12 00:30 UTC, chaodhib requested changes
Please don't put that logic in the MoveGen. Like you already pointed it out, it's not a suitable place for pet logic (or any non movement logic really).

The reason there already is pet logic there is because of the laziness from past contributors. Let's not keep doing the same thing.

PS: I'm in the process of refactoring the MoveGen to clean it up from this kind of stuff. 
PS2: I'm also in the process of improving the MoveGen. The overhead of complexity created by these unnecessary coupling between the different parts of the core are slowing down my progress significantly.
PS3: Nice work nonetheless. I know contributing to the project for the first time is hard, because of the size and the complexity. Keep it up!

2018-01-12 13:05 UTC, tkrokli commented
I do hope @necropola is still alive and around to receive the feedback.
Would be sad to see useful & practical feedback go to waste.

2018-04-08 20:32 UTC, Shauren commented
Replaced by 2a84562dc85516f432bb1e5de9add23c28b26ce4

2018-04-08 20:32 UTC, closed without merging