Core/Transmog: Add TransmogSets
TrinityCore/TrinityCore pull request #20135
Opened 2017-08-11 09:52 UTC by Golrag

**Changes proposed:**

-  Add Achievement for transmog set completion
-  SPELL_EFFECT_LEARN_TRANSMOG_SET

**Target branch(es):**
- master

**Issues addressed:** Closes #20133

**Tests performed:**
- Tested in game
- Compiles

**Known issues and TODO list:** (add/remove lines as needed)
- I really don't like ```IsSetCompleted``` :(

2017-08-13 13:09 UTC, Shoxxo commented
Tested ...

[Working](https://image.prntscr.com/image/33FDOv_KSZSeDM17qVPiRA.png)

2017-08-13 13:14 UTC, Golrag commented
Oh I am talking about the tab 'Sets' in your appearances collection not about the transmogging to a set.
I could take a look at that tho and see if I it fits this PR

2017-08-13 13:19 UTC, Shoxxo commented
Yes i know and as you can see, it is avaible or i am wrong?

2017-08-13 13:52 UTC, Golrag commented
Yea it's available :)

2017-08-20 22:03 UTC, Shauren requested changes

2017-08-20 22:03 UTC, Shauren commented on src/server/game/Entities/Player/CollectionMgr.cpp
> +bool CollectionMgr::IsSetCompleted(uint32 transmogSetId) const
https://gist.github.com/Shauren/6929981f075b8a40b6c822a209fd518a
Improved version with no temporary containers (this is what the client does too btw with ItemTransmogrificationSlots)

2017-08-20 22:03 UTC, Shauren commented on src/server/game/DataStores/DB2Stores.cpp
> +std::vector<TransmogSetEntry const*> const* DB2Manager::GetTransmogSetsForItemModifiedAppearance(uint32 itemModID) const
Please use full name for argument (itemModifiedAppearanceId)

2017-08-21 08:50 UTC, Golrag commented on src/server/game/Entities/Player/CollectionMgr.cpp
> +        int32 transmogSlot = ItemTransmogrificationSlots[item->InventoryType];
@Shauren shouldn't we check if item is null or is it guaranteed to exist ?

2017-08-21 08:54 UTC, Golrag commented
I could take a look at CRITERIA_TYPE_APPEARANCE_UNLOCKED_BY_SLOT in this PR btw maybe it fits :p

2017-08-21 11:26 UTC, Shauren commented on src/server/game/Entities/Player/CollectionMgr.cpp
> +        int32 transmogSlot = ItemTransmogrificationSlots[item->InventoryType];
You should check it - i didn't do complete checking there

2017-08-21 11:28 UTC, Shauren commented on src/server/game/Entities/Item/Item.h
> +int32 const ItemTransmogrificationSlots[MAX_INVTYPE] =
This change is bad, all you had to do here was write a declaration - `extern int32 const ItemTransmogrificationSlots[MAX_INVTYPE]`

2017-08-23 09:32 UTC, Golrag commented
Added CRITERIA_TYPE_APPEARANCE_UNLOCKED_BY_SLOT but somehow progress is not shown just like with issue #18448

2017-08-24 18:39 UTC, closed without merging