Core/SAI: implement SMART_ACTION_EXIT_VEHICLE and fix orientation in _ExitVehicle().
TrinityCore/TrinityCore pull request #20447
Opened 2017-09-26 16:44 UTC by Wyreth

**Changes proposed:**

-  Implement SMART_ACTION_EXIT_VEHICLE, allowing to choose the exit position for passenger by using SMART_TARGET_POSITION, or choose which entity should eject vehicle, using other target types.

This is needed for cases where the only vehicle aura applied is [Ride Vehicle Hardcoded](http://www.wowhead.com/spell=46598) (unapplying it doesn't dismount entity) and where the exit position is not default (example: [this quest](https://youtu.be/eGsEu1rPcOU?t=38).

- Fix orientation used in _ExitVehicle(). Previously it was using the original vehicle's orientation instead of the one set in the Position parameter.

**Target branch(es):**

- [x] 3.3.5

**Tests performed:** works fine.

2017-09-26 17:02 UTC, Killyana commented
When a player or any npc exit a vehicle it will execute a little jump to a position relative to the vehicle, I'm pretty sure this information can be found in DBC file,s related to vehicle_id and seat_id.

2017-09-26 17:06 UTC, Wyreth commented
Right now it uses the current vehicle's position, [here](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L13809).

I'll see if I can find something in DBC.

2017-09-26 17:15 UTC, Killyana commented
You can find here the enter/exit information https://wowdev.wiki/DB/VehicleSeat

2017-09-26 17:32 UTC, Wyreth commented
There's information about arc height and duration, but I'm not sure that can be used to calculate a position. It's above my level either way, so if someone can shed more light it'd be nice :P

2017-09-26 17:35 UTC, Killyana commented
There's more to do for vehicles like: https://github.com/TrinityCore/TrinityCore/issues/15224

2017-09-28 11:06 UTC, Wyreth commented
To add some context to this, this is a script for [a quest](http://www.wowhead.com/quest=11661) that requires a solution like this one:

```sql
UPDATE `event_scripts` SET `datalong`=27939, `datalong2`=300000, `x`=2839.433, `y`=7150.816, `z`=-0.4185546, `o`=4.246748 WHERE `id`=16889;

UPDATE `creature_template` SET `unit_flags`=33554432, `VehicleId`=311, `AIName`="SmartAI", `InhabitType`=4 WHERE `entry`=27939;
UPDATE `creature_template` SET `unit_flags`=768, `AIName`="SmartAI", `InhabitType`=1 WHERE `entry` IN (32576, 32577, 32578, 32579, 32580);
UPDATE `creature_template` SET `flags_extra`=`flags_extra`|64 WHERE `entry` IN (32577, 32578, 32579, 32580);

DELETE FROM `npc_spellclick_spells` WHERE `npc_entry`=27939;
INSERT INTO `npc_spellclick_spells` (`npc_entry`, `spell_id`, `cast_flags`, `user_type`) VALUES
(27939, 46598, 1, 0);

DELETE FROM `smart_scripts` WHERE `entryorguid`=27939;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (32576, 3257600, 3257601, 32578, 3257800, 32577, 3257700, 32580, 3258000, 32579, 3257900);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(27939, 0, 0, 1, 11, 0, 100, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "The Helmsman's Ship - On Reset - Set Active On"),
(27939, 0, 1, 0, 61, 0, 100, 0, 0, 0, 0, 0, 53, 1, 27939, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "The Helmsman's Ship - On Reset - Start Waypoint"),
(27939, 0, 2, 3, 40, 0, 100, 0, 3, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 19, 32576, 0, 0, 0, 0, 0, 0, "The Helmsman's Ship - On WP 3 Reached - Set Data 1 1 (Orabus the Helmsman)"),
(27939, 0, 3, 0, 61, 0, 100, 0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "The Helmsman's Ship - On WP 3 Reached - Set Active Off"),
(32576, 0, 0, 0, 11, 0, 100, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Orabus the Helmsman - On Respawn - Say Line 0"),
(32576, 0, 1, 0, 38, 0, 100, 0, 1, 1, 0, 0, 80, 3257600, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Orabus the Helmsman - On Data 1 1 Set - Run Script"),
(32576, 0, 2, 0, 38, 0, 100, 0, 2, 2, 0, 0, 80, 3257601, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Orabus the Helmsman - On Data 2 2 Set - Run Script"),
(3257600, 9, 0, 0, 0, 0, 100, 0, 3000, 3000, 0, 0, 45, 1, 1, 0, 0, 0, 0, 19, 32578, 0, 0, 0, 0, 0, 0, "Orabus the Helmsman - On Script - Set Data 1 1 (Kvaldir Crewman)"),
(3257601, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Orabus the Helmsman - On Script - Say Line 1"),
(3257601, 9, 1, 0, 0, 0, 100, 0, 1000, 1000, 0, 0, 16, 1, 0, 0, 0, 0, 0, 8, 0, 0, 0, 2807.858, 7038.571, 7.075813,  4.73481, "Orabus the Helmsman - On Script - Exit Vehicle"),
(3257601, 9, 2, 0, 0, 0, 100, 0, 0, 0, 0, 0, 19, 256, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Orabus the Helmsman - On Script - Remove Immune To PC"),
(3257601, 9, 3, 0, 0, 0, 100, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Orabus the Helmsman - On Script - Set ReactState Aggressive"),
(3257601, 9, 4, 0, 0, 0, 100, 0, 0, 0, 0, 0, 53, 1, 32578, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, "Orabus the Helmsman - On Script - Start Waypoint"),
(32578, 0, 0, 0, 38, 0, 100, 0, 1, 1, 0, 0, 80, 3257800, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Data 1 1 Set - Run Script"),
(32578, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 19, 32577, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Death - Set Data 1 1 (Kvaldir Crewman)"),
(3257800, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 19, 32576, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Say Line 2 (Orabus the Helmsman)"),
(3257800, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Say Line 0"),
(3257800, 9, 2, 0, 0, 0, 100, 0, 1000, 1000, 0, 0, 16, 1, 0, 0, 0, 0, 0, 8, 0, 0, 0, 2803.729, 7046.516, 5.362013, 4.73481, "Kvaldir Crewman - On Script - Exit Vehicle"),
(3257800, 9, 3, 0, 0, 0, 100, 0, 0, 0, 0, 0, 19, 256, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Remove Immune To PC"),
(3257800, 9, 4, 0, 0, 0, 100, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Set ReactState Aggressive"),
(3257800, 9, 5, 0, 0, 0, 100, 0, 1500, 1500, 0, 0, 5, 15, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Emote 'Roar'"),
(3257800, 9, 6, 0, 0, 0, 100, 0, 0, 0, 0, 0, 53, 1, 32578, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Start Waypoint"),
(32577, 0, 0, 0, 38, 0, 100, 0, 1, 1, 0, 0, 80, 3257700, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Data 1 1 Set - Run Script"),
(32577, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 19, 32580, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Death - Set Data 1 1 (Kvaldir Crewman)"),
(3257700, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 19, 32576, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Say Line 2 (Orabus the Helmsman)"),
(3257700, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Say Line 0"),
(3257700, 9, 2, 0, 0, 0, 100, 0, 1000, 1000, 0, 0, 16, 1, 0, 0, 0, 0, 0, 8, 0, 0, 0, 2801.168, 7046.468, 5.362013, 4.73481, "Kvaldir Crewman - On Script - Exit Vehicle"),
(3257700, 9, 3, 0, 0, 0, 100, 0, 0, 0, 0, 0, 19, 256, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Remove Immune To PC"),
(3257700, 9, 4, 0, 0, 0, 100, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Set ReactState Aggressive"),
(3257700, 9, 5, 0, 0, 0, 100, 0, 1500, 1500, 0, 0, 5, 15, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Emote 'Roar'"),
(3257700, 9, 6, 0, 0, 0, 100, 0, 0, 0, 0, 0, 53, 1, 32578, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Start Waypoint"),
(32580, 0, 0, 0, 38, 0, 100, 0, 1, 1, 0, 0, 80, 3258000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Data 1 1 Set - Run Script"),
(32580, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 45, 1, 1, 0, 0, 0, 0, 19, 32579, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Death - Set Data 1 1 (Kvaldir Crewman)"),
(3258000, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 19, 32576, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Say Line 2 (Orabus the Helmsman)"),
(3258000, 9, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Say Line 0"),
(3258000, 9, 2, 0, 0, 0, 100, 0, 1000, 1000, 0, 0, 16, 1, 0, 0, 0, 0, 0, 8, 0, 0, 0, 2803.319, 7051.411, 5.362913, 4.73481, "Kvaldir Crewman - On Script - Exit Vehicle"),
(3258000, 9, 3, 0, 0, 0, 100, 0, 0, 0, 0, 0, 19, 256, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Remove Immune To PC"),
(3258000, 9, 4, 0, 0, 0, 100, 0, 0, 0, 0, 0, 8, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Set ReactState Aggressive"),
(3258000, 9, 5, 0, 0, 0, 100, 0, 1500, 1500, 0, 0, 5, 15, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Emote 'Roar'"),
(3258000, 9, 6, 0, 0, 0, 100, 0, 0, 0, 0, 0, 53, 1, 32578, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Start Waypoint"),
(32579, 0, 0, 0, 38, 0, 100, 0, 1, 1, 0, 0, 80, 3257900, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Data 1 1 Set - Run Script"),
(32579, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 45, 2, 2, 0, 0, 0, 0, 19, 32576, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Death - Set Data 2 2 (Orabus the Helmsman)"),
(3257900, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 19, 32576, 0, 0, 0, 0, 0, 0, "Kvaldir Crewman - On Script - Say Line 2  [...]

2017-09-30 09:13 UTC, joschiwald requested changes

2017-09-30 09:13 UTC, joschiwald commented on src/server/game/AI/SmartScripts/SmartScript.cpp
> +                    creature->_ExitVehicle(&_exitPosition);
don't use Unit::_ExitVehicle, it will bypass the spell aura system

2017-09-30 09:13 UTC, joschiwald commented on src/server/game/Entities/Unit/Unit.cpp
> +    init.SetFacing(pos.GetOrientation());
this causes passengers exits vehicle with vehicles orientation

2017-09-30 09:13 UTC, joschiwald commented on src/server/game/AI/SmartScripts/SmartScript.cpp
> +                    creature->_ExitVehicle(&_exitPosition);
the only way to solve this properly is to resolve the todo in Unit::ExitVehicle

2018-05-09 12:10 UTC, closed without merging