Core/MotionMaster: Add MovePoint with facing
TrinityCore/TrinityCore pull request #20779
Opened 2017-11-02 19:28 UTC by Kittnz

Thanks to Riztazz

**Changes proposed:**

-  Core/MotionMaster: Add MovePoint with facing

**Target branch(es):** 3.3.5

- [x] 3.3.5

**Tests performed:** (Does it build, tested in-game, etc.)
Works as is.

2017-11-02 21:26 UTC, Keader commented on src/server/game/Movement/MotionMaster.h
> +        void MovePoint(uint32 id, Position const& pos, bool generatePath, bool _setFinalFacing);
setFinalFacing

2017-11-02 21:28 UTC, Keader commented on src/server/game/Movement/MotionMaster.cpp
> +void MotionMaster::MovePoint(uint32 id, Position const& pos, bool generatePath = true, bool _setFinalFacing = false)
setFinalFacing

2017-11-02 21:43 UTC, tkrokli commented
About the title edit: I simply picked the directory name 1 level up
(which also is the common denominator for all files in this PR).

2017-11-02 23:41 UTC, Keader approved these changes
Looks good to me

2017-11-03 08:14 UTC, ccrs commented
doesnt feel right.. everything should be just handled with Position and update all the x,y,z uses..
stall this for the weekend, maybe I can perform the changes

2017-11-03 08:42 UTC, Riztazz commented
Afaik shauren didnt want to use NAN to determine if there is orientation set, because by default orient is set to some value, 0.0f i think? Even tho 0.0f is still valid orient ;p

2017-11-09 02:27 UTC, Keader commented
Maybe has some useful discussion about it [here](https://github.com/TrinityCore/TrinityCore/pull/18893)

2017-11-09 09:00 UTC, Shauren commented
#include "Optional.h"

Use that instead of float+bool arg pair (dont shove it into Position)

2017-12-14 09:19 UTC, jackpoz commented
@Kittnz can you use the suggestion above about using Optional ? Then this PR could be merged

2017-12-14 09:26 UTC, Kittnz commented
Ill look into it.

2017-12-17 19:12 UTC, Naios approved these changes

2017-12-17 19:14 UTC, Naios requested changes
As said before, the optional part is missing

2017-12-22 20:18 UTC, jackpoz commented on src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp
> +        init.SetFacing(*_orient);
are these 2 lines correct ?

2017-12-22 20:19 UTC, jackpoz commented
@Naios could you check if it's ok now ?

2017-12-22 22:19 UTC, Shauren requested changes
No, Optional was meant to propagate in api back to MotionMaster::MovePoint, with the overload that has Position argument not being added

2017-12-23 03:58 UTC, Naios commented on src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp
> +        init.SetFacing(*_orient);
Yes, this should be correct

2017-12-23 04:00 UTC, Naios approved these changes
Optional used correctly instead of 0 float,
Please address Shaurens comment before merging please

2017-12-23 12:30 UTC, jackpoz commented
@Shauren better now ? (I actually deleted the overload before reading your comment since it didn't make sense to add a new one to me either)

2017-12-23 12:48 UTC, Shauren commented
`Optional<float> = nullptr` only works because its we defined `BOOST_OPTIONAL_USE_OLD_DEFINITION_OF_NONE` to work around msvc linker errors, you should default construct it with `Optional<float> = {}`

2017-12-23 15:08 UTC, Shauren approved these changes

2017-12-23 15:12 UTC, merged