Core/Packets: Implement GAMEOBJECT_TYPE_UI_LINK
TrinityCore/TrinityCore pull request #20919
Opened 2017-11-17 12:13 UTC by DoctorKraft

**Changes proposed:**

-  Implement GAMEOBJECT_TYPE_UI_LINK for gob with type 48
Get UI for Obliterium Forge or Hero's Call Board with Adventure Journal

**Target branch(es):**

- [X] master

**Issues addressed:** Closes #20913 

**Tests performed:** Build & tested in-game

**Known issues and TODO list:**

- [ ] Radius not implemented (if anyone have an idea)

2017-11-17 22:33 UTC, Shauren requested changes
And radius - isnt that simply the interaction distance limit?

2017-11-17 22:33 UTC, Shauren commented on src/server/game/Server/Packets/GameObjectPackets.h
> +            uint32 UILink = 0;
This one should be int32

2017-11-17 22:33 UTC, Shauren commented on src/server/game/Server/Packets/GameObjectPackets.cpp
> +    _worldPacket << UILink;
always write the type for ints/floats (`_worldPacket << int32(UILink);`)

2017-11-17 22:45 UTC, DoctorKraft commented
@Shauren yeah i think same, but i don't have any idea where to implement this. It's in GridNotifier?

2017-11-18 19:47 UTC, joschiwald commented
take a look at GameObject::GetInteractionDistance

2017-11-23 08:39 UTC, DoctorKraft commented
I have tried one but not working. For example i set 50 yards, when icon for interact are grayed you can do everything it's always same range (only when icon are not grayed). The structure contains also a spellfocus...

2017-12-10 15:58 UTC, joschiwald commented
it looks like that all gameobjects have the default interaction range

2017-12-10 19:30 UTC, joschiwald commented
merging in the next days

2017-12-15 19:37 UTC, Killyana commented
Gobs interaction range will be fixed by https://github.com/TrinityCore/TrinityCore/pull/18917

2018-01-04 00:15 UTC, merged