[bfa]  CreatureFamily struct update
TrinityCore/TrinityCore pull request #22592
Opened 2018-10-08 16:22 UTC by Palabola

**Changes proposed:**

-  New BFA dbc values

**Target branch(es):** 3.3.5/master

- [x] master

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

2018-10-08 16:24 UTC, Shauren requested changes
You must change .Get*** function used to read that field when parsing all involved QueryResults

2018-10-08 16:25 UTC, Shauren requested changes

2018-10-08 17:53 UTC, illfated commented
BTW, please add a LineFeed or `<Enter>` at the end of `sql/updates/world/master/2018_10_08_00_world.sql` (missing NewLine).

2018-10-09 19:40 UTC, illfated commented on src/server/game/Miscellaneous/SharedDefines.h
> +    CREATURE_FAMILY_ABONIATION          = 155,
Good point. `CREATURE_FAMILY_ABOMINATION` should be the correct name, unless there is a sniff sample showing that Blizzard have actually added this typo in their servers.
Especially if this is a new enum name, using a correct spelling will be more practical.
(I tried searching for `CREATURE_FAMILY_ABONIATION` as well as `CREATURE_FAMILY_ABOMINATION` in both master & 3.3.5, but could not find it being used before.)

2018-10-09 20:09 UTC, Palabola commented on src/server/game/Miscellaneous/SharedDefines.h
> +    CREATURE_FAMILY_ABONIATION          = 155,
Typo

2018-10-11 11:34 UTC, arazi47 commented on src/server/game/Miscellaneous/SharedDefines.h
> +    CREATURE_FAMILY_FEATHEMANE          = 160,
CREATURE_FAMILY_FEATHERMANE.

2018-10-11 17:57 UTC, illfated commented on src/server/game/Server/Packets/CalendarPackets.cpp
> +}
from travis-ci :
```cpp
src/server/game/Server/Packets/CalendarPackets.cpp:159:1:
 fatal error: control reaches end of non-void function [-Wreturn-type]
}
^
```

2018-10-11 17:59 UTC, illfated commented on src/server/game/Server/Protocol/Opcodes.cpp
> +    DEFINE_SERVER_OPCODE_HANDLER(SMSG_ACCOUNT_MOUNT_UPDATE,                    XXXXXXXXXXXX,        CONNECTION_TYPE_INSTANCE);
from travis-ci :
```cpp
src/server/game/Server/Protocol/Opcodes.cpp:877:80:
 fatal error: use of undeclared identifier 'XXXXXXXXXXXX'
    DEFINE_SERVER_OPCODE_HANDLER(SMSG_ACCOUNT_MOUNT_UPDATE,                    XXXXXXXXXXXX,        CONNECTION_TYPE_INSTANCE);
                                                                               ^
```

2018-10-15 19:24 UTC, closed without merging