Core/Misc: don't allow players to use/activate/loot non-allowed gameobjects while under the effect of a damage immunity aura
TrinityCore/TrinityCore pull request #23319
Opened 2019-05-26 19:57 UTC by Wyrserth

**Changes proposed:**

- Set UNIT_FLAG_HAS_IMMUNITY_AURA (previously UNIT_FLAG_UNK_31) on units affected by damage immunity auras and prevents them from interacting with certain gameobjects while said aura is active.
This flag disables the client from interacting with certain gameobjects while it's set.

- Also add some anti-cheating measures.

- Remove flag usage from some boss scripts, now it's set and unset appropriately when the relative auras are applied/removed.

Prevents, for example, Paladins from looting chests (like the Gurubashi Arena one) while bubbled.

Thanks to xvwyh for detailed post about this issue [here](https://github.com/TrinityCore/TrinityCore/pull/23207#discussion_r279888053).

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Tests performed:** works fine.

2019-05-26 20:07 UTC, Shauren requested changes

2019-05-26 20:07 UTC, Shauren commented on src/server/game/Entities/Unit/UnitDefines.h
> +    UNIT_FLAG_HAS_IMMUNITY_AURA     = 0x80000000,
Not researched this on later versions but it might be used for more things than just auras, better to simply call it "IMMUNE"

2019-05-26 20:07 UTC, Shauren commented on src/server/game/Spells/Auras/SpellAuraEffects.cpp
> +    else
Remove case needs the typical `if (!target->HasAuraType(...))` check found in all aura handlers that set/remove flags

2019-05-26 20:15 UTC, Shauren requested changes

2019-05-26 20:15 UTC, Shauren commented on src/server/game/Entities/GameObject/GameObjectData.h
> +            default: return true;
GAMEOBJECT_TYPE_CHEST must return true in all cases,
default must return false

2019-05-26 20:18 UTC, Killyana commented on src/server/game/Entities/GameObject/GameObjectData.h
> +            case GAMEOBJECT_TYPE_FLAGDROP:   return flagdrop.noDamageImmune != 0;
Add GAMEOBJECT_TYPE_CHEST when data22: Damage Immune =0

2019-05-26 20:28 UTC, Wyrserth commented
Done, thanks!

@Killyana I thought that only applies to newer expansions, data for chests stops being relevant past 17 and in 3.3.5a they're all set to 0. Might have to change that when/if it's ported to master.

2019-05-26 20:34 UTC, Killyana commented
Chests in master have data22: Damage Immune and all have data22=0
Chest were not usable under immunity in all expansions.

2019-05-28 06:04 UTC, jackpoz commented
@Shauren anything more or can this be merged ?

2019-05-30 12:41 UTC, jackpoz commented
@Wyrserth is this ready to be merged ?

2019-05-30 16:08 UTC, Wyrserth commented
@jackpoz yeah there's nothing left to do that I know of.

2019-05-30 18:07 UTC, merged

2019-05-30 18:07 UTC, jackpoz commented
Thanks for the PR :)