Core/Misc: More coding standards
TrinityCore/TrinityCore pull request #23519
Opened 2019-06-26 08:29 UTC by Aokromes

**Changes proposed:**

-  remove more "  "
-  align things where they are aligned and it's clear it's intended
-  

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

2019-06-26 09:14 UTC, Shauren commented
You mean more of the git blame headache

2019-06-26 12:40 UTC, jackpoz commented on src/server/game/Battlegrounds/ArenaTeam.h
>          int32  WonAgainst(uint32 Own_MMRating, uint32 Opponent_MMRating, int32& rating_change);
I would fix "int32  " and "float  " and whatever "return_type  " is there too while at it

2019-06-28 08:34 UTC, jackpoz commented on src/server/game/Groups/Group.h
> +        uint8  itemCount;
don't add new spaces

2019-06-28 08:34 UTC, jackpoz commented on src/server/game/Groups/Group.h
> + static void ConvertLeaderInstancesToGroup(Player* player, Group* group, bool switchLeader);
move static aligned to other rows void

2019-06-28 08:34 UTC, jackpoz commented on src/server/game/Guilds/Guild.h
> +        int8  GetRights() const { return rights; }
don't add new spaces

2019-06-28 08:35 UTC, jackpoz commented on src/server/game/Loot/LootMgr.h
> +    bool   needs_quest;                                    // quest drop (quest is required for item to drop)
remove spaces here too

2019-06-28 08:35 UTC, jackpoz commented on src/server/game/Movement/Spline/MoveSplineInitArgs.h
> +        float  angle;
remove spaces here too

2019-06-28 08:35 UTC, jackpoz commented on src/server/game/Movement/Spline/MoveSplineInitArgs.h
> +        int32  path_Idx_offset;
don't add new spaces

2019-06-28 08:36 UTC, jackpoz commented
This PR adds more spaces than the ones it removes. Please just remove them all, we are not building a newspaper, unaligned code is alright.

2019-06-28 09:12 UTC, jackpoz commented on src/server/game/Groups/GroupMgr.h
> +    void Update(uint32 diff);
where did this come from ?

2019-06-28 09:14 UTC, Aokromes commented on src/server/game/Groups/GroupMgr.h
> +    void Update(uint32 diff);
update local branch with github xd

2019-07-01 07:16 UTC, jackpoz requested changes
Some new spaces have been added, please remove them.

2019-07-01 07:16 UTC, jackpoz commented on src/server/game/Entities/Unit/Unit.h
> +        bool   HasAuraState(AuraStateType flag, SpellInfo const* spellProto = nullptr, Unit const* Caster = nullptr) const;
remove the new space

2019-07-01 07:16 UTC, jackpoz commented on src/server/game/Entities/Unit/Unit.h
> +        bool   IsMagnet() const;
remove the new space

2019-07-01 07:16 UTC, jackpoz commented on src/server/game/Entities/Unit/Unit.h
> +        Unit*  GetMeleeHitRedirectTarget(Unit* victim, SpellInfo const* spellInfo = nullptr);
remove the new space

2019-07-01 07:16 UTC, jackpoz commented on src/server/game/Entities/Unit/Unit.h
> +        float  SpellHealingPctDone(Unit* victim, SpellInfo const* spellProto) const;
remove the new space

2019-07-01 07:16 UTC, jackpoz commented on src/server/game/Entities/Unit/Unit.h
> +        bool   HasUnitMovementFlag(uint32 f) const { return (m_movementInfo.flags & f) == f; }
remove the new space

2019-07-01 07:16 UTC, jackpoz commented on src/server/game/Groups/GroupMgr.h
> +    void Update(uint32 diff);
This still needs to be fixed

2019-07-01 07:16 UTC, jackpoz commented on src/server/game/Loot/LootMgr.h
> +    bool needs_quest;                                    // quest drop (quest is required for item to drop)
should you align the comments ?

2019-07-01 07:16 UTC, jackpoz commented on src/server/game/Quests/QuestDef.h
> +        float  GetRewHonorMultiplier() const { return _rewardKillHonor; }
remove the new space

2019-07-01 09:58 UTC, jackpoz commented on src/server/game/Chat/Chat.h
> +        void extractOptFirstArg(char* args, char** arg1, char** arg2);
could you fix the alignment of the whole ChatHandler class while at it ?

2019-07-01 09:59 UTC, jackpoz commented on src/server/game/Entities/Object/Object.h
> +        void AddFlag(FLAG_TYPE flag) { m_flags |= (1 << flag); }
Could you fix the alignment of the whole FlaggedValuesArray32 class while at it ?

2019-07-01 10:17 UTC, jackpoz commented
I would like to have 1 script that checks all the source code by itself and optionally fixes it automatically

2019-07-01 11:06 UTC, Aokromes commented
rgrep "\b  \b" src/* |grep -v "//"
can help to find double spaces on rows, ignoring the ones containing //

2019-07-07 18:58 UTC, jackpoz commented on src/server/game/Battlegrounds/ArenaTeam.h
>          MemberList     Members;
please remove whitespace from all the members of this class, starting from https://github.com/TrinityCore/TrinityCore/pull/23519/files#diff-d7bafcb23b1ab0c2d6dffc8cd7a74d87R116

2019-07-08 10:51 UTC, merged