- updated argon2 to latest release from https://github.com/P-H-C/phc-…
TrinityCore/TrinityCore pull request #23893
Opened 2019-10-28 12:57 UTC by damaex

**Changes proposed:**

- updated argon2 for arm/aarch64 support

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Issues addressed:** Closes #  (insert issue tracker number)

**Tests performed:** (Does it build, tested in-game, etc.)
- [x] build
- [x] in game (on raspberry pi 4)

**Known issues and TODO list:** (add/remove lines as needed)

2019-10-31 07:10 UTC, jackpoz commented
Please update https://github.com/TrinityCore/TrinityCore/blob/33aa5d2e39af867e85c14a2c412a23d08c51cc25/dep/PackageList.txt too with the new version of the package (for example the commit hash)

2019-10-31 07:22 UTC, Shauren commented on dep/argon2/CMakeLists.txt
> +    list(REMOVE_ITEM sources
Please fix indent size here (and in the else part) to match rest of the file

2019-10-31 08:25 UTC, damaex commented
The version in the PackageList.txt is already on point with the latest Upstream:
https://github.com/P-H-C/phc-winner-argon2/commit/62358ba2123abd17fccf2a108a301d4b52c01a7c

2019-10-31 09:05 UTC, jackpoz commented
does that mean that the version in PackagesList.txt doesn't match the version we have in /dep ?

2019-10-31 11:49 UTC, jackpoz commented
@Treeston could you take a look at this PR ? did you remove some code from argon2 when including it in TC ? is it ok to include it back ?

2019-10-31 12:43 UTC, Treeston commented
I stripped threading logic because we don't use it, and I didn't want foreign MT code in the TC codebase.

2019-10-31 12:54 UTC, Shauren commented
You should have just defined ARGON2_NO_THREADS

2019-10-31 12:55 UTC, Treeston commented
...I had some reason for not doing that at the time, though I have to admit I don't recall it.

2019-11-01 08:16 UTC, jackpoz commented
@Shauren were should ARGON2_NO_THREADS be defined ? In cmake somewhere ?

2019-11-01 09:04 UTC, Shauren commented
in argon2 CMakeLists.txt

2019-11-01 12:57 UTC, damaex commented
added ARGON2_NO_THREADS definition to argon2 library

2019-11-01 14:39 UTC, Shauren requested changes

2019-11-01 14:39 UTC, Shauren commented on dep/argon2/CMakeLists.txt
> +add_definitions(-DARGON2_NO_THREADS)
add_definitions is the old way of specifying compile flags, you should use

```
target_compile_definitions(argon2
  PRIVATE
    -DARGON2_NO_THREADS)
```

2019-11-01 14:39 UTC, Shauren commented on dep/argon2/CMakeLists.txt
>    ${CMAKE_CURRENT_SOURCE_DIR})
add extra indent level to this line too

2019-11-01 14:39 UTC, Shauren commented on dep/argon2/CMakeLists.txt
>    FOLDER
++indent (and on next line too)

2019-11-01 14:39 UTC, Shauren commented on dep/argon2/CMakeLists.txt
>    trinity-dependency-interface)
++indent

2019-11-01 17:57 UTC, Shauren approved these changes
This looks great, ship when it passes build test

2019-11-02 01:43 UTC, illfated commented
🔼  :shipit:

2019-11-02 10:04 UTC, merged