Core: build on aarch64 with gcc
TrinityCore/TrinityCore pull request #24216
Opened 2020-02-29 18:28 UTC by damaex

**Changes proposed:**

-  fixed GCC build on aarch64
    - missing `mm_malloc.h` on gcc for aarch64
        - added functions `_mm_malloc` and `_mm_free`
        - like https://clang.llvm.org/doxygen/mm__malloc_8h_source.html
    - don't force SSE2 flags for aarch64 with gcc

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Tests performed:** (Does it build, tested in-game, etc.)
- [x] build on raspberry pi 4 4GB (ubuntu 19.10 64bit + GCC 9.2.1)
- [x] connected and played 5 min with 2 accounts in parallel

2020-02-29 18:59 UTC, ghost approved these changes
LGTM

2020-03-01 09:10 UTC, jackpoz requested changes

2020-03-01 09:10 UTC, jackpoz commented on src/common/Utilities/SFMTRand.cpp
> +#if defined(__clang__) && defined(__aarch64__)
how about
```cpp
#if defined(__aarch64__)
  #if defined(__clang__)
  ...
  #elif defined(__GNUC__)
  ...
  #else
  "some error here"
  #endif
#else
...
```

2020-03-01 15:27 UTC, illfated commented on src/common/Utilities/SFMTRand.cpp
> +        _mm_malloc(size_t __size, size_t __align) {
TC C++ codestyle: put opening curly brackets ` { ` on a new line (see lower part of the file for examples)

2020-03-01 15:36 UTC, ghost approved these changes

2020-03-01 19:16 UTC, merged

2020-03-01 19:17 UTC, jackpoz commented
Thanks for the PR :)