Core/Gameobjects: Improve stealth detection
TrinityCore/TrinityCore pull request #24417
Opened 2020-04-09 11:49 UTC by Jildor

**Changes proposed:**

-  all explained here: https://github.com/TrinityCore/TrinityCore/issues/24224

Author: @joshwhedon
**Target branch(es):** 3.3.5/master

- [X] 3.3.5
- [ ] master

**Issues addressed:** Closes #24224

**Tests performed:** tested in-game

2020-04-09 19:59 UTC, Faq commented on src/server/game/Grids/Notifiers/GridNotifiers.h
> -                if (!i_obj->IsWithinDistInMap(u, i_range) || !i_funit->IsValidAttackTarget(u))
fatal error: private field 'i_funit' is not used

2020-04-11 18:13 UTC, jackpoz requested changes

2020-04-11 18:13 UTC, jackpoz commented on src/server/game/Spells/Spell.cpp
> +        if (m_originalCaster && !caster->ToGameObject())
could you please add a code comment here to explain why the check is needed and what it does ?

2020-04-11 18:15 UTC, jackpoz commented
I change a bit the code style, it should not have broken anything.

2020-04-12 08:03 UTC, Jildor commented
sure, feel free to modify whatever you want, thx 👍

2020-04-12 13:27 UTC, jackpoz approved these changes

2020-04-12 13:28 UTC, merged