Core/Player: add helper methods for PLAYER_FLAGS_DEVELOPER
TrinityCore/TrinityCore pull request #24511
Opened 2020-04-28 13:25 UTC by ForesterDev

**Changes proposed:**

-  Add helper methods IsDeveloper(), SetDeveloper(bool)
-  Update .dev command to new model

**Target branch(es):** 3.3.5/master

- [x] 3.3.5

**Tests performed:** (Does it build, tested in-game, etc.)
Tested in-game

2020-04-28 13:34 UTC, Shauren requested changes

2020-04-28 13:34 UTC, Shauren commented on src/server/scripts/Commands/cs_misc.cpp
> +        Player* _player = handler->GetSession()->GetPlayer();
local variable naming: remove `_`

2020-04-28 13:41 UTC, Shauren approved these changes

2020-04-29 20:41 UTC, merged

2020-04-29 20:41 UTC, jackpoz commented
Thanks for the PR :)