Core/Authserver: Clean up account table
TrinityCore/TrinityCore pull request #25135
Opened 2020-07-26 14:04 UTC by Treeston

Builds on #25131, merge that first please. View commits separately until then.

## Changes
* `seed` and `verifier` are now `BINARY(32)`, from `VARCHAR(64)`
* `SessionKey` is now `BINARY(40)`, from `VARCHAR(80)`

## Backwards compatibility
* `sha_pass_hash` is no longer updated, though external tools can still set it
* `sha_pass_hash` will only be used if `s`/`v` are explicitly set to empty strings from external tools

2020-07-26 14:49 UTC, jackpoz commented
> * `sha_pass_hash` is no longer updated, though external tools can still set it

this breaks https://github.com/TrinityCore/minimanager , in particular login using TC as auth. See https://github.com/TrinityCore/aowow/blob/master/includes/user.class.php#L286 .

It would be nice if that tool (and other tools under the TC umbrella) would be updated before merging this PR

2020-07-26 15:22 UTC, Treeston commented
@jackpoz we want some of the changes in this PR before updating external tools

re-added sha_pass_hash updating (for now)

2020-07-29 13:02 UTC, Shauren requested changes

2020-07-29 13:02 UTC, Shauren commented on src/server/authserver/Server/AuthSession.cpp
> +        fields[11].GetBinary(salt);
Can you use the other overload here (and everywhere else), this looks just weird/wrong

2020-07-31 18:31 UTC, jackpoz commented
I would add https://github.com/TrinityCore/account-creator also to the list of apps that would be nice to fix before merging this

2020-07-31 21:50 UTC, Shauren commented on src/server/authserver/Server/AuthSession.cpp
> +    if (result) do
dont mess with me

2020-08-02 20:52 UTC, merged