Scripts/World: updated Training Dummy script
TrinityCore/TrinityCore pull request #25169
Opened 2020-07-29 17:02 UTC by Ovahlord

**Changes proposed:**

-  updated script model to current standard
-  removed pointless 500 gametime timer event for checks and update combat timers in realtime instead.
-  changed training dummy from creatureai to NullCreatureAI since a dummy should not have any AI reaction at all.

**Target branch(es):** 3.3.5/master

- [x] 3.3.5
- [ ] master

**Tests performed:** (Does it build, tested in-game, etc.)
tested on 4.x

2020-07-29 17:06 UTC, Treeston approved these changes

2020-07-29 19:14 UTC, Carbenium requested changes
Since currently I'm not doing anything else, let's chrono-ify this one as well.

2020-07-29 19:14 UTC, Carbenium commented on src/server/scripts/World/npcs_special.cpp
> +        _combatTimer[attacker->GetGUID()] = int32(5 * IN_MILLISECONDS);
```suggestion
        _combatTimer[attacker->GetGUID()] = 5s;
```

2020-07-29 19:14 UTC, Carbenium commented on src/server/scripts/World/npcs_special.cpp
> +            itr->second -= diff;
```suggestion
            itr->second -= Milliseconds(diff);
```

2020-07-29 19:14 UTC, Carbenium commented on src/server/scripts/World/npcs_special.cpp
> +            if (itr->second <= 0)
```suggestion
            if (itr->second <= 0s)
```

2020-07-29 19:14 UTC, Carbenium commented on src/server/scripts/World/npcs_special.cpp
> +    std::unordered_map<ObjectGuid /*attackerGUID*/, int32 /*combatTime*/> _combatTimer;
```suggestion
    std::unordered_map<ObjectGuid /*attackerGUID*/, Milliseconds /*combatTime*/> _combatTimer;
```

2020-08-04 23:05 UTC, Carbenium approved these changes

2020-08-04 23:19 UTC, merged