[3.3.5] ChatCommands, the other half: chat command resolution refactor
TrinityCore/TrinityCore pull request #25463
Opened 2020-09-16 23:19 UTC by Treeston

Now that the command handler side is cleaned up with the dark arts of C++17 and template logic, time to tackle the other half of chat commands – the part that takes _what you enter in chat_ and comes up with _which command should be executed_.

Two main things to do here:

[x] Make command tables more readable in scripts
[ ] Get rid of `strtok` and move everything to `std::string_view` where it should be.

2020-09-16 23:20 UTC, Treeston commented
_(NB: This will not currently build. I have only changed one command script file (`cs_learn`) to the new constructors for the time being.)_

2020-09-16 23:23 UTC, Treeston commented
@Carbenium this is relevant to your interests

2020-09-17 11:55 UTC, Warpten commented on src/server/game/Chat/Chat.cpp
> +    if (str.substr(0, 12) != "TrinityCore\t")
C++20 starts_with (advstd?)

2020-09-18 07:31 UTC, jackpoz commented
is this going to be backward compatible with existing commands and command definitions ? I'm thinking about custom patches which added new commands

2020-09-18 11:46 UTC, Treeston commented
The `std::vector<ChatCommand>` will need to be replaced with `ChatCommandTable`. _(And I'll see if there is maybe some way we can work around that.)_ Apart from that, yes.

(However, you will get warnings for using the deprecated constructor.)

2020-09-18 13:04 UTC, Treeston commented
there you go @jackpoz, now std::vector<ChatCommand> will still work for legacy patches (with deprecation warnings)

2020-09-18 13:35 UTC, Treeston commented
todo port all the command scripts and get rid of the warning pragmas

2020-09-18 17:31 UTC, Shauren commented on src/server/scripts/Commands/cs_account.cpp
> +            { "",                   HandleAccountCommand,               rbac::RBAC_PERM_COMMAND_ACCOUNT,                    Console::No       },
so you realigned everything but left the closing } broken, nice

2020-09-18 17:46 UTC, Faq commented on src/server/scripts/Commands/cs_account.cpp
> +            { "2fa",                HandleAccountSet2FACommand,         rbac::RBAC_PERM_COMMAND_ACCOUNT_SET_2FA,            Console::Yes      },
```suggestion
            { "addon",              HandleAccountSetAddonCommand,       rbac::RBAC_PERM_COMMAND_ACCOUNT_SET_ADDON,          Console::Yes },
            { "sec regmail",        HandleAccountSetRegEmailCommand,    rbac::RBAC_PERM_COMMAND_ACCOUNT_SET_SEC_REGMAIL,    Console::Yes },
            { "sec email",          HandleAccountSetEmailCommand,       rbac::RBAC_PERM_COMMAND_ACCOUNT_SET_SEC_EMAIL,      Console::Yes },
            { "gmlevel",            HandleAccountSetSecLevelCommand,    rbac::RBAC_PERM_COMMAND_ACCOUNT_SET_SECLEVEL,       Console::Yes },  // temp for a transition period
            { "seclevel",           HandleAccountSetSecLevelCommand,    rbac::RBAC_PERM_COMMAND_ACCOUNT_SET_SECLEVEL,       Console::Yes },
            { "password",           HandleAccountSetPasswordCommand,    rbac::RBAC_PERM_COMMAND_ACCOUNT_SET_PASSWORD,       Console::Yes },
            { "2fa",                HandleAccountSet2FACommand,         rbac::RBAC_PERM_COMMAND_ACCOUNT_SET_2FA,            Console::Yes },
```

2020-09-18 17:47 UTC, Faq commented on src/server/scripts/Commands/cs_account.cpp
> +            { "2fa",                HandleAccountSet2FACommand,         rbac::RBAC_PERM_COMMAND_ACCOUNT_SET_2FA,            Console::Yes      },
Same for all.

2020-09-18 20:11 UTC, Shauren requested changes

2020-09-18 20:11 UTC, Shauren commented on src/server/worldserver/CommandLine/CliRunnable.cpp
> +    //@todo maybe? dear lord this readline business is UGLY
literally unmergable

2020-09-19 22:48 UTC, Shauren commented on src/server/game/Chat/ChatCommands/ChatCommand.h
> +        private:
.

2020-09-20 00:50 UTC, merged