Core/Spells - Checking Exile's Reach spell reward
TrinityCore/TrinityCore pull request #26036
Opened 2021-02-05 03:38 UTC by matanshukry

**Changes proposed:**

-  Spells that are rewarded on quest and are part of Exile's reach will be rewarded to players outside of exile's reach (everyone for now since exile's reach is not yet implemented)

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

(Does it build, tested in-game, etc.)

- [x] It builds
- [x] tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

2021-02-05 07:57 UTC, MaxtorCoder approved these changes

2021-02-06 11:04 UTC, illfated approved these changes
Looks pretty good & straightforward to me.

2021-02-06 20:48 UTC, Shauren requested changes
I would prefer to make this a bit more generic

* Rename flag to CanFallbackToLearnedOnSkillLearn
* Use if (!meets player condition from SpellMiscEntry::ShowFutureSpellPlayerConditionID) instead of IsStartingInExilesReach
* future note: if IsStartingInExilesReach becomes neccessary, name it "used NPE" (new player experience) to match the field name in packet for character creation
* dont use `this->`

2021-02-09 12:23 UTC, Shauren commented on src/server/game/Entities/Player/Player.h
> +        bool IsStartingInExilesReach() const { return false; } // NYI
This is not needed anymore, right?

2021-02-09 22:05 UTC, Shauren approved these changes

2021-02-09 22:06 UTC, merged