Core/Quests: When player interacts with npc it will show the quest window if there's
TrinityCore/TrinityCore pull request #26094
Opened 2021-02-15 09:28 UTC by matanshukry

**Changes proposed:**

-  When player interacts with npc it will show the quest window if there's only one quest

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

Closes #22010

**Tests performed:**

(Does it build, tested in-game, etc.)

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

- [] WorldPackets::Quest::QuestGiverRequestItems.StatusFlags currently we only use `canComplete ? 0xFF : 0xFD;`. However even when the quest isn't complete, player will get the message "You are already on that quest". `AutoLaunched` seems to not have a direct influence on that. I'm guessing there are other flags we're missing

2021-02-15 22:09 UTC, illfated commented
Since the PR title has been cut short, maybe rephrase it to make it quicker to read:

**Core/Quests: NPC shows Player Quest Window for singular Quest**

(This is merely a suggestion, use how much or little as you want. The main idea is to simplify the title as much as possible.)

2021-04-11 18:30 UTC, Shauren commented
All of these changes are unneccessary, all that you had to do was remove `source->GetTypeId() != TYPEID_UNIT || source->ToUnit()->HasNpcFlag(UNIT_NPC_FLAG_GOSSIP)` from `Player::SendPreparedQuest`

2021-04-11 18:33 UTC, Shauren requested changes
All of these changes are unneccessary, all that you had to do was remove `source->GetTypeId() != TYPEID_UNIT || source->ToUnit()->HasNpcFlag(UNIT_NPC_FLAG_GOSSIP)` from `Player::SendPreparedQuest`

2021-04-11 19:03 UTC, matanshukry commented
> All of these changes are unneccessary, all that you had to do was remove `source->GetTypeId() != TYPEID_UNIT || source->ToUnit()->HasNpcFlag(UNIT_NPC_FLAG_GOSSIP)` from `Player::SendPreparedQuest`

Yup "sadly" (not really) this is better; my bad.

2021-04-11 19:58 UTC, Shauren commented on src/server/game/Entities/Player/Player.cpp
> +            if (qmi0.QuestIcon == GOSSIP_ICON_INTERACT_1)
I would like you to revert this change - GOSSIP_ICON_INTERACT_1 is not the correct enum to use (there is no defined enum for this field)

2021-04-11 20:19 UTC, Shauren approved these changes

2021-04-11 20:22 UTC, merged