Scripts/Spells: Implemented druid's Skull Bash
TrinityCore/TrinityCore pull request #26103
Opened 2021-02-17 00:36 UTC by matanshukry

**Changes proposed:**

- Implemented druid's skull bash spell

**Target branch(es):** 3.3.5/master

- [ ] 3.3.5
- [x] master

**Issues addressed:**

**Tests performed:**

(Does it build, tested in-game, etc.)

- [x] It builds
- [x] Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

2021-02-17 09:42 UTC, offl commented
#19727?

2021-02-21 20:32 UTC, illfated commented
Would it be interesting to sort the enum DruidSpells list, or should we ignore it? I notice it got skipped in your Prayer of Mending PR.

2021-02-21 21:15 UTC, matanshukry commented
> Would it be interesting to sort the enum DruidSpells list, or should we ignore it? I notice it got skipped in your Prayer of Mending PR.

I'm planning another PR for paladin spells, was gonna sneak the priest enum into that.
I need to fix this one enum anyway, so might as well do it together as well.

2021-02-22 16:55 UTC, Shauren commented
This is incorrect (wrong sequencing and wrong spell ids)
Using 106839 immediately triggers two spells: 221514 (charge) and 93985 (interrupt). Interrupt does not happen when charge finishes movement (this is a general player interrupt thing, no interrupt of any class has travel time)

2021-02-22 19:52 UTC, matanshukry commented
Fixed

2021-02-22 20:28 UTC, Shauren requested changes

2021-02-22 20:28 UTC, Shauren commented on src/server/scripts/Spells/spell_druid.cpp
> +        return ValidateSpellInfo({ SPELL_DRUID_SKULL_BASH_CHARGE });
Missing SPELL_DRUID_SKULL_BASH_INTERRUPT here

2021-02-22 20:28 UTC, Shauren commented on src/server/scripts/Spells/spell_druid.cpp
> +    RegisterSpellScript(spell_dru_skull_bash);
sort by class name

2021-02-22 20:28 UTC, Shauren commented on src/server/scripts/Spells/spell_druid.cpp
> +class spell_dru_skull_bash : public SpellScript
scripts are sorted (i dont remember why anymore, but they are)

2021-02-22 21:08 UTC, Shauren approved these changes

2021-02-22 21:10 UTC, merged