Core/Quest: Remove RewardMoney from quest_template and send correct data
TrinityCore/TrinityCore pull request #27590
Opened 2022-01-10 22:18 UTC by funjoker

**Changes proposed:**

-  Remove static RewardMoney
-  Use correct values in packet

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**
It builds

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

2022-01-13 19:38 UTC, Shauren requested changes

2022-01-13 19:38 UTC, Shauren commented on src/server/game/Entities/Creature/GossipDef.cpp
> +        _session->SendPacket(queryPacket->Write());
Very much thread unsafe and completely removes the point of this cache - its fine if we just send "as if at max level for quest" value here when cache is enabled

2022-01-14 22:44 UTC, funjoker commented on src/server/game/Quests/QuestDef.cpp
>      if (QuestMoneyRewardEntry const* money = sQuestMoneyRewardStore.LookupEntry(player->GetQuestLevel(this)))
maybe make it else if ?

2022-01-16 18:47 UTC, Shauren commented on src/server/game/Quests/QuestDef.cpp
>      if (QuestMoneyRewardEntry const* money = sQuestMoneyRewardStore.LookupEntry(player->GetQuestLevel(this)))
Not a maybe, definitely (this crashes)

2022-01-18 20:22 UTC, merged