Core/Player: Added PlayerCreateMode field to playercreateinfo_cast_sp…
TrinityCore/TrinityCore pull request #27593
Opened 2022-01-11 01:29 UTC by mdX7

…ell to only cast spells based on related mode

**Tests performed:**

(Does it build, tested in-game, etc.)
built, tested ingame with undead in exiles reach and deathknell
(+ also used 295600 spell for exiles reach)

2022-01-13 19:36 UTC, Shauren requested changes

2022-01-13 19:36 UTC, Shauren commented on src/server/game/Globals/ObjectMgr.h
> +typedef std::unordered_map<PlayerCreateMode, PlayerCreateInfoSpells> PlayerCreateInfoSpellsMap;
no, just make that a plain array

2022-01-13 20:55 UTC, mdX7 commented on src/server/game/Globals/ObjectMgr.h
> +typedef std::unordered_map<PlayerCreateMode, PlayerCreateInfoSpells> PlayerCreateInfoSpellsMap;
done

2022-01-14 18:21 UTC, Shauren approved these changes

2022-01-14 18:52 UTC, merged