Core/PacketIO: Implement CMSG_UI_MAP_QUEST_LINES_REQUEST
TrinityCore/TrinityCore pull request #28010
Opened 2022-06-08 19:21 UTC by osleyder85

**Changes proposed:**

-  
-  
-  

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

(Does it build, tested in-game, etc.)

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

2022-06-08 19:48 UTC, MaxtorCoder commented
Db2 isn't loaded?

2022-06-08 19:51 UTC, osleyder85 commented
> Db2 isn't loaded?

Db2 uploaded by Shauren in this commit 5134622a75bdc8ffafb0d86e0c0275d731385d0c

2022-06-08 20:13 UTC, MaxtorCoder requested changes

2022-06-08 20:13 UTC, MaxtorCoder commented on src/server/game/Server/Packets/QuestPackets.cpp
> +        _worldPacket << questIDs;
```suggestion
    for (uint32 const& questID : QuestLineXQuestIDs)
        _worldPacket << uint32(questID);
```

2022-06-08 20:13 UTC, MaxtorCoder commented on src/server/game/Handlers/QuestHandler.cpp
> +    if (!uiMap)
```suggestion
    UiMapEntry const* uiMap = sUiMapStore.LookupEntry(uiMapQuestLinesRequest.UiMapID);
    if (!uiMap)
```

2022-06-08 20:13 UTC, MaxtorCoder commented on src/server/game/Handlers/QuestHandler.cpp
> +    }
```suggestion
    for (QuestLineXQuestEntry const* questLineXQuest : sQuestLineXQuestStore)
    {
        if (questLineXQuest->OrderIndex == 0)
            response.QuestLineXQuestIDs.push_back(questLineXQuest->ID);
    }
```

2022-06-09 11:27 UTC, Shauren commented
This is not good at all, you are always sending all questlines on all maps, ignoring the uimap

2022-06-11 05:59 UTC, closed without merging