Fixed the quest dialog not closing automatically when there are no other follow-up quests for the quest giver.
TrinityCore/TrinityCore pull request #28978
Opened 2023-05-13 05:57 UTC by HuangStomach

**Changes proposed:**

- Fixed the quest dialog not closing automatically when there are no other follow-up quests for the quest giver.
- Add the `const` keyword to functions and arguments that are semantically read-only.

**Issues addressed:**

discussion: https://github.com/TrinityCore/TrinityCore/discussions/28971#discussion-5188356

**Tests performed:**

build completed, tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

None.

2023-05-13 16:20 UTC, Shauren requested changes

2023-05-13 16:20 UTC, Shauren commented on src/server/game/Entities/Player/Player.cpp
> +        else if (questGiver->IsQuestGiver() && GetQuestDialogStatus(questGiver) > QuestGiverStatus::TrivialDailyQuest)
QuestGiverStatus is a bitmask type, use appropriate comparison operators

2023-05-14 12:44 UTC, ZaDarkSide commented
I don't think this fixes anything, for example quest [Join the Battle!](https://www.wowhead.com/quest=28780/join-the-battle) the 3rd Quest when playing as a Human Hunter in Northshire still gets stuck on screen after you press Accept button, curiously enough if you set in `WordServer.conf` the setting `Quests.IgnoreAutoAccept = 1` then the Quest Window no longer gets stuck on screen.

2023-05-14 14:02 UTC, HuangStomach commented
> I don't think this fixes anything, for example quest [Join the Battle!](https://www.wowhead.com/quest=28780/join-the-battle) the 3rd Quest when playing as a Human Hunter in Northshire still gets stuck on screen after you press Accept button, curiously enough if you set in the setting then the Quest Window no longer gets stuck on screen.`worldserver.conf``Quests.IgnoreAutoAccept = 1`

This change is in the `SendQuestReward` function and corrects the fact that the dialog box does not close automatically when the quest reward is obtained. I'll change the description of this pr.

2023-05-14 15:52 UTC, ZaDarkSide commented
Can you give an example of what Quest it fixes, like I did? So I can test before and after I applied your fix? Because I understand now, that my example issue is not the exact issue you are trying to solve, so my issue is a separate issue from this one.

2023-05-15 01:47 UTC, HuangStomach commented
I found this out when I first started the orc newbie quest.
For example, the first quest after choosing Exile's Reach [warming-up](https://www.wowhead.com/quest=59926/warming-up)
and the early quests in Valley of Trials [cactus-apple](https://www.wowhead.com/object=171938/cactus-apple)

2023-05-15 01:47 UTC, HuangStomach commented
I found this out when I first started the orc newbie quest.
For example, the first quest after choosing Exile's Reach [warming-up](https://www.wowhead.com/quest=59926/warming-up)
and the early quests in Valley of Trials [cactus-apple](https://www.wowhead.com/object=171938/cactus-apple)

2023-06-08 14:31 UTC, merged