Spells: Implement target threshold sqrt aoe reduction
TrinityCore/TrinityCore pull request #29192
Opened 2023-07-28 06:18 UTC by Seyden

**Changes proposed:**

Added 2 new script methods to overwrite target caps before hit hooks happen

-  Add SpellScript::SetSoftTargetCap
-  Add SpellScript::SetFullAmountTargetCap

SoftTargetCap is an value that determines how many targets can be hit before the square root aoe reduction kicks in. 
Default value is 0.

FullAmountTargetCap when used with SoftTargetCap > 0 determines how many target(s) will take the full unreduced amount. Default value is 0.

**Important note!!!:**
The soft target cap does not overwrite the aoe damage target cap, if a spell has a soft target cap listed in wowhead as 20, then its not needed to set it.

If the soft target cap is set to 6, it will only scale up to 20 and afterwards will be cut through 20 targets.

**Issues addressed:**

Closes #  (insert issue tracker number)

**Tests performed:**

(Does it build, tested in-game, etc.)
- [x] Builds
- [x] Tested in-game

2023-07-28 08:46 UTC, Nyr97 commented
I'm not sure the implementation is correct for the soft-cap since it's a known fact that class spells with both damage and healing effects have different soft-caps, which basically affects healing specializations across the board:

Chi Burst: damage soft-cap 20, healing soft-cap 6.

Hammer of Light: damage soft-cap 20, healing soft-cap 6.

Halo: damage soft-cap 20, healing soft-cap 6.

Divine Star: damage soft-cap 20, healing soft-cap 6.

2023-07-28 09:19 UTC, Shauren commented
All of the spells you mentioned (well idk about hammer of light) are areatriggers that cast single targeting spells on each individual unit and will not interact with this PR at all

2023-07-28 09:37 UTC, Nyr97 commented
Light's Hammer summons a npc, the caster gets aura 114918, which triggers 119952 (AoE healing) on the npc.

2023-08-20 22:17 UTC, Seyden commented
> Not sure the implementation is correct, BUT it's a known fact that class spells with both damage and healing effects have different soft-caps, which basically affects healing specializations across the board:
> 
> Chi Burst: damage soft-cap 20, healing soft-cap 6.
> 
> Light's Hammer: damage soft-cap 20, healing soft-cap 6.
> 
> Halo: damage soft-cap 20, healing soft-cap 6.
> 
> Divine Star: damage soft-cap 20, healing soft-cap 6.

I'm not quite sure what your intention is by posting this list, there is no question or anything inside your comment.

If your spell has a soft cap, you can assign a soft cap to it.

If your healing spell has a soft cap of 6, then you can set it to 6.

You dont have to set the soft cap for 20 targets anyway because its per default since wotlk for all AOE spells.

2023-08-21 11:18 UTC, Nyr97 commented
> Light's Hammer summons a NPC, its caster gets aura 114918, which triggers 119952 (AoE healing) periodically on the NPC's location, so yes, the spell will be affected by this.

This isn't supported correctly by your implementation.

2023-08-21 14:36 UTC, Seyden commented
> > Light's Hammer summons an NPC, and its caster gets aura 114918, which triggers 119952 (AoE healing) periodically on the NPC's location, so yes, the spell will be affected by this.
> 
> This won't be supported correctly by your implementation because the paladin triggers an AoE healing periodically on the summoned dummy, it's not an individual heal cast by an areatrigger.

I dont get what you mean, every cast which is a AOE, you can set the Soft Target Cap to 6, i dont see the problem?

2023-08-21 20:02 UTC, Shauren requested changes

2023-08-21 22:02 UTC, merged

2023-08-21 22:37 UTC, Seyden commented on src/server/game/Spells/Spell.cpp
> +                    m_damage *= AOE_DAMAGE_TARGET_CAP / targetCount;
Thank you for noticing !

2023-08-21 23:20 UTC, Seyden commented
@Shauren just if you missed the commit comments by any chance..

there are multiple spells which dynamically update the target cap based on talents and stuff..



ID - 198013 Eye Beam
Takes it from EFFECT_5

ID - 258926 Fel Barrage
Takes it from EFFECT_2

ID - 400370 Burning Vehemence
Is also taking it from basepoints and this is also a talent

This is also a talent which modifies another spell
https://www.wowhead.com/spell=403826/blade-of-vengeance

Deep Impact from Mage is also dynamic