Core/Battleground: Clean up some Team/TeamId parameters to use enums …
TrinityCore/TrinityCore pull request #29535
Opened 2023-12-28 10:28 UTC by Golrag

…instead of integer types

**Changes proposed:**

-  Change some integer types to Enum types in parameters/return types/members

**Issues addressed:**

Closes: None

**Tests performed:**

- Builds

**Known issues and TODO list:**

- None

2023-12-28 18:56 UTC, Shauren requested changes

2023-12-28 18:56 UTC, Shauren commented on src/server/game/World/World.h
> +        void SendZoneText(uint32 zone, const char *text, WorldSession* self = nullptr, Team team = TEAM_OTHER);
These would have been better as `Optional<Team> team = {}`

2023-12-28 19:00 UTC, Golrag commented on src/server/game/World/World.h
> +        void SendZoneText(uint32 zone, const char *text, WorldSession* self = nullptr, Team team = TEAM_OTHER);
Alright!

2023-12-28 22:42 UTC, jackpoz commented
> **Tests performed:**
> 
> * Builds

Marking this PR as draft, please test it and then publish it again

2023-12-29 10:29 UTC, Golrag commented
Tests performed (after rebase):
- Outdoor pvp Hellfire: checked if monster credit was granted
- Outdoor pvp Nagrand: halaa take over
- Outdoor pvp terrokar: tower take over quest credit
- battleground queue & win

2023-12-29 13:11 UTC, Shauren approved these changes

2023-12-29 13:12 UTC, merged