Core/Creatures: Implemented UNIT_NPC_FLAG_GOSSIP as viewer dependent …
TrinityCore/TrinityCore pull request #29646
Opened 2024-01-31 16:29 UTC by mdX7

…and update npcflags on quest changes

**Tests performed:**
tested ingame, utilizing gossip menu conditions

2024-02-11 14:45 UTC, Shauren requested changes

2024-02-11 14:45 UTC, Shauren commented on src/server/game/Entities/Player/Player.cpp
> +        QuestRelationResult objectQR = sObjectMgr->GetCreatureQuestRelations(creature->GetEntry());
Move this to just before loop (so that its never called if any of objectQIR returns true)

2024-02-13 21:33 UTC, killerwife commented
What expansion is this used in

2024-02-13 21:38 UTC, mdX7 commented
I've seen it minimum in BfA

2024-02-16 17:24 UTC, Shauren commented on src/server/game/Entities/Player/Player.cpp
> +    SendDirectMessage(&packet);
```suggestion
    if (!udata.HasData())
        return;

    WorldPacket packet;
    udata.BuildPacket(&packet);
    SendDirectMessage(&packet);
```

2024-02-24 11:48 UTC, Shauren approved these changes

2024-02-24 14:05 UTC, merged