Wandering isle quest 29419
TrinityCore/TrinityCore pull request #29821
Opened 2024-03-19 23:00 UTC by aquadeus

**Changes proposed:**

-  Script quest 29419 blizzlike

**Tests performed:**

Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

- Npcs Amberleaf scamp should walk/run randomly when random movement is set and walk when movetargetedhome is set

2024-03-26 01:33 UTC, mdX7 requested changes

2024-03-26 01:33 UTC, mdX7 commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +                case 0:
magic numbers

2024-03-26 01:33 UTC, mdX7 commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +            if (waypointId == 3)
magic numbers

2024-03-26 01:33 UTC, mdX7 commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +        if (id == 0)
magic numbers

2024-03-26 01:33 UTC, mdX7 commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +                    Unit* summoner = me->ToTempSummon()->GetSummonerUnit();
crash when `me->ToTempSummon()` null

2024-03-26 01:33 UTC, mdX7 commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +                    summoner->RemoveAurasDueToSpell(SPELL_SUMMON_CART_DRIVER);
crash when summoner null

2024-03-27 20:42 UTC, Shauren commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +                PhasingHandler::OnConditionChange(player); // blizzard adds phase 630 when kill credit but immediately is removed to add it again when Min Dimwind reaches final waypoint
remove blizzard from comment

2024-04-08 17:31 UTC, Shauren requested changes

2024-04-11 12:51 UTC, Shauren commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +        me->GetMotionMaster()->MoveIdle();
Wouldn't `GetMotionMaster()->InitializeDefault()` be more appropriate here?

2024-04-12 11:08 UTC, aquadeus commented
> Conflicting files src/server/scripts/Pandaria/zone_the_wandering_isle.cpp

done

2024-04-12 20:28 UTC, Shauren commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +                player->CastSpell(player, SPELL_SERVERSIDE_DRIVER_CREDIT, TRIGGERED_FULL_MASK);
this shows the PR was untested

2024-04-12 20:30 UTC, merged