Scripts/Wandering isle: Handle quest 29414 (The way of the Tushui)
TrinityCore/TrinityCore pull request #29846
Opened 2024-03-29 12:26 UTC by aquadeus

**Changes proposed:**

-  Implement quest 29414 more blizzlike

**Tests performed:**

Tested in-game

**Known issues and TODO list:** (add/remove lines as needed)

- Adjust spawn position of the npcs spawned by spell 114710 / 114698 (must be spawned outside the cave)
- Implement Summonpropertiesflag UseDemonTimeout (atm they dissapear when aura is removed, and they shouldn't)

2024-04-08 17:27 UTC, Shauren requested changes

2024-04-08 17:27 UTC, Shauren commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +Position const aysaJumpPos[3] =
can be constexpr now

2024-04-08 17:27 UTC, Shauren commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +        _scheduler.Schedule(Seconds(3), [this](TaskContext task)
`Seconds(3)` -> `3s` (apply everywhere, too many to list)

2024-04-08 17:27 UTC, Shauren commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +        if (player->HasAura(SPELL_MEDITATION_TIMER_BAR))
`HasAura` unneccessary before `RemoveAura`

2024-04-08 17:27 UTC, Shauren commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +    bool talkDone = false;
Fundamentally broken, there is only one copy of `at_inside_of_cave_of_meditation` in worldserver, you will need to store it in script of the summoned creature

2024-04-08 17:27 UTC, Shauren commented on src/server/scripts/Pandaria/zone_the_wandering_isle.cpp
> +                target->RemoveAura(GetId());
Just call `this->Remove()` (without this->)

2024-04-11 12:29 UTC, Shauren requested changes

2024-04-11 22:15 UTC, Aokromes commented
Conflicting files
src/server/scripts/Pandaria/zone_the_wandering_isle.cpp

2024-04-12 11:08 UTC, aquadeus commented
> Conflicting files src/server/scripts/Pandaria/zone_the_wandering_isle.cpp

done

2024-07-10 20:33 UTC, merged