Core/Spells: Attempt to fix an ancient issue where Shadowform cooldown stuck untill relog
TrinityCore/TrinityCore pull request #29886
Opened 2024-04-03 13:24 UTC by CraftedRO

**Changes proposed:**

-  Attempt to fix an ancient issue where Shadowform cooldown stuck untill relog
-  Fix was provided by [Langerz82](https://github.com/Langerz82) in the targeted issue comments section.

**Issues addressed:**

Closes https://github.com/TrinityCore/TrinityCore/issues/18178

**Tests performed:**

Does it build, tested in-game, as you can see below:

Before: https://youtu.be/IXLfiyOGKUE

After: https://youtu.be/leSUubEQBgU

**Known issues and TODO list:** (add/remove lines as needed)

- [ No issue, but I guess this might look like a hack. ]

2024-04-03 13:34 UTC, CraftedRO commented
GCC sometimes is useless

2024-04-03 16:21 UTC, r4d1sh requested changes

2024-04-03 16:21 UTC, r4d1sh commented on src/server/game/Spells/Spell.cpp
> +            else if (m_castItemEntry)
You can significantly simplify the code to one line: `return m_castItemEntry ? SPELL_FAILED_NOT_READY : SPELL_FAILED_DONT_REPORT;`

2024-04-03 21:23 UTC, CraftedRO commented
well judged by Rizztazz comment, your proposed fix might be more to the point, also I tested it and it works well.

2024-04-04 19:44 UTC, Shauren requested changes

2024-04-04 19:44 UTC, Shauren commented on src/server/game/Spells/Spell.cpp
> +            if (m_triggeredByAuraSpell || m_spellInfo->HasAttribute(SPELL_ATTR0_DISABLED_WHILE_ACTIVE))
Use IsCooldownStartedOnEvent() instead of direct attribute check (spell category matters here too and that function checks it)

2024-04-06 20:53 UTC, merged