Core/Creatures: moved combat pulse into heartbeat handling and implemented CREATURE_STATIC_FLAG_2_FORCE_PARTY_MEMBERS_INTO_COMBAT
TrinityCore/TrinityCore pull request #29946
Opened 2024-04-27 15:36 UTC by Ovahlord

**Changes proposed:**

-  the combat pulse mechanic is being moved into heartbeat handling and now fires once on engaging a creature
-  This mechanic will now only kick in for creatures that use CREATURE_STATIC_FLAG_2_FORCE_PARTY_MEMBERS_INTO_COMBAT
- this furthermore no longer binds the mechanic to dungeons but it can now also act in the open world since we now draw our targets from combat references instead of iterating over the entire map.

**Tests performed:**
- to be tested.

2024-04-27 15:47 UTC, Nyr97 commented
Are you sure this must be set for all bosses? Asking because I've been recently playing wotlk classic and on low level dungeons, for example, Deadmines, when engaging a boss, I wouldn't be dragged into combat if my team mates engaged it while I was drinking. And as far as I recall, engaging would break drinking.

2024-04-27 15:52 UTC, Ovahlord commented
It is.

2024-04-27 15:55 UTC, Ghaster commented
Flag was also added (at earliest) very late in Vanilla or very early TBC so there's a chance that earlier Vanilla bosses simply didn't have the flag until later.

2024-04-27 15:57 UTC, Ovahlord commented
It applies primarily for raid bosses only. Dungeon bosses are not part of this mechanic for most of the part.

2024-04-27 15:59 UTC, Nyr97 commented
I see then, thanks for the clarification!

2024-04-28 00:09 UTC, Nyr97 commented
Since you've removed DoZoneInCombat(), this means that, in raid encounters where there are creatures that engage the boss when players do, e.g., Archimonde in Hellfire Citadel or Sylvanas Windrunner in Sanctum of Domination, we're forced to find those creatures and call AttackStart on the bosses, is that it?

2024-04-28 00:34 UTC, moJIto-ice commented on src/server/game/Entities/Creature/Creature.cpp
> +    ForcePartyMembersIntoCombat();
hmmmmmmm,. group updates packets also used to be updated here ( i meen health, auras of group members etc ) or it should be called from ::Heartbeat( ) ?

2024-04-28 08:10 UTC, Ovahlord commented
> Since you've removed DoZoneInCombat(), this means that, in raid encounters where there are creatures that engage the boss when players do, e.g., Archimonde in Hellfire Citadel or Sylvanas Windrunner in Sanctum of Domination, we're forced to find those creatures and call AttackStart on the bosses, is that it?

DoZoneInCombat only put all players (and their summons) on the map in combat with the target creature. So it was just making sure that when you engage the boss (e.g. Tank start attacking) that all players were put in combat which is only correct for raid bosses and this is now done via static flag and only for party members, not for all players on the map.

2024-04-28 11:47 UTC, Shauren requested changes

2024-04-28 11:47 UTC, Shauren commented on src/server/game/Entities/Creature/Creature.cpp
> +        for (auto const* itr = partyToForceIntoCombat->GetFirstMember(); itr != nullptr; itr = itr->next())
bad auto

2024-04-28 12:37 UTC, Shauren approved these changes

2024-04-28 14:09 UTC, merged