Ragefire chasm instance sai
TrinityCore/TrinityCore pull request #30015
Opened 2024-05-30 21:44 UTC by aquadeus

…inside the instance and misc

**Changes proposed:**

-  Add SAI for creatures, areatriggers and npcs for quest inside the instance

**Tests performed:**
Tested in-game

2024-06-02 15:42 UTC, mdX7 requested changes

2024-06-02 15:42 UTC, mdX7 commented on src/server/scripts/Kalimdor/RagefireChasm/ragefire_chasm.cpp
> +        adolescentFlameHound1->GetMotionMaster()->MovePoint(POINT_INTRO, AdolescentFlameHoundIntro[0]);
```cpp
if (Creature* adolescentFlameHound = player->FindNearestCreatureWithOptions(80.0f, { .StringId = "npc_adolescent_flame_hound_1" }))
    adolescentFlameHound->GetMotionMaster()->MovePoint(POINT_INTRO, AdolescentFlameHoundIntro[0]);
```
do it similarly for all the other doggos

2024-06-02 15:42 UTC, mdX7 commented on src/server/scripts/Kalimdor/RagefireChasm/ragefire_chasm.cpp
> +        if (GetCaster()->ToCreature()->HasStringId("npc_rescued_cage_1"))
move `GetCaster()->ToCreature()` to a variable, e.g. `casterCreature`, and use that instead of casting x times

2024-06-03 10:28 UTC, mdX7 commented on src/server/scripts/Kalimdor/RagefireChasm/ragefire_chasm.cpp
> +        Creature* casterCreature = GetCaster()->ToCreature();
possible crash if caster isn't a creature.
```suggestion
        Creature* casterCreature = GetCaster()->ToCreature();
        if (!casterCreature)
            return;
```

2024-07-05 21:31 UTC, meji46 commented on sql/updates/world/master/2024_99_99_99_ragefire_chasm_instance_smart_ai.sql
> +UPDATE `creature_template_difficulty` SET `ContentTuningID`=207, `StaticFlags1`=0 WHERE `Entry`=61680; -- Kor'kron Scout
Check current value for StaticFlags1 (probably you're removing a serverside flag) and drop data for Difficulty 1 for every creature entry

2024-07-05 21:31 UTC, meji46 commented on sql/updates/world/master/2024_99_99_99_ragefire_chasm_instance_smart_ai.sql
> +UPDATE `creature_template` SET `unit_flags`=32832, `unit_flags2`=2048 WHERE `entry`=61788; -- SI:7 Ranger
Current parser doesn't update unit_flags adding UNIT_FLAG_CAN_SWIM (0x8000) (it should update StaticFlags1 adding CREATURE_STATIC_FLAG_CAN_SWIM)

2024-07-05 21:31 UTC, meji46 commented on sql/updates/world/master/2024_99_99_99_ragefire_chasm_instance_smart_ai.sql
> +(7897, 2, 0, 0, 46, 0, 100, 0, 7897, 0, 0, 0, 0, 86, 119742, 0, 7, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'On Trigger - Cast Lava on Invoker');
SMART_ACTION_INVOKER_CAST (134)

2024-07-05 21:31 UTC, meji46 commented on sql/updates/world/master/2024_99_99_99_ragefire_chasm_instance_smart_ai.sql
> +(7898, 2, 0, 0, 46, 0, 100, 0, 7898, 0, 0, 0, 0, 86, 119741, 0, 7, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'On Trigger - Cast Lava on Invoker');
SMART_ACTION_INVOKER_CAST (134)

2024-07-05 21:31 UTC, meji46 commented on sql/updates/world/master/2024_99_99_99_ragefire_chasm_instance_smart_ai.sql
> +(211885, 1, 3, 0, '', 70, 0, 100, 0, 2, 0, 0, 0, 0, '', 86, 101163, 0, 19, 61680, 0, 0, 0, NULL, 19, 61680, 0, 0, 0, NULL, 0, 0, 0, 0, 'Scout Cage - On State Changed - Cast Spell 101163 to Kor\'kron
Maybe you can link the alliance and horde related SAI respectively (so you only need 2 conditions by go)

2024-07-05 21:31 UTC, meji46 commented on sql/updates/world/master/2024_99_99_99_ragefire_chasm_instance_smart_ai.sql
> +((61790 * 100), 9, 2, 0, '', 0, 0, 100, 0, 0, 0, 0, 0, 0, '', 97, 14, 0, 57, 0, 1, 0, 0, NULL, 8, 0, 0, 0, 0, NULL, -87.7343, 57.2282, -18.1655, 0, 'Action list - Self: Jump To Pos');
Link OnGossipSelect actions (you need to reorder them to be able to use the conditions)

2024-07-05 21:31 UTC, meji46 commented on sql/updates/world/master/2024_99_99_99_ragefire_chasm_instance_smart_ai.sql
> +((61780 * 100), 9, 3, 0, '', 0, 0, 100, 0, 0, 0, 0, 0, 0, '', 97, 14, 0, 131, 0, 1, 0, 0, NULL, 8, 0, 0, 0, 0, NULL, -308.103, -15.2036, -56.5575, 0, 'Action list - Self: Jump To Pos');
Same (link OnGossipSelect actions)

2024-07-05 21:31 UTC, meji46 commented on sql/updates/world/master/2024_99_99_99_ragefire_chasm_instance_smart_ai.sql
> +(61658, 0, 6, 0, '', 6, 0, 100, 0, 0, 0, 0, 0, 0, '', 11, 120292, 0, 0, 0, 0, 0, 0, NULL, 16, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 'Mature Flame Hound - On Death - Cast spell 120292 on Invoker Party');
Link

2024-09-01 19:03 UTC, merged