Core/Spells: Fixed UnitData::ChannelObjects for channeled spells using dest targets
TrinityCore/TrinityCore pull request #30027
Opened 2024-06-06 21:24 UTC by meji46

…g dest targets

**Changes proposed:**

-  Fix UnitData::ChannelObjects for channeled spells using dest targets

**Issues addressed:**
None

**Tests performed:**
Builds, tested in-game (Spell: 160415 Tuulani Unlock Visual)

**Known issues and TODO list:** (add/remove lines as needed)
None

2024-06-07 01:53 UTC, mdX7 approved these changes

2024-06-07 08:12 UTC, Shauren requested changes
Do not merge - needs more research on spells like this

```
ID - 52185 Bindings of Submission

AttributesEx1: 0x00000044 (SPELL_ATTR1_IS_CHANNELLED, SPELL_ATTR1_IS_SELF_CHANNELLED)

=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
Difficulty: Id 0 (DIFFICULTY_NONE)
BasePoints = 0.00
Targets (22, 7) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ENTRY)
Aura Id 4 (SPELL_AURA_DUMMY), value = 0, misc = 0 (0), miscB = 0, amplitude = 0, periodic = 0
TargetBRadius (Id 48) 60.00 (Min: 0.00 Max: 60.00)

Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
Difficulty: Id 0 (DIFFICULTY_NONE)
BasePoints = 0.00
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 40 (SPELL_AURA_DAMAGE_IMMUNITY), value = 0, misc = 127 (127), miscB = 0, amplitude = 0, periodic = 0

Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
Difficulty: Id 0 (DIFFICULTY_NONE)
BasePoints = 0.00
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 26 (SPELL_AURA_MOD_ROOT), value = 0, misc = 0 (0), miscB = 0, amplitude = 0, periodic = 0
```

2024-06-07 16:28 UTC, Nyr97 commented
Maybe when both are present we should iterate through all targets of the existing effects of the spell and exclude SELF_CHANNEL from any that's not the caster and SPELL_ATTR1_IS_CHANNELLED from the caster huh

2024-06-10 16:41 UTC, meji46 commented
> Needs more research on spells like this
> 
> ```
> ID - 52185 Bindings of Submission
> 
> AttributesEx1: 0x00000044 (SPELL_ATTR1_IS_CHANNELLED, SPELL_ATTR1_IS_SELF_CHANNELLED)
> 
> =================================================
> Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
> Difficulty: Id 0 (DIFFICULTY_NONE)
> BasePoints = 0.00
> Targets (22, 7) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ENTRY)
> Aura Id 4 (SPELL_AURA_DUMMY), value = 0, misc = 0 (0), miscB = 0, amplitude = 0, periodic = 0
> TargetBRadius (Id 48) 60.00 (Min: 0.00 Max: 60.00)
> 
> Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
> Difficulty: Id 0 (DIFFICULTY_NONE)
> BasePoints = 0.00
> Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
> Aura Id 40 (SPELL_AURA_DAMAGE_IMMUNITY), value = 0, misc = 127 (127), miscB = 0, amplitude = 0, periodic = 0
> 
> Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
> Difficulty: Id 0 (DIFFICULTY_NONE)
> BasePoints = 0.00
> Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
> Aura Id 26 (SPELL_AURA_MOD_ROOT), value = 0, misc = 0 (0), miscB = 0, amplitude = 0, periodic = 0
> ```
> 
> What is special here is that both attributes are present and there are effects that target both intended targets and caster

```
[0] Object Guid: Full: 0x20309C47601BFCC0000084000065FCDF Creature/0 R3111/S132 Map: 571 (Northrend) Entry: 28659 (Artruis the Heartless) Low: 6683871
[0] [0] ChannelObjects: Full: 0x20309C47601BFEC0000084000065FCE0 Creature/0 R3111/S132 Map: 571 (Northrend) Entry: 28667 (Jaloot) Low: 6683872
[0] [1] ChannelObjects: Full: 0x20309C47601BFF00000084000065FCE0 Creature/0 R3111/S132 Map: 571 (Northrend) Entry: 28668 (Zepik the Gorloc Hunter) Low: 6683872
[0] [2] ChannelObjects: Full: 0x20309C47601BFCC0000084000065FCDF Creature/0 R3111/S132 Map: 571 (Northrend) Entry: 28659 (Artruis the Heartless) Low: 6683871
[0] (ChannelData) SpellID: 52185
[0] (ChannelData) (SpellVisual) SpellXSpellVisualID: 25535
[0] (ChannelData) (SpellVisual) ScriptVisualID: 0
```

2024-06-10 20:46 UTC, Shauren approved these changes

2024-06-10 20:46 UTC, merged