Scripts/Waycrest Manor: Implement Soulbound Goliath encounter (all difficulties)
TrinityCore/TrinityCore pull request #30074
Opened 2024-07-08 22:55 UTC by aquadeus

**Changes proposed:**

-  Implement Soulbound Goliath encounter (all difficulties)

**Tests performed:**

Tested in-game

2024-07-09 17:18 UTC, mdX7 requested changes
also missing boundary for resets (should reset when you pull him into building i think)

2024-07-09 17:18 UTC, mdX7 commented on src/server/scripts/KulTiras/WaycrestManor/boss_soulbound_goliath.cpp
> +    SAY_SOUL_HARVEST    = 6 // NYI I don't know when is used
when is it used in sniff?

2024-07-09 17:18 UTC, mdX7 commented on src/server/scripts/KulTiras/WaycrestManor/boss_soulbound_goliath.cpp
> +                summoner->RemoveAurasDueToSpell(GetEffectValue());
missing validate

2024-07-09 17:18 UTC, mdX7 commented on src/server/scripts/KulTiras/WaycrestManor/boss_soulbound_goliath.cpp
> +        if (map->IsDungeon() && map->IsHeroicOrHigher())
is dungeon check is unnecessary - or is this aura also used outside dungeons?

2024-07-09 17:18 UTC, mdX7 commented on src/server/scripts/KulTiras/WaycrestManor/boss_soulbound_goliath.cpp
> +        GetTarget()->ToCreature()->GetMotionMaster()->Clear();
what if GetTarget() isn't a creature?

2024-07-09 17:18 UTC, mdX7 commented on src/server/scripts/KulTiras/WaycrestManor/waycrest_manor.cpp
> +            GetTarget()->CastSpell(randomPos, aurEff->GetSpellEffectInfo().CalcValue(), TRIGGERED_FULL_MASK);
missing validate

2024-07-09 21:54 UTC, aquadeus commented on src/server/scripts/KulTiras/WaycrestManor/boss_soulbound_goliath.cpp
> +    SAY_SOUL_HARVEST    = 6 // NYI I don't know when is used
in the middle of the combat

2024-07-10 17:42 UTC, mdX7 commented on src/server/scripts/KulTiras/WaycrestManor/waycrest_manor.h
> +enum WaycrestManorSharedMisc
split into two enums: `WaycrestManorSpells` and `WaycrestManorActions`

2024-07-30 21:37 UTC, mdX7 approved these changes

2024-07-30 21:37 UTC, merged