Scripts/Command Use linked bonuses & context for .additem command
TrinityCore/TrinityCore pull request #30209
Opened 2024-09-05 02:10 UTC by Traesh

**Changes proposed:**

-  Let .additem commands use the bonuses & itemcontext from linked items.
-  Allow to add item directly from link with correct bonuses & context
-  

**Issues addressed:**

None

**Tests performed:**

Built, tested ingame

**Known issues and TODO list:** (add/remove lines as needed)

2024-09-05 21:34 UTC, CraftedRO commented
if this does what I think, I guess it will need some merge to 3.3.5 too.

2024-09-05 22:13 UTC, Traesh commented
@CraftedRO Not needed afaik, there is no bonus or context on items in 3.3.5

2024-09-05 22:16 UTC, CraftedRO commented
ah ok then that's another case to be able to properly add items with this command via itemname / link.

2024-09-06 15:33 UTC, Shauren commented
I like the idea but not the implementation. Ideally it would be directly accessible through typed command args (Hyperlink<item>) but im not judging it yet (no idea if its easily doable)

2024-09-17 14:19 UTC, Shauren requested changes
Needs changing after 1f60e76b7f157af6a24fa3c962b59f3391b21e75

2025-01-07 17:05 UTC, closed without merging