Scripts/Spells: Fix Rogue Stealth with cleanup for dropped spells and…
TrinityCore/TrinityCore pull request #30378
Opened 2024-10-26 21:45 UTC by aquadeus

… deleting related spells to move them in their own scripts

**Changes proposed:**

-  Fix Rogue Stealth with cleanup for dropped spells and deleting related spells to move them in their own scripts

**Tests performed:**

Tested in-game

2024-11-10 18:13 UTC, Shauren requested changes
What is with this PR? I can see Master of Subtlety and Death from Above being removed from the game but Shadow Focus and Premeditation are still very much part of Subtlety talent tree. Don't just completely remove their code without also adding their own scripts as you wrote in PR description

2024-11-10 18:38 UTC, aquadeus commented
mb i had the scripts done but i forgot to push them

2024-11-10 22:15 UTC, aquadeus commented
added missing scripts

2024-11-10 22:26 UTC, Aokromes commented
Conflicting files
src/server/scripts/Spells/spell_rogue.cpp

2024-11-10 22:31 UTC, aquadeus commented
done

2024-11-10 22:58 UTC, Aokromes commented
/home/runner/work/TrinityCore/TrinityCore/src/server/scripts/Spells/spell_rogue.cpp:841:2: error: expected ‘;’ after class definition
  841 | }
      |  ^
      |  ;
compilation terminated due to -Wfatal-errors.

2024-11-16 22:26 UTC, Shauren requested changes

2024-11-16 22:26 UTC, Shauren commented on sql/updates/world/master/2024_99_99_99_shadow_focus_and_premeditation.sql
> +(343173,0x00,8,0x00000000,0x00400000,0x00000000,0x00000000,0x0,0x0,0x1,0x2,0x0,0x0,0x0,0,0,0,0); -- Premeditation
This mask includes too many spells (finishing moves, instant poison damage proc)

2024-11-16 22:26 UTC, Shauren commented on sql/updates/world/master/2024_99_99_99_shadow_focus_and_premeditation.sql
> +(185313, 'spell_rog_shadow_focus');
spell_rog_premeditation_proc not assigned

2024-11-24 15:14 UTC, merged