Scripts/Wandering Isle: Implement quest 29420 (The Spirit's Guardian)
TrinityCore/TrinityCore pull request #30467
Opened 2024-11-29 14:15 UTC by aquadeus

**Changes proposed:**

-  Implement quest 29420 (The Spirit's Guardian)

**Tests performed:**

Tested in-game

2025-04-15 22:35 UTC, Naddley requested changes

2025-04-15 22:35 UTC, Naddley commented on sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql
> +(30, 0, 7736, 0, 0, 1, 0, 92571, 0, 0, 1, 0, 0, '', 'Areatrigger 7736 only triggers when player has not aura 92571');
wrong SourceGroup in DELETE

2025-04-15 22:35 UTC, Naddley commented on sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql
> +(32, 5, 59626, 0, 0, 47, 0, 29420, 2, 0, '', 0, 0, 0, '', 'Flame Spout gets visible if Quest: 29420 is completed');
missing SourceGroup in DELETE

2025-04-15 22:35 UTC, Naddley commented on sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql
> +(7736, 2, 0, 0, 46, 0, 100, 0, 7736, 0, 0, 0, 0, '', 86, 92571, 2, 19, 60176, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'On Trigger - Cast CSA Area Trigger Dummy Timer Aura');
param1 is not needed anymore for EventType 46

2025-04-15 22:35 UTC, Naddley commented on sql/updates/world/master/2024_99_99_99_wandering_isle_quest_29420.sql
> +UPDATE `creature_template_addon` SET `auras`='96112' WHERE `entry`=59626; -- 59626 (Flame Spout) - Shrink
missing script for spell

2025-06-14 22:32 UTC, mdX7 approved these changes

2025-06-14 22:33 UTC, merged