Scripts/Spells: Implement demon hunter talent "Restless Hunter"
TrinityCore/TrinityCore pull request #30484
Opened 2024-12-05 13:27 UTC by aquadeus

**Changes proposed:**

-  Implement demon hunter talent "Restless Hunter"

**Tests performed:**

Tested in-game

2024-12-25 18:43 UTC, Shauren requested changes

2024-12-25 23:13 UTC, aquadeus commented on src/server/scripts/Spells/spell_dh.cpp
> +        AfterEffectRemove += AuraEffectRemoveFn(spell_dh_restless_hunter::OnRemove, EFFECT_0, SPELL_AURA_TRANSFORM, AURA_EFFECT_HANDLE_REAL);
done (ill try to fix demonic tomorrow)

2024-12-25 23:13 UTC, aquadeus commented on sql/updates/world/master/2024_99_99_99_dh_restless_hunter.sql
> +(390212,0x00,107,0x00001000,0x00000000,0x00000000,0x00000000,0x0,0x0,0x1,0x1,0x0,0x12,0x0,0,0,0,0); -- Restless Hunter
done

2024-12-30 19:39 UTC, Shauren approved these changes

2024-12-30 19:40 UTC, merged