Scripts/Spells: Implement demon hunter talent "Glaive Tempest"
TrinityCore/TrinityCore pull request #30551
Opened 2024-12-27 20:35 UTC by aquadeus

**Changes proposed:**

-  Implement demon hunter talent "Glaive Tempest" (areatrigger)

**Tests performed:**

Tested in-game

2025-01-15 18:34 UTC, mdX7 commented on src/server/scripts/Spells/spell_dh.cpp
> +        _scheduler.Schedule(200ms, 250ms, [this](TaskContext task)
at spell has SPELL_ATTR8_HASTE_AFFECTS_DURATION, that means more haste => less duration. With the current approach that'd be a disadvantage. Count the amount of ticks done and then use at max duration/<max ticks> as tickrate

2025-01-15 20:09 UTC, Shauren requested changes

2025-01-15 20:09 UTC, Shauren commented on src/server/scripts/Spells/spell_dh.cpp
> +        _scheduler.Schedule(200ms, 250ms, [this](TaskContext task)
This spell ticks 7 (* 2) times, with a tick on cast (SPELL_ATTR5_EXTRA_INITIAL_PERIOD) and 500ms period (affected by melee haste)
Duration is snapshotted on cast
Haste is recalculated every tick (might cause you to gain/lose ticks!)
Every tick cast the spell twice (simulating separate main/off hand hits, no special handling for that required, just cast twice)

see 55dda32225a653d1ecdd44d88e8566f8dd2f4121 for haste handling (except use ModHaste instead of ModCastingSpeed for melee haste)

2025-01-17 10:22 UTC, Shauren approved these changes

2025-01-17 10:22 UTC, merged